// Generated by pnpm run types:scripting. Do not edit directly.

/* eslint-disable */

type ScriptPipe = {
  <A>(value: A): A;
  <A, B>(value: A, ab: (a: A) => B): B;
  <A, B, C>(value: A, ab: (a: A) => B, bc: (b: B) => C): C;
  <A, B, C, D>(
    value: A,
    ab: (a: A) => B,
    bc: (b: B) => C,
    cd: (c: C) => D,
  ): D;
};

interface ScriptEffectModule {
  readonly [key: string]: any;
}

interface ScriptOptionModule {
  some<Value>(value: Value): Option<Value>;
  none<Value = never>(): Option<Value>;
  isSome<Value>(
    option: Option<Value>,
  ): option is { readonly _tag: "Some"; readonly value: Value };
  isNone<Value>(option: Option<Value>): option is { readonly _tag: "None" };
  readonly [key: string]: any;
}

interface ScriptOpaqueModule {
  readonly [key: string]: any;
}

interface ScriptEffectStd {
  readonly Effect: ScriptEffectModule;
  readonly Option: ScriptOptionModule;
  readonly Duration: ScriptOpaqueModule;
  readonly pipe: ScriptPipe;
}

declare module "effect" {
  const effect: ScriptEffectStd;
  export = effect;
}

declare module "vexed" {
  const vexed: ScriptVexedStd;
  export = vexed;
}

type DurationInput = number | string | bigint | DurationLike;

interface DurationLike {
  readonly _tag?: string;
}

type Option<Value> =
  | { readonly _tag: "Some"; readonly value: Value }
  | { readonly _tag: "None" };

type EffectYieldable<
  Value = unknown,
  Error = unknown,
  Requirements = never,
  Next = never,
> = unknown;

interface Effect<
  Value = unknown,
  Error = unknown,
  Requirements = never,
> {
  [Symbol.iterator](): Generator<EffectYieldable<Value, Error>, Value, any>;
}

interface ScriptExecutionError extends Error {
  readonly _tag: "ScriptExecutionError";
  readonly sourceName: string;
}

interface ScriptNotReadyError extends Error {
  readonly _tag: "ScriptNotReadyError";
  readonly sourceName: string;
}

interface BridgeError extends Error {}

interface ArmyError extends Error {}

type ItemIdentifierToken = number | string;
type MonsterName =
  | string
  | `id'${number}`
  | `id.${number}`
  | `id:${number}`
  | `id-${number}`;
type MonsterMapID = number;
type MonsterIdentifierToken = MonsterName | MonsterMapID;
type Skill = number | string;

type ScriptMain = () => Generator<EffectYieldable<unknown, unknown>, unknown, any>;

interface ScriptContext {
    readonly api: ScriptApi;
    readonly script: ScriptRuntimeApi;
    readonly features: ScriptFeaturesApi;
}
interface ScriptVexedStd {
    readonly api: ScriptApi;
    readonly script: ScriptRuntimeApi;
    readonly features: ScriptFeaturesApi;
}
interface ScriptApi {
    readonly army: ArmyApi;
    readonly auth: AuthApi;
    readonly bank: BankApi;
    readonly combat: CombatApi;
    readonly drops: DropsApi;
    readonly environment: EnvironmentApi;
    readonly events: ScriptEventsApi;
    readonly house: HouseApi;
    readonly inventory: InventoryApi;
    readonly outfits: OutfitsApi;
    readonly packet: ScriptPacketApi;
    readonly player: PlayerApi;
    readonly quests: QuestsApi;
    readonly recipes: RecipesApi;
    readonly settings: SettingsApi;
    readonly shops: ShopsApi;
    readonly tempInventory: TempInventoryApi;
    readonly wait: WaitApi;
    readonly world: WorldApi;
}
interface ScriptRuntimeApi {
  /** Current script cancellation signal; aborted when the script stops. */
    readonly signal: AbortSignal;
    readonly options: ScriptRuntimeOptionsApi;
    log(message: string): void;
  /** Stops the current script. */
    stop(reason?: string): Effect<never, never>;
  /** Waits for milliseconds and cancels when the script stops. Prefer this over homemade `setTimeout` helpers to avoid background timers that keep running after the script is stopped. */
    sleep(ms: number): Effect<void, ScriptExecutionError>;
  /** Intentionally exits the current script, optionally logging out and closing the owning game window during teardown. */
    exit(options?: ScriptExitOptions): Effect<never, ScriptExecutionError | BridgeError>;
}
interface ArmyApi {
    start(configName: string): Effect<ArmySession, never | ArmyError | BridgeError>;
    leave(): Effect<void, never | ArmyError | BridgeError>;
    isStarted(): Effect<boolean, never | ArmyError | BridgeError>;
    isLeader(): Effect<boolean, never | ArmyError | BridgeError>;
    isMember(): Effect<boolean, never | ArmyError | BridgeError>;
    getSession(): Effect<ArmySession | null, never | ArmyError | BridgeError>;
  /** Reads a value from the active army config.

Dot-separated keys read nested object values. An empty key returns the raw
config object. Returns `defaultValue` when the army is not started (a.k.a. no config loaded), the key
is missing, or a nested path cannot be resolved. */
    getConfigValue(key: string, defaultValue?: unknown): Effect<unknown, never | ArmyError | BridgeError>;
  /** Reads a string value from the active army config.

Uses the same key resolution rules as `getConfigValue`, but returns
`defaultValue` when the resolved value is missing or not a string. */
    getConfigString(key: string, defaultValue?: string): Effect<string, never | ArmyError | BridgeError>;
  /** The player's number in the army, starting at 1 for the leader and incrementing
for each member. */
    getPlayerNumber(): Effect<number, never | ArmyError | BridgeError>;
    sync(label?: string, options?: ArmyRunStepOptions): Effect<void, never | ArmyError | BridgeError>;
    runStep<A, E>(label: string, action: Effect<A, E, never>, options?: ArmyRunStepOptions): Effect<A, E | ArmyError | BridgeError>;
    executeWithArmy<A, E>(action: Effect<A, E, never>): Effect<A, E | ArmyError | BridgeError>;
    waitForAllInMap(): Effect<void, never | ArmyError | BridgeError>;
    joinMap(map: string, cell?: string, pad?: string): Effect<void, never | ArmyError | BridgeError>;
    kill(target: MonsterIdentifierToken, options?: CombatKillOptions): Effect<void, never | ArmyError | BridgeError>;
    killForItem(target: MonsterIdentifierToken, item: ItemIdentifierToken, quantity?: number, options?: CombatKillOptions): Effect<void, never | ArmyError | BridgeError>;
    killForTempItem(target: MonsterIdentifierToken, item: ItemIdentifierToken, quantity?: number, options?: CombatKillOptions): Effect<void, never | ArmyError | BridgeError>;
    equipSet(setName: string, options?: ArmyEquipSetOptions): Effect<void, never | ArmyError | BridgeError>;
    startLoopTaunt(options: ArmyLoopTauntOptions): Effect<ArmyLoopTauntHandle, never | ArmyError | BridgeError>;
    stopLoopTaunt(id: string): Effect<boolean, never | ArmyError | BridgeError>;
    stopAllLoopTaunts(): Effect<void, never | ArmyError | BridgeError>;
}
interface AuthApi {
    connectTo(server: string): Effect<AuthConnectOutcome, BridgeError>;
    getServers(): Effect<Server[], BridgeError>;
    getUsername(): Effect<string, BridgeError>;
    getPassword(): Effect<string, BridgeError>;
    isLoggedIn(): Effect<boolean, BridgeError>;
    isTemporarilyKicked(): Effect<boolean, BridgeError>;
    login(username: string, password: string): Effect<void, BridgeError>;
    logout(): Effect<void, BridgeError>;
}
interface BankApi {
    contains(item: ItemIdentifierToken, quantity?: number): Effect<boolean, BridgeError>;
    deposit(item: ItemIdentifierToken): Effect<boolean, BridgeError>;
    depositMany(...items: ItemIdentifierToken[]): Effect<void, BridgeError>;
    getItem(item: ItemIdentifierToken): Effect<Item | null, BridgeError>;
    getItems(): Effect<readonly Item[], BridgeError>;
    getSlots(): Effect<number, BridgeError>;
    getUsedSlots(): Effect<number, BridgeError>;
    getAvailableSlots(): Effect<number, BridgeError>;
    isOpen(): Effect<boolean, BridgeError>;
    open(force?: boolean): Effect<void, BridgeError>;
    swap(invKey: ItemIdentifierToken, bankKey: ItemIdentifierToken): Effect<boolean, BridgeError>;
    withdraw(key: ItemIdentifierToken): Effect<boolean, BridgeError>;
    withdrawMany(...items: ItemIdentifierToken[]): Effect<void, BridgeError>;
}
interface CombatApi {
    attackMonster(monster: MonsterIdentifierToken): Effect<boolean, BridgeError>;
    cancelAutoAttack(): Effect<void, BridgeError>;
    cancelTarget(): Effect<void, BridgeError>;
    canUseSkill(index: string | number): Effect<boolean, BridgeError>;
    exit(): Effect<boolean, BridgeError>;
    getConsumableSkillItem(): Effect<ConsumableSkillItem | null, BridgeError>;
    getTarget(): Effect<Monster | Avatar | null, BridgeError>;
    hasTarget(): Effect<boolean, BridgeError>;
    kill(target: MonsterIdentifierToken, options?: CombatKillOptions): Effect<void, BridgeError>;
    killForItem(target: MonsterIdentifierToken, item: ItemIdentifierToken, quantity?: number, options?: CombatKillOptions): Effect<void, BridgeError>;
    killForTempItem(target: MonsterIdentifierToken, item: ItemIdentifierToken, quantity?: number, options?: CombatKillOptions): Effect<void, BridgeError>;
    useSkill(index: string | number, force?: boolean, wait?: boolean): Effect<void, BridgeError>;
    hunt(target: MonsterIdentifierToken, findMost?: boolean): Effect<string, BridgeError>;
}
interface DropsApi {
    acceptDrop(item: ItemIdentifierToken): Effect<void, BridgeError>;
    containsDrop(item: ItemIdentifierToken): Effect<boolean, BridgeError>;
    getDrops(): Effect<readonly ItemData[], never>;
    isUsingCustomDrops(): Effect<boolean, BridgeError>;
    rejectDrop(itemId: number, visual?: boolean): Effect<boolean, BridgeError>;
    toggleUi(): Effect<void, BridgeError>;
}
interface EnvironmentApi {
    getState(): Effect<EnvironmentState, unknown>;
    clear(): Effect<EnvironmentState, unknown>;
    addQuest(questId: string | number, rewardItemId?: string | number): Effect<EnvironmentState, unknown>;
    removeQuest(questId: string | number): Effect<EnvironmentState, unknown>;
    setQuestReward(questId: string | number, rewardItemId: string | number): Effect<EnvironmentState, unknown>;
    clearQuestReward(questId: string | number): Effect<EnvironmentState, unknown>;
    clearQuests(): Effect<EnvironmentState, unknown>;
  /** Enable or disable auto registration of quest requirements in the drop list. */
    setAutoRegisterRequirements(enabled: boolean): Effect<EnvironmentState, unknown>;
  /** Enable or disable auto registration of quest rewards in the drop list. */
    setAutoRegisterRewards(enabled: boolean): Effect<EnvironmentState, unknown>;
    addItem(name: string): Effect<EnvironmentState, unknown>;
    removeItem(name: string): Effect<EnvironmentState, unknown>;
  /** Accept or ignore member-only AC-tagged items. */
    setAcceptAcMemberOnlyDrops(enabled: boolean): Effect<EnvironmentState, unknown>;
  /** Accept or ignore non-member AC-tagged items. */
    setAcceptAcNonMemberDrops(enabled: boolean): Effect<EnvironmentState, unknown>;
  /** Accept or ignore member-only non-AC items. */
    setAcceptNonAcMemberOnlyDrops(enabled: boolean): Effect<EnvironmentState, unknown>;
  /** Accept or ignore non-member non-AC items. */
    setAcceptNonAcNonMemberDrops(enabled: boolean): Effect<EnvironmentState, unknown>;
  /** Reject or ignore unregistered drops that are not accepted by policy. */
    setRejectUnregisteredDrops(enabled: boolean): Effect<EnvironmentState, unknown>;
  /** Update one or more drop handling options. */
    setDropPolicy(policy: Partial<EnvironmentDropPolicy>): Effect<EnvironmentState, unknown>;
    clearItems(): Effect<EnvironmentState, unknown>;
    addBoost(name: string): Effect<EnvironmentState, unknown>;
    removeBoost(name: string): Effect<EnvironmentState, unknown>;
    clearBoosts(): Effect<EnvironmentState, unknown>;
    fetchBoosts(): Effect<readonly string[], unknown>;
    syncToAll(): Effect<EnvironmentState, unknown>;
}
interface HouseApi {
    getItem(item: ItemIdentifierToken): Effect<Item | null, BridgeError>;
    getItems(): Effect<readonly Item[], BridgeError>;
    getSlots(): Effect<number, BridgeError>;
    getUsedSlots(): Effect<number, BridgeError>;
    getAvailableSlots(): Effect<number, BridgeError>;
}
interface InventoryApi {
    contains(item: ItemIdentifierToken, quantity?: number): Effect<boolean, BridgeError>;
    equip(item: ItemIdentifierToken): Effect<boolean, BridgeError>;
    getItem(item: ItemIdentifierToken): Effect<Item | null, BridgeError>;
    getItems(): Effect<readonly Item[], BridgeError>;
    getSlots(): Effect<number, BridgeError>;
    getUsedSlots(): Effect<number, BridgeError>;
    getAvailableSlots(): Effect<number, BridgeError>;
}
interface OutfitsApi {
    getAll(): Effect<readonly Outfit[], BridgeError>;
    get(name: string): Effect<Outfit | null, BridgeError>;
    equip(name: string, options?: OutfitEquipOptions): Effect<boolean, BridgeError>;
    wear(name: string, options?: OutfitEquipOptions): Effect<boolean, BridgeError>;
}
interface PlayerApi {
    getCell(): Effect<string, BridgeError>;
  /** Uppercased class name. */
    getClassName(): Effect<string, BridgeError>;
    getFactions(): Effect<Collection<string, Faction>, BridgeError>;
    getGender(): Effect<string, BridgeError>;
    getGold(): Effect<number, BridgeError>;
    getHp(): Effect<number, BridgeError>;
    getLevel(): Effect<number, BridgeError>;
    getMaxHp(): Effect<number, BridgeError>;
    getMaxMp(): Effect<number, BridgeError>;
    getMp(): Effect<number, BridgeError>;
    getPad(): Effect<string, BridgeError>;
    getPosition(): Effect<[number, number], BridgeError>;
    getState(): Effect<number, BridgeError>;
    isAfk(): Effect<boolean, BridgeError>;
    isReady(): Effect<boolean, BridgeError>;
    isMember(): Effect<boolean, BridgeError>;
    jumpToCell(cell: string, pad?: string, correction?: boolean): Effect<void, BridgeError>;
    joinMap(map: string, cell?: string, pad?: string): Effect<void, BridgeError>;
    goToPlayer(name: string): Effect<void, BridgeError>;
    rest(full?: boolean): Effect<void, BridgeError>;
    useBoost(boost: ItemIdentifierToken): Effect<boolean, BridgeError>;
    hasActiveBoost(boostType: 'classPoints' | 'exp' | 'gold' | 'rep'): Effect<boolean, BridgeError>;
    isAlive(): Effect<boolean, BridgeError>;
    walkTo(x: number, y: number, walkSpeed?: number): Effect<boolean, BridgeError>;
}
interface QuestsApi {
    abandon(questId: number): Effect<void, BridgeError>;
    accept(questId: number, silent?: boolean): Effect<void, BridgeError>;
    canComplete(questId: number): Effect<boolean, BridgeError>;
    complete(questId: number, turnIns?: number, itemId?: number, special?: boolean): Effect<void, BridgeError>;
    getMaxTurnIns(questId: number): Effect<number, BridgeError>;
    load(questId: number, silent?: boolean): Effect<void, BridgeError>;
    loadMany(questIds: number[], silent?: boolean): Effect<void, BridgeError>;
    getTree(): Effect<Collection<number, Quest>, never>;
    has(questId: number): Effect<boolean, never>;
    getAccepted(): Effect<Quest[], BridgeError>;
    isAvailable(questId: number): Effect<boolean, BridgeError>;
    isInProgress(questId: number): Effect<boolean, BridgeError>;
}
interface RecipesApi {
    buff(skillList?: readonly number[] | null, wait?: boolean): Effect<void, unknown>;
    ensureLifeSteal(quantity: number): Effect<void, unknown>;
    ensureScrollOfEnrage(quantity: number): Effect<void, unknown>;
    useConsumables(items: string | readonly string[], equipAfter?: string): Effect<void, unknown>;
    goToHouse(player?: string): Effect<void, unknown>;
    beep(times?: number): Effect<void, unknown>;
    doWheelOfDoom(toBank?: boolean): Effect<void, unknown>;
    waitForPlayerCount(count: number, exact?: boolean): Effect<void, unknown>;
    equipItemByEnhancement(options: EquipEnhancementSelector): Effect<void, unknown>;
    enhanceItem(item: string, options: ScriptEnhanceItemOptions): Effect<void, unknown>;
}
interface ScriptEventsApi {
  /** Subscribes to an event. */
    on<E extends ScriptEventName>(eventName: E, handler: ScriptEventListener<E>): Effect<ScriptEventDisposer, ScriptExecutionError | ScriptNotReadyError>;
  /** Subscribes once, then disposes the listener. */
    once<E extends ScriptEventName>(eventName: E, handler: ScriptEventListener<E>): Effect<ScriptEventDisposer, ScriptExecutionError | ScriptNotReadyError>;
  /** Waits for the next matching game event. Packet events are not supported. */
    waitFor<E extends ScriptSemanticEventName>(eventName: E, options?: ScriptEventWaitOptions<E>): Effect<Option<ScriptEventMap[E]>, ScriptNotReadyError | unknown>;
}
interface ScriptFeaturesAntiCounterApi {
    isEnabled(): Effect<boolean, never>;
    setEnabled(enabled: boolean): Effect<void, never>;
    enable(): Effect<void, never>;
    disable(): Effect<void, never>;
}
interface ScriptFeaturesApi {
    readonly autoRelogin: ScriptFeaturesAutoReloginApi;
    readonly autoZone: ScriptFeaturesAutoZoneApi;
    readonly antiCounter: ScriptFeaturesAntiCounterApi;
}
interface ScriptFeaturesAutoReloginApi {
    isEnabled(): Effect<boolean, never>;
    enable(): Effect<void, never>;
    disable(): Effect<void, never>;
    getDelay(): Effect<number, never>;
    setDelay(delayMs: number): Effect<void, never>;
    getServer(): Effect<string | undefined, never>;
    setServer(serverName: string): Effect<void, never>;
}
interface ScriptFeaturesAutoZoneApi {
    isEnabled(): Effect<boolean, never>;
    getMap(): Effect<AutoZoneSupportedMap | undefined, never>;
    enable(): Effect<void, never>;
    disable(): Effect<void, never>;
    setMap(map: 'ledgermayne' | 'moreskulls' | 'ultradage' | 'darkcarnax' | 'astralshrine' | 'queeniona' | 'magnumopus' | undefined): Effect<void, never>;
}
interface ScriptPacketApi {
    sendClient(packet: string, type?: ClientPacketSendType): Effect<void, BridgeError>;
    sendServer(packet: string, type?: ServerPacketSendType): Effect<void, BridgeError>;
}
interface ScriptRuntimeOptionsApi {
    getUsePrivateRooms(): Effect<boolean, never>;
    setUsePrivateRooms(enabled: boolean): Effect<void, ScriptExecutionError>;
    getAll(): Effect<Readonly<ScriptOptions>, never>;
    reset(): Effect<void, never>;
}
interface SettingsApi {
    setEnemyMagnet(enabled: boolean): Effect<void, BridgeError>;
    setInfiniteRange(enabled: boolean): Effect<void, BridgeError>;
    setProvokeCell(enabled: boolean): Effect<void, BridgeError>;
    setSkipCutscenes(enabled: boolean): Effect<void, BridgeError>;
    setCustomName(name: string): Effect<void, BridgeError>;
    setCustomGuild(name: string): Effect<void, BridgeError>;
    setWalkSpeed(speed: number): Effect<void, BridgeError>;
    setDeathAdsVisible(visible: boolean): Effect<void, BridgeError>;
    setCollisionsEnabled(enabled: boolean): Effect<void, BridgeError>;
    setEffectsEnabled(enabled: boolean): Effect<void, BridgeError>;
    setOtherPlayersVisible(visible: boolean): Effect<void, BridgeError>;
    setLagKillerEnabled(enabled: boolean): Effect<void, BridgeError>;
    setFrameRate(fps: number): Effect<void, BridgeError>;
}
interface ShopsApi {
    buyById(id: number, quantity?: number): Effect<boolean, BridgeError>;
    buyByName(name: string, quantity?: number): Effect<boolean, BridgeError>;
    canBuyItem(key: ItemIdentifierToken, quantity?: number): Effect<boolean, BridgeError>;
    close(shopId?: number): Effect<boolean, BridgeError>;
    getInfo(): Effect<ShopInfo | null, BridgeError>;
    getItem(key: ItemIdentifierToken): Effect<ShopItem | null, BridgeError>;
    getItems(): Effect<readonly ShopItem[], BridgeError>;
    getMaxBuyQuantity(key: ItemIdentifierToken): Effect<number, BridgeError>;
    isOpen(shopId?: number): Effect<boolean, BridgeError>;
    isMergeShop(): Effect<boolean, BridgeError>;
    load(shopId: number): Effect<void, BridgeError>;
    loadArmorCustomize(): Effect<void, BridgeError>;
    loadHairShop(shopId: number): Effect<void, BridgeError>;
    sellById(id: number, quantity?: number): Effect<boolean, BridgeError>;
    sellByName(name: string, quantity?: number): Effect<boolean, BridgeError>;
}
interface TempInventoryApi {
    contains(item: ItemIdentifierToken, quantity?: number): Effect<boolean, BridgeError>;
    getItem(item: ItemIdentifierToken): Effect<Item | null, BridgeError>;
    getItems(): Effect<readonly Item[], BridgeError>;
}
interface WaitApi {
  /** Waits until a predicate returns true, or returns false when the optional timeout expires.

```js
const loaded = yield* api.wait.until(
  function* () {
    const map = yield* api.world.map.getName();
    return map === "battleon";
  },
  { timeout: "10 seconds", interval: "250 millis" },
);

if (!loaded) {
  script.log("Battleon did not load in time.");
}
``` */
    until(predicate: ScriptWaitPredicate, options?: ScriptWaitOptions): Effect<boolean, unknown>;
    isGameActionAvailable(gameAction: 'acceptQuest' | 'addLoadout' | 'buyItem' | 'doIA' | 'equipLoadout' | 'equipItem' | 'getMapItem' | 'loadEnhShop' | 'loadHairShop' | 'loadShop' | 'removeLoadout' | 'rest' | 'sellItem' | 'tfer' | 'tryQuestComplete' | 'unequipItem' | 'wearLoadout' | 'who'): Effect<boolean, BridgeError>;
    forGameAction(gameAction: 'acceptQuest' | 'addLoadout' | 'buyItem' | 'doIA' | 'equipLoadout' | 'equipItem' | 'getMapItem' | 'loadEnhShop' | 'loadHairShop' | 'loadShop' | 'removeLoadout' | 'rest' | 'sellItem' | 'tfer' | 'tryQuestComplete' | 'unequipItem' | 'wearLoadout' | 'who', options?: ScriptWaitOptions | DurationInput): Effect<boolean, BridgeError>;
    forPlayerReady(options?: ScriptWaitOptions): Effect<boolean, BridgeError>;
    forPlayerPosition(x: number, y: number, options?: ScriptWaitOptions): Effect<boolean, BridgeError>;
    forCombatExit(options?: ScriptWaitOptions): Effect<boolean, unknown>;
    forFullyRested(options?: ScriptWaitOptions): Effect<boolean, BridgeError>;
    forMapLoaded(map?: string, options?: ScriptWaitOptions): Effect<boolean, BridgeError>;
    forLocation(location: { readonly cell?: string; readonly pad?: string; }, options?: ScriptWaitOptions): Effect<boolean, BridgeError>;
    forPlayerCount(count: number, options?: ScriptPlayerCountWaitOptions): Effect<boolean, unknown>;
    forMonsterSpawn(monster: MonsterIdentifierToken, options?: ScriptMonsterWaitOptions): Effect<boolean, unknown>;
    forMonsterAvailable(monster: MonsterIdentifierToken, options?: ScriptMonsterWaitOptions): Effect<boolean, BridgeError>;
    forMonsterDeath(monster: MonsterIdentifierToken, options?: ScriptMonsterWaitOptions): Effect<boolean, unknown>;
    forDrop(item: ItemIdentifierToken, options?: ScriptWaitOptions): Effect<boolean, BridgeError>;
    forDropRemoved(item: ItemIdentifierToken, options?: ScriptWaitOptions): Effect<boolean, BridgeError>;
    forInventoryItem(item: ItemIdentifierToken, options?: ScriptItemWaitOptions): Effect<boolean, BridgeError>;
    forInventoryItemRemoved(item: ItemIdentifierToken, options?: ScriptItemWaitOptions): Effect<boolean, BridgeError>;
    forItemEquipped(item: ItemIdentifierToken, options?: ScriptWaitOptions): Effect<boolean, BridgeError>;
    forBankOpen(options?: ScriptWaitOptions): Effect<boolean, BridgeError>;
    forBankItem(item: ItemIdentifierToken, options?: ScriptItemWaitOptions): Effect<boolean, BridgeError>;
    forBankItemRemoved(item: ItemIdentifierToken, options?: ScriptItemWaitOptions): Effect<boolean, BridgeError>;
    forHouseItem(item: ItemIdentifierToken, options?: ScriptWaitOptions): Effect<boolean, BridgeError>;
    forQuestLoaded(questId: number, options?: ScriptWaitOptions): Effect<boolean, unknown>;
    forQuestAccepted(questId: number, options?: ScriptWaitOptions): Effect<boolean, BridgeError>;
    forQuestCompleted(questId: number, options?: ScriptWaitOptions): Effect<boolean, BridgeError>;
    forSkillReady(index: string | number, options?: ScriptWaitOptions): Effect<boolean, BridgeError>;
}
interface WorldApi {
    readonly map: WorldMapApi;
    readonly players: WorldPlayersApi;
    readonly monsters: WorldMonstersApi;
}
interface WorldMapApi {
    getCellMonsters(): Effect<Monster[], BridgeError>;
    getCells(): Effect<string[], BridgeError>;
    getCellPads(): Effect<string[], BridgeError>;
    isLoaded(): Effect<boolean, BridgeError>;
    getMapItem(itemId: number): Effect<void, BridgeError>;
    loadSwf(path: string): Effect<void, BridgeError>;
    reload(): Effect<void, BridgeError>;
    setSpawnPoint(cell?: string, pad?: string): Effect<void, BridgeError>;
    getName(): Effect<string, never>;
    getId(): Effect<number, never>;
    getRoomNumber(): Effect<number, never>;
}
interface WorldMonstersApi {
    getAll(): Effect<Collection<number, Monster>, never>;
    get(monMapId: number): Effect<Option<Monster>, never>;
    findByName(name: string, cell?: string): Effect<Option<Monster>, never>;
    getAura(monMapId: number, auraName: string): Effect<Option<Aura>, never>;
}
interface WorldPlayersApi {
    readonly me: WorldPlayersMeApi;
    getAll(): Effect<Collection<string, Avatar>, never>;
    get(username: string): Effect<Option<Avatar>, never>;
    getByName(name: string): Effect<Option<Avatar>, never>;
    getAuras(username: string): Effect<readonly Aura[], never>;
    getAura(username: string, auraName: string): Effect<Option<Aura>, never>;
}
interface WorldPlayersMeApi {
    get(): Effect<Option<Avatar>, never>;
    getAuras(): Effect<readonly Aura[], never>;
    getAura(auraName: string): Effect<Option<Aura>, never>;
}

interface ArmyEquipSetOptions {
  /**
   * When true, items will be resolved under the `items` key of the army config.
   */
  readonly resolveItems?: boolean;
}
interface ArmyLoopTauntHandle {
  readonly id: string;
  stop(): ArmyEffect<boolean>;
}
type ArmyLoopTauntOptions =
  | (ArmyLoopTauntBaseOptions & {
      readonly aura: string;
      readonly delayMs?: number;
      readonly debounceMs?: never;
      readonly message?: never;
    })
  | (ArmyLoopTauntBaseOptions & {
      readonly aura?: never;
      readonly debounceMs?: number;
      readonly delayMs?: never;
      readonly message: string;
    });
interface ArmyRunStepOptions {
  readonly timeoutMs?: number;
}
type ArmySession = ArmySessionPayload;
type Aura = {
  cat?: string;
  duration?: number;
  icon?: string;
  isNew?: boolean;
  name: string;
  /**
   * Number of active instances tracked for this aura name.
   */
  stack?: number;
  /**
   * The aura's value, if applicable.
   * Can be an integer or float.
   */
  value?: number;
};
type AuthConnectOutcome =
  | {
      readonly status: "connected";
      readonly message: string;
      readonly retryable: false;
      readonly serverName?: string;
    }
  | {
      readonly status: AuthConnectFailureStatus;
      readonly message: string;
      readonly retryable: boolean;
      readonly serverName?: string;
    };
type AutoZoneSupportedMap = 'ledgermayne' | 'moreskulls' | 'ultradage' | 'darkcarnax' | 'astralshrine' | 'queeniona' | 'magnumopus';
interface Avatar extends BaseEntity {
  readonly data: AvatarData;
  readonly pad: string;
  readonly mp: number;
  readonly maxMp: number;
  readonly mpPercentage: number;
  readonly level: number;
  readonly username: string;
  isAFK(): boolean;
  readonly position: [number, number];
}
type ClientPacketSendType = "str" | "json" | "xml";
interface Collection<Key, Value> extends Map<Key, Value> {
  ensure(key: Key, defaultValueGenerator: (key: Key, collection: this) => Value): Value;
  hasAll(...keys: Key[]): boolean;
  hasAny(...keys: Key[]): boolean;
  first(): Value | undefined;
  first(amount: number): Value[];
  firstKey(): Key | undefined;
  firstKey(amount: number): Key[];
  last(): Value | undefined;
  last(amount: number): Value[];
  lastKey(): Key | undefined;
  lastKey(amount: number): Key[];
  at(index: number): Value | undefined;
  keyAt(index: number): Key | undefined;
  random(): Value | undefined;
  random(amount: number): Value[];
  randomKey(): Key | undefined;
  randomKey(amount: number): Key[];
  reverse(): this;
  find<NewValue extends Value>(fn: (value: Value, key: Key, collection: this) => value is NewValue): NewValue | undefined;
  find(fn: (value: Value, key: Key, collection: this) => unknown): Value | undefined;
  find<This, NewValue extends Value>(fn: (this: This, value: Value, key: Key, collection: this) => value is NewValue, thisArg: This): NewValue | undefined;
  find<This>(fn: (this: This, value: Value, key: Key, collection: this) => unknown, thisArg: This): Value | undefined;
  findKey<NewKey extends Key>(fn: (value: Value, key: Key, collection: this) => key is NewKey): NewKey | undefined;
  findKey(fn: (value: Value, key: Key, collection: this) => unknown): Key | undefined;
  findKey<This, NewKey extends Key>(fn: (this: This, value: Value, key: Key, collection: this) => key is NewKey, thisArg: This): NewKey | undefined;
  findKey<This>(fn: (this: This, value: Value, key: Key, collection: this) => unknown, thisArg: This): Key | undefined;
  findLast<NewValue extends Value>(fn: (value: Value, key: Key, collection: this) => value is NewValue): NewValue | undefined;
  findLast(fn: (value: Value, key: Key, collection: this) => unknown): Value | undefined;
  findLast<This, NewValue extends Value>(fn: (this: This, value: Value, key: Key, collection: this) => value is NewValue, thisArg: This): NewValue | undefined;
  findLast<This>(fn: (this: This, value: Value, key: Key, collection: this) => unknown, thisArg: This): Value | undefined;
  findLastKey<NewKey extends Key>(fn: (value: Value, key: Key, collection: this) => key is NewKey): NewKey | undefined;
  findLastKey(fn: (value: Value, key: Key, collection: this) => unknown): Key | undefined;
  findLastKey<This, NewKey extends Key>(fn: (this: This, value: Value, key: Key, collection: this) => key is NewKey, thisArg: This): NewKey | undefined;
  findLastKey<This>(fn: (this: This, value: Value, key: Key, collection: this) => unknown, thisArg: This): Key | undefined;
  sweep(fn: (value: Value, key: Key, collection: this) => unknown): number;
  sweep<This>(fn: (this: This, value: Value, key: Key, collection: this) => unknown, thisArg: This): number;
  filter<NewKey extends Key>(fn: (value: Value, key: Key, collection: this) => key is NewKey): Collection<NewKey, Value>;
  filter<NewValue extends Value>(fn: (value: Value, key: Key, collection: this) => value is NewValue): Collection<Key, NewValue>;
  filter(fn: (value: Value, key: Key, collection: this) => unknown): Collection<Key, Value>;
  filter<This, NewKey extends Key>(fn: (this: This, value: Value, key: Key, collection: this) => key is NewKey, thisArg: This): Collection<NewKey, Value>;
  filter<This, NewValue extends Value>(fn: (this: This, value: Value, key: Key, collection: this) => value is NewValue, thisArg: This): Collection<Key, NewValue>;
  filter<This>(fn: (this: This, value: Value, key: Key, collection: this) => unknown, thisArg: This): Collection<Key, Value>;
  partition<NewKey extends Key>(fn: (value: Value, key: Key, collection: this) => key is NewKey): [Collection<NewKey, Value>, Collection<Exclude<Key, NewKey>, Value>];
  partition<NewValue extends Value>(fn: (value: Value, key: Key, collection: this) => value is NewValue): [Collection<Key, NewValue>, Collection<Key, Exclude<Value, NewValue>>];
  partition(fn: (value: Value, key: Key, collection: this) => unknown): [Collection<Key, Value>, Collection<Key, Value>];
  partition<This, NewKey extends Key>(fn: (this: This, value: Value, key: Key, collection: this) => key is NewKey, thisArg: This): [Collection<NewKey, Value>, Collection<Exclude<Key, NewKey>, Value>];
  partition<This, NewValue extends Value>(fn: (this: This, value: Value, key: Key, collection: this) => value is NewValue, thisArg: This): [Collection<Key, NewValue>, Collection<Key, Exclude<Value, NewValue>>];
  partition<This>(fn: (this: This, value: Value, key: Key, collection: this) => unknown, thisArg: This): [Collection<Key, Value>, Collection<Key, Value>];
  flatMap<NewValue>(fn: (value: Value, key: Key, collection: this) => Collection<Key, NewValue>): Collection<Key, NewValue>;
  flatMap<NewValue, This>(fn: (this: This, value: Value, key: Key, collection: this) => Collection<Key, NewValue>, thisArg: This): Collection<Key, NewValue>;
  map<NewValue>(fn: (value: Value, key: Key, collection: this) => NewValue): NewValue[];
  map<This, NewValue>(fn: (this: This, value: Value, key: Key, collection: this) => NewValue, thisArg: This): NewValue[];
  mapValues<NewValue>(fn: (value: Value, key: Key, collection: this) => NewValue): Collection<Key, NewValue>;
  mapValues<This, NewValue>(fn: (this: This, value: Value, key: Key, collection: this) => NewValue, thisArg: This): Collection<Key, NewValue>;
  some(fn: (value: Value, key: Key, collection: this) => unknown): boolean;
  some<This>(fn: (this: This, value: Value, key: Key, collection: this) => unknown, thisArg: This): boolean;
  every<NewKey extends Key>(fn: (value: Value, key: Key, collection: this) => key is NewKey): boolean;
  every<NewValue extends Value>(fn: (value: Value, key: Key, collection: this) => value is NewValue): boolean;
  every(fn: (value: Value, key: Key, collection: this) => unknown): boolean;
  every<This, NewKey extends Key>(fn: (this: This, value: Value, key: Key, collection: this) => key is NewKey, thisArg: This): boolean;
  every<This, NewValue extends Value>(fn: (this: This, value: Value, key: Key, collection: this) => value is NewValue, thisArg: This): boolean;
  every<This>(fn: (this: This, value: Value, key: Key, collection: this) => unknown, thisArg: This): boolean;
  reduce(fn: (accumulator: Value, value: Value, key: Key, collection: this) => Value, initialValue?: Value): Value;
  reduce<InitialValue>(fn: (accumulator: InitialValue, value: Value, key: Key, collection: this) => InitialValue, initialValue: InitialValue): InitialValue;
  reduceRight(fn: (accumulator: Value, value: Value, key: Key, collection: this) => Value, initialValue?: Value): Value;
  reduceRight<InitialValue>(fn: (accumulator: InitialValue, value: Value, key: Key, collection: this) => InitialValue, initialValue: InitialValue): InitialValue;
  each(fn: (value: Value, key: Key, collection: this) => void): this;
  each<This>(fn: (this: This, value: Value, key: Key, collection: this) => void, thisArg: This): this;
  tap(fn: (collection: this) => void): this;
  tap<This>(fn: (this: This, collection: this) => void, thisArg: This): this;
  clone(): Collection<Key, Value>;
  concat(...collections: ReadonlyCollection<Key, Value>[]): Collection<Key, Value>;
  equals(collection: ReadonlyCollection<Key, Value>): boolean;
  sort(compareFunction?: Comparator<Key, Value>): this;
  intersection(other: ReadonlyCollection<Key, any>): Collection<Key, Value>;
  union<OtherValue>(other: ReadonlyCollection<Key, OtherValue>): Collection<Key, Value | OtherValue>;
  difference(other: ReadonlyCollection<Key, any>): Collection<Key, Value>;
  symmetricDifference<OtherValue>(other: ReadonlyCollection<Key, OtherValue>): Collection<Key, Value | OtherValue>;
  merge<OtherValue, ResultValue>(other: ReadonlyCollection<Key, OtherValue>, whenInSelf: (value: Value, key: Key) => Keep<ResultValue>, whenInOther: (valueOther: OtherValue, key: Key) => Keep<ResultValue>, whenInBoth: (value: Value, valueOther: OtherValue, key: Key) => Keep<ResultValue>): Collection<Key, ResultValue>;
  toReversed(): Collection<Key, Value>;
  toSorted(compareFunction?: Comparator<Key, Value>): Collection<Key, Value>;
  toJSON(): [Key, Value][];
}
interface CombatKillOptions {
  readonly killPriority?: readonly MonsterIdentifierToken[] | string;
  readonly skillSet?: readonly Skill[] | string;
  readonly skillDelay?: number;
  readonly skillWait?: boolean;
}
type ConsumableSkillItem = {
  itemId?: number;
  name?: string;
};
interface EnvironmentDropPolicy {
  /** Accept member-only AC-tagged items. */
  readonly acceptAcMemberOnlyDrops: boolean;
  /** Accept non-member AC-tagged items. */
  readonly acceptAcNonMemberDrops: boolean;
  /** Accept member-only non-AC items. */
  readonly acceptNonAcMemberOnlyDrops: boolean;
  /** Accept non-member non-AC items. */
  readonly acceptNonAcNonMemberDrops: boolean;
  /** Reject any unregistered drop that is not accepted by this policy. */
  readonly rejectUnregisteredDrops: boolean;
}
interface EnvironmentState {
  readonly questIds: readonly number[];
  readonly questAutoRegister: EnvironmentQuestAutoRegisterOptions;
  readonly questRewards: Readonly<Record<number, number>>;
  readonly itemNames: readonly string[];
  readonly itemRules: EnvironmentItemRules;
  readonly boosts: readonly string[];
}
type EquipEnhancementSelector = {
  /**
   * The base enhancement name to match, such as "lucky" or "forge".
   */
  readonly enhancement: string;
  /**
   * The slot of the item, one of "weapon", "cape", "helm", "class".
   */
  readonly slot?: EquipEnhancementSelectorSlot;
  /**
   * Optional special enhancement variant, such as a weapon proc or Forge special ("anima", "vainglory").
   */
  readonly special?: string;
};
interface Faction {
  data: FactionData;
  readonly id: number;
  readonly name: string;
  readonly rank: number;
  readonly totalRep: number;
  readonly rep: number;
  readonly requiredRep: number;
  readonly remainingRep: number;
}
interface Item {
  data: ItemData;
  readonly id: number;
  readonly name: string;
  readonly description: string;
  readonly quantity: number;
  readonly maxStack: number;
  isUpgrade(): boolean;
  isAC(): boolean;
  readonly category: string;
  isTemp(): boolean;
  readonly itemGroup: string;
  isArmor(): boolean;
  isClass(): boolean;
  isCape(): boolean;
  isHelm(): boolean;
  isPet(): boolean;
  isWeapon(): boolean;
  readonly fileName: string;
  readonly fileLink: string;
  readonly meta: Record<string, number> | null;
  readonly classRank: number | null;
  isMaxed(): boolean;
  isMember(): boolean;
  readonly charItemId: number;
  isEquipped(): boolean;
  isWearing(): boolean;
  readonly level: number;
  readonly enhancementLevel: number;
  readonly enhancementPatternId: number;
  isBoost(): boolean;
}
type ItemData = {
  CharID: number;
  CharItemID: number;
  EnhDPS: number;
  EnhID: number;
  EnhLvl: number;
  EnhPatternID: number;
  PatternID?: number | string;
  EnhRng: number;
  EnhRty: number;
  ItemID: number;
  ProcID?: number;
  bBank: number;
  bHouse: number;
  bCoins: number;
  bEquip: number;
  bStaff: number;
  bTemp: number;
  bUpg: number;
  bWear: number;
  dPurchase: string;
  iCost: number;
  iDPS: number;
  iHrs: number;
  iLvl: number;
  iQty: number;
  iRng: number;
  iRty: number;
  iStk: number;
  iType: number;
  sDesc: string;
  sES: string;
  sElmt: string;
  sFile: string;
  sIcon: string;
  sLink: string;
  sMeta: string;
  sName: string;
  sType: string;
};
interface Monster extends BaseEntity {
  readonly data: MonsterData;
  readonly monMapId: number;
  readonly id: number;
  readonly level: number;
  readonly race: string;
  readonly name: string;
}
interface Outfit {
  readonly name: string;
  readonly data: Record<string, unknown>;
}
interface OutfitEquipOptions {
  readonly keepColors?: boolean;
}
interface Quest {
  data: QuestInfo;
  readonly name: string;
  readonly id: number;
  readonly once: boolean;
  readonly rewards: QuestReward[];
  readonly requirements: QuestRequirement[];
  isDaily(): boolean;
  isWeekly(): boolean;
  isMonthly(): boolean;
}
interface ScriptEnhanceItemOptions {
  readonly enhancement: string;
  readonly special?: string;
}
type ScriptEventDisposer = () => void;
type ScriptEventListener<E extends ScriptEventName = ScriptEventName> = (
  event: ScriptEventMap[E],
) =>
  | void
  | Effect<unknown, unknown>
  | Generator<EffectYieldable<any, any, never, never>, unknown, never>;
interface ScriptEventMap {
  packetFromClient: string;
  packetFromServer: string;
  extensionResponse: string;
  monsterDeath: ScriptEventMonsterDeathEvent;
  questComplete: ScriptEventQuestCompleteEvent;
  zone: ScriptEventZoneEvent;
  joinMap: ScriptEventJoinMapEvent;
  animationMessage: ScriptEventAnimationMessageEvent;
  auraAdded: ScriptEventAuraEvent;
  auraRemoved: Omit<ScriptEventAuraEvent, "aura">;
  afk: ScriptEventAfkEvent;
  antiCounterStart: ScriptEventAntiCounterEvent;
  antiCounterEnd: Omit<ScriptEventAntiCounterEvent, "durationMs">;
  playerLocation: ScriptEventPlayerLocationEvent;
}
type ScriptEventName = keyof ScriptEventMap;
interface ScriptEventWaitOptions<E extends ScriptSemanticEventName>
  extends ScriptWaitOptions {
  readonly predicate?: ScriptEventPredicate<E>;
}
interface ScriptExitOptions {
  readonly logout?: boolean;
  readonly closeWindow?: boolean;
}
interface ScriptItemWaitOptions extends ScriptWaitOptions {
  readonly quantity?: number;
}
interface ScriptMonsterWaitOptions extends ScriptWaitOptions {
  readonly cell?: string;
  readonly currentCell?: boolean;
}
interface ScriptOptions {
  readonly usePrivateRooms: boolean;
}
interface ScriptPlayerCountWaitOptions extends ScriptWaitOptions {
  readonly exact?: boolean;
}
type ScriptSemanticEventName = Exclude<
  ScriptEventName,
  ScriptPacketEventName
>;
interface ScriptWaitOptions {
  readonly timeout?: DurationInput;
  readonly interval?: DurationInput;
}
type ScriptWaitPredicate = () =>
  | boolean
  | Effect<boolean, unknown>
  | Generator<EffectYieldable<any, any, never, never>, boolean, never>;
interface Server {
  data: { readonly bOnline: number; readonly bUpg: number; readonly iChat: number; readonly iCount: number; readonly iLevel: number; readonly iMax: number; readonly iPort: number; readonly sIP: string; readonly sLang: string; readonly sName: string; };
  readonly maxPlayers: number;
  readonly port: number;
  readonly langCode: string;
  readonly name: string;
  readonly ip: string;
  readonly playerCount: number;
  isUpgrade(): boolean;
  isCanned(): boolean;
  isOnline(): boolean;
  isFull(): boolean;
}
type ServerPacketSendType = "String" | "Json";
type ShopInfo = {
  Location: string;
  ShopID: string;
  bHouse: string;
  bStaff: string;
  bUpgrd: string;
  iIndex: string;
  items: ShopItemData[];
  sField: string;
  sName: string;
};
interface ShopItem extends Item {
  data: ShopItemData;
}
type ArmyEffect<A, E = never> = Effect<
  A,
  E | ArmyError | BridgeError
>;
interface ArmyLoopTauntBaseOptions {
  readonly id?: string;
  readonly noEligiblePolicy?: ArmyLoopTauntNoEligiblePolicy;
  readonly players?: readonly ArmyLoopTauntPlayer[];
  readonly shouldTaunt?: ArmyLoopTauntShouldTaunt;
  readonly skill: Skill;
  readonly target: MonsterIdentifierToken;
}
interface ArmySessionPayload extends ArmyConfigPayload {
  readonly sessionId: string;
  readonly playerName: string;
  readonly playerNumber: number;
  readonly role: "leader" | "member";
}
type AuthConnectFailureStatus =
  | Exclude<ConnectToSelectionStatus, "selected">
  | "connection-failed"
  | "connection-error"
  | "timeout";
interface BaseEntity {
  readonly data: BaseEntityData;
  readonly hp: number;
  readonly maxHp: number;
  readonly hpPercentage: number;
  readonly state: EntityState;
  readonly alive: boolean;
  isHpLessThan(value: number): boolean;
  isHpGreaterThan(value: number): boolean;
  isHpPercentageLessThan(value: number): boolean;
  isHpPercentageGreaterThan(value: number): boolean;
  isInCombat(): boolean;
  isDead(): boolean;
  isIdle(): boolean;
  isPlayer(): boolean;
  isMonster(): boolean;
  readonly cell: string;
  isInCell(cell: string): boolean;
}
type AvatarData = BaseEntityData & {
  afk: boolean;
  entID: number;
  entType: string;
  intLevel: number;
  intMP: number;
  intMPMax: number;
  strPad: string;
  strUsername: string;
  tx: number;
  ty: number;
  uoName: string;
};
type ReadonlyCollection<Key, Value> = Omit<Collection<Key, Value>, keyof Map<Key, Value> | "ensure" | "reverse" | "sort" | "sweep"> & ReadonlyMap<Key, Value>;
type Comparator<Key, Value> = (firstValue: Value, secondValue: Value, firstKey: Key, secondKey: Key) => number;
type Keep<Value> = {
    keep: false;
} | {
    keep: true;
    value: Value;
};
interface EnvironmentQuestAutoRegisterOptions {
  readonly requirements: boolean;
  readonly rewards: boolean;
}
interface EnvironmentItemRules {
  readonly buckets: readonly EnvironmentItemBucket[];
  readonly rejectElse: boolean;
}
type EquipEnhancementSelectorSlot = EquipItemTypeFilter | "armor";
type FactionData = {
  CharFactionID: string;
  /**
   * The ID of the faction.
   */
  FactionID: string;
  /**
   * The rank that the player has achieved in this faction.
   */
  iRank: number;
  /**
   * The total amount of rep the player has for this faction.
   */
  iRep: number;
  /**
   * The total required rep for the player to rank up.
   */
  iRepToRank: number;
  /**
   * The amount of rep the player has for their current rank.
   */
  iSpillRep: number;
  /**
   * The name of the faction.
   */
  sName: string;
};
interface CharID { readonly [key: string]: unknown; }
interface CharItemID { readonly [key: string]: unknown; }
interface EnhDPS { readonly [key: string]: unknown; }
interface EnhID { readonly [key: string]: unknown; }
interface EnhLvl { readonly [key: string]: unknown; }
interface EnhPatternID { readonly [key: string]: unknown; }
interface PatternID { readonly [key: string]: unknown; }
interface EnhRng { readonly [key: string]: unknown; }
interface EnhRty { readonly [key: string]: unknown; }
interface ItemID { readonly [key: string]: unknown; }
interface ProcID { readonly [key: string]: unknown; }
type MonsterData = BaseEntityData & {
  iLvl: number;
  intMP: number;
  intMPMax: number;
  monId: number;
  monMapId: number;
  sRace: string;
  strFrame: string;
  strMonName: string;
};
type QuestInfo = {
  FactionID: string;
  /**
   * The ID of this quest.
   */
  QuestID: string;
  RequiredItems: QuestRequirementData[];
  Rewards: QuestBonusRewardData[];
  bGuild: string;
  /**
   * Whether this quest can only be completed once.
   */
  bOnce: string;
  bStaff: string;
  bUpg: string;
  bitSuccess: string;
  iClass: number;
  /**
   * The amount of experience rewarded for completing this quest.
   */
  iExp: number;
  /**
   * The amount of gold rewarded for completing this quest.
   */
  iGold: number;
  iIndex?: number;
  /**
   * The required level to accept this quest.
   */
  iLvl: number;
  /**
   * The amount of reputation rewarded for completing this quest. 0 if not applicable.
   */
  iRep: number;
  /**
   * The class points required to accept this quest. 0 if not applicable.
   */
  iReqCP: number;
  /**
   * The required faction reputation to accept this quest.
   */
  iReqRep: number;
  iSlot: number;
  iValue: number;
  iWar: number;
  metaValues: Record<string, string>;
  oItems: Record<string, ItemData>;
  oRewards: Record<string, QuestBonusRewardData>;
  reward: QuestRewardData[];
  /**
   * The description of this quest.
   */
  sDesc: string;
  /**
   * The text displayed when this quest can be completed.
   */
  sEndText: string;
  /**
   * The name of the faction that this quest is for.
   */
  sFaction: string;
  sField?: string;
  /**
   * The name of this quest.
   */
  sName: string;
  /**
   * The status of the quest.
   */
  status: string;
  turnin: QuestTurnInData[];
};
type QuestReward = {
  /**
   * The drop chance of the item with a percent sign.
   */
  dropChance: string;
  /**
   * The item ID.
   */
  itemId: string;
  /**
   * The name of the item.
   */
  itemName: string;
  /**
   * The quantity of the item.
   */
  quantity: number;
};
type QuestRequirement = {
  /**
   * The item ID.
   */
  itemId: string;
  /**
   * The name of the item.
   */
  itemName: string;
  /**
   * The quantity of the item.
   */
  quantity: number;
};
interface ScriptEventMonsterDeathEvent {
  readonly monMapId: number;
}
interface ScriptEventQuestCompleteEvent {
  readonly QuestID: number;
  readonly bSuccess: number;
  readonly sName: string;
  readonly rewardObj: {
    readonly intGold?: number;
    readonly intExp?: number;
    readonly iCP?: number;
    readonly typ?: string;
    readonly intCoins?: number;
  };
}
interface ScriptEventZoneEvent {
  readonly map: string;
  readonly zone: string;
}
interface ScriptEventJoinMapEvent {
  readonly mapName?: string;
  readonly mapId?: number;
  readonly roomNumber?: number;
}
interface ScriptEventAnimationMessageEvent {
  readonly message: string;
  readonly monMapId?: number;
  readonly sourceMonMapId?: number;
  readonly targetMonMapId?: number;
}
interface ScriptEventAuraEvent {
  readonly auraName: string;
  readonly targetId: number;
  readonly targetName?: string;
  readonly targetType: "monster" | "player";
  readonly aura?: Aura;
}
interface ScriptEventAfkEvent {
  readonly username: string;
  readonly afk: boolean;
}
interface ScriptEventAntiCounterEvent {
  readonly monMapId: number;
  readonly source: "message" | "aura";
  readonly triggerId: string;
  readonly triggerText: string;
  readonly durationMs?: number;
}
interface ScriptEventPlayerLocationEvent {
  readonly username: string;
  readonly cell?: string;
  readonly pad?: string;
  readonly x?: number;
  readonly y?: number;
}
type ScriptEventPredicate<E extends ScriptSemanticEventName> = (
  event: ScriptEventMap[E],
) =>
  | boolean
  | Effect<boolean, unknown>
  | Generator<EffectYieldable<any, any, never, never>, boolean, never>;
type ScriptPacketEventName =
  | "packetFromClient"
  | "packetFromServer"
  | "extensionResponse";
interface Json { readonly [key: string]: unknown; }
interface Location { readonly [key: string]: unknown; }
interface ShopID { readonly [key: string]: unknown; }
type ShopItemData = ItemData & {
  /**
   * Faction ID associated with the item.
   */
  FactionID: string;
  /**
   * Proc ID for Forge/Awe weapon enhancements
   */
  ItemProcID?: string;
  /**
   * Shop item id.
   */
  ShopItemID: string;
  /**
   * Enhancement-specific properties
   */
  bEnhShop?: boolean;
  /**
   * Whether the item can be placed in a house.
   */
  bHouse: string;
  iClass: string;
  iQSindex: string;
  iQSvalue: string;
  iQtyRemain: string;
  iReqCP: string;
  iReqRep: string;
  /**
   * Faction associated with the item.
   */
  sFaction: string;
  sQuest?: string;
  /**
   * Items required to merge this item.
   */
  turnin?: {
    ItemID: string;
    iQty: string;
    sName: string;
  }[];
};
type ArmyLoopTauntNoEligiblePolicy = "throw" | "cast-scheduled";
type ArmyLoopTauntPlayer = number | string;
type ArmyLoopTauntShouldTaunt = (
  context: ArmyLoopTauntTurnContext,
) => boolean | Effect<boolean, unknown>;
interface ArmyConfigPayload extends ArmyConfigCore {
  readonly configName: string;
  readonly raw: ArmyConfigRaw;
}
type ConnectToSelectionStatus =
  | "selected"
  | "not-ready"
  | "offline"
  | "full"
  | "member-only"
  | "chat-restricted"
  | "underage-chat"
  | "email-unconfirmed"
  | "test-client-required"
  | "not-found";
type BaseEntityData = {
  intHP: number;
  intHPMax: number;
  intState: number;
  strFrame: string;
};
enum EntityState {
  /**
   * The entity is dead.
   */
  Dead = 0,
  /**
   * The entity is idle.
   */
  Idle = 1,
  /**
   * The entity is in combat.
   */
  InCombat = 2
}
type EnvironmentItemBucket = 'ac-member' | 'ac-non-member' | 'non-ac-member' | 'non-ac-non-member';
type EquipItemTypeFilter = "weapon" | "cape" | "helm" | "class";
interface CharFactionID { readonly [key: string]: unknown; }
interface FactionID { readonly [key: string]: unknown; }
interface QuestID { readonly [key: string]: unknown; }
interface RequiredItems { readonly [key: string]: unknown; }
type QuestRequirementData = {
  /**
   * The item ID.
   */
  ItemID: string;
  /**
   * The quantity of the item.
   */
  iQty: number;
  /**
   * The name of the item.
   */
  sName: string;
};
interface Rewards { readonly [key: string]: unknown; }
type QuestBonusRewardData = {
  /**
   * The drop chance of the item with a percent sign.
   */
  DropChance: string;
  /**
   * The item ID.
   */
  ItemID: string;
  /**
   * The quantity of the item.
   */
  iQty: number;
  /**
   * The name of the item.
   */
  sName: string;
};
type QuestRewardData = {
  /**
   * The item ID.
   */
  ItemID: string;
  /**
   * The quantity of the item.
   */
  iQty: number;
  /**
   * The rate of the reward without a percent sign.
   */
  iRate: string;
  /**
   * The type of the reward.
   */
  iType: string;
};
type QuestTurnInData = {
  /**
   * The item ID.
   */
  ItemID: string;
  /**
   * The quantity of the item.
   */
  iQty: number;
};
interface ItemProcID { readonly [key: string]: unknown; }
interface ShopItemID { readonly [key: string]: unknown; }
interface ArmyLoopTauntTurnContext {
  readonly id: string;
  readonly target: {
    readonly token: MonsterIdentifierToken;
    readonly monMapId: number;
  };
  readonly localPlayer: ResolvedArmyPlayer;
  readonly scheduled: ResolvedArmyPlayer;
  readonly candidate: ResolvedArmyPlayer;
  readonly participants: readonly ResolvedArmyPlayer[];
  readonly turn: {
    readonly index: number;
    readonly triggerCount: number;
  };
  readonly trigger: NormalizedLoopTauntTrigger;
  readonly world: {
    readonly players: Pick<
      WorldPlayersShape,
      "getAll" | "getByName" | "getAuras" | "getAura"
    >;
    readonly monsters: Pick<WorldMonstersShape, "get" | "getAura">;
  };
}
interface ArmyConfigCore {
  readonly leader: string;
  readonly players: readonly string[];
  readonly roomNumber: string;
}
type ArmyConfigRaw = Record<string, unknown>;
interface Dead { readonly [key: string]: unknown; }
interface Idle { readonly [key: string]: unknown; }
interface InCombat { readonly [key: string]: unknown; }
interface DropChance { readonly [key: string]: unknown; }
interface ResolvedArmyPlayer {
  readonly name: string;
  readonly number: number;
}
type NormalizedLoopTauntTrigger =
  | {
      readonly aura: string;
      readonly delayMs: number;
      readonly type: "aura";
    }
  | {
      readonly debounceMs: number;
      readonly message: string;
      readonly type: "message";
    };
interface WorldPlayersShape {
  register(username: string, entId: number): Effect<void>;
  unregister(username: string): Effect<void>;
  add(data: AvatarData): Effect<void>;
  remove(username: string): Effect<void>;
  setSelf(username: string): Effect<void>;
  getAll(): Effect<Collection<string, Avatar>>;
  getSelf(): Effect<Option<Avatar>>;
  withSelf<A>(f: (self: Avatar) => A): Effect<Option<A>>;
  get(username: string): Effect<Option<Avatar>>;
  getByName(name: string): Effect<Option<Avatar>>;
  addAura(entId: number, aura: Aura): Effect<void>;
  updateAura(entId: number, aura: Aura): Effect<void>;
  removeAura(entId: number, auraName: string): Effect<void>;
  getAuras(entId: number): Effect<readonly Aura[]>;
  getAura(entId: number, auraName: string): Effect<Option<Aura>>;
  clearAuras(entId: number): Effect<void>;
}
interface WorldMonstersShape {
  getAll(): Effect<Collection<number, Monster>>;
  add(data: MonsterData): Effect<void>;
  get(monMapId: number): Effect<Option<Monster>>;
  findByName(
    name: string,
    cell?: string,
  ): Effect<Option<Monster>>;
  addAura(monMapId: number, aura: Aura): Effect<void>;
  updateAura(monMapId: number, aura: Aura): Effect<void>;
  removeAura(monMapId: number, auraName: string): Effect<void>;
  getAura(
    monMapId: number,
    auraName: string,
  ): Effect<Option<Aura>>;
  clearAuras(monMapId: number): Effect<void>;
}
