// Generated by pnpm run types:scripting. Do not edit directly.

/* eslint-disable */

type DurationInput = number | string | bigint | DurationLike;

interface DurationLike {
  readonly _tag?: string;
}

type Option<Value> =
  | { readonly _tag: "Some"; readonly value: Value }
  | { readonly _tag: "None" };

type EffectYieldable<
  Value = unknown,
  Error = unknown,
  Requirements = never,
  Next = never,
> = unknown;

interface Effect<
  Value = unknown,
  Error = unknown,
  Requirements = never,
> {
  [Symbol.iterator](): Generator<EffectYieldable<Value, Error>, Value, any>;
}

interface ScriptExecutionError extends Error {
  readonly _tag: "ScriptExecutionError";
  readonly sourceName: string;
}

interface ScriptNotReadyError extends Error {
  readonly _tag: "ScriptNotReadyError";
  readonly sourceName: string;
}

interface BridgeError extends Error {}

interface ArmyError extends Error {}

type ItemIdentifierToken = number | string;
type MonsterName =
  | string
  | `id'${number}`
  | `id.${number}`
  | `id:${number}`
  | `id-${number}`;
type MonsterMapID = number;
type MonsterIdentifierToken = MonsterName | MonsterMapID;
type Skill = number | string;

type ScriptMain = (
  context: ScriptContext,
) => Generator<EffectYieldable<unknown, unknown>, unknown, any>;

interface ScriptContext {
    readonly api: ScriptApi;
    readonly autoRelogin: ScriptContextAutoReloginApi;
    readonly autoZone: ScriptContextAutoZoneApi;
}
interface ScriptApi {
  /** Aborts when the script stops. Pass this to APIs that support cancellation. */
    readonly signal: AbortSignal;
    log(message: string): void;
  /** Stops the current script. */
    stop(reason?: string): Effect<never, never>;
  /** Waits for milliseconds and cancels when the script stops. */
    sleep(ms: number): Effect<void, ScriptExecutionError>;
    readonly army: ArmyApi;
    readonly auth: AuthApi;
    readonly bank: BankApi;
    readonly combat: CombatApi;
    readonly drops: DropsApi;
    readonly house: HouseApi;
    readonly inventory: InventoryApi;
    readonly packet: ScriptPacketApi;
    readonly player: PlayerApi;
    readonly quests: QuestsApi;
    readonly recipes: RecipesApi;
    readonly settings: SettingsApi;
    readonly shops: ShopsApi;
    readonly tempInventory: TempInventoryApi;
    readonly world: WorldApi;
}
interface ArmyApi {
    start(configName: string): Effect<ArmySession, never | ArmyError | BridgeError>;
    leave(): Effect<void, never | ArmyError | BridgeError>;
    isStarted(): Effect<boolean, never | ArmyError | BridgeError>;
    isLeader(): Effect<boolean, never | ArmyError | BridgeError>;
    isMember(): Effect<boolean, never | ArmyError | BridgeError>;
    getSession(): Effect<ArmySession | null, never | ArmyError | BridgeError>;
  /** Reads a value from the active army config.

Dot-separated keys read nested object values. An empty key returns the raw
config object. Returns `defaultValue` when the army is not started (a.k.a. no config loaded), the key
is missing, or a nested path cannot be resolved. */
    getConfigValue(key: string, defaultValue?: unknown): Effect<unknown, never | ArmyError | BridgeError>;
  /** Reads a string value from the active army config.

Uses the same key resolution rules as `getConfigValue`, but returns
`defaultValue` when the resolved value is missing or not a string. */
    getConfigString(key: string, defaultValue?: string): Effect<string, never | ArmyError | BridgeError>;
  /** The player's number in the army, starting at 1 for the leader and incrementing
for each member. */
    getPlayerNumber(): Effect<number, never | ArmyError | BridgeError>;
    sync(label?: string, options?: ArmyRunStepOptions): Effect<void, never | ArmyError | BridgeError>;
    runStep<A, E>(label: string, action: Effect<A, E, never>, options?: ArmyRunStepOptions): Effect<A, E | ArmyError | BridgeError>;
    executeWithArmy<A, E>(action: Effect<A, E, never>): Effect<A, E | ArmyError | BridgeError>;
    waitForAllInMap(): Effect<void, never | ArmyError | BridgeError>;
    joinMap(map: string, cell?: string, pad?: string): Effect<void, never | ArmyError | BridgeError>;
    kill(target: MonsterIdentifierToken, options?: CombatKillOptions): Effect<void, never | ArmyError | BridgeError>;
    killForItem(target: MonsterIdentifierToken, item: ItemIdentifierToken, quantity?: number, options?: CombatKillOptions): Effect<void, never | ArmyError | BridgeError>;
    killForTempItem(target: MonsterIdentifierToken, item: ItemIdentifierToken, quantity?: number, options?: CombatKillOptions): Effect<void, never | ArmyError | BridgeError>;
    equipSet(setName: string, options?: ArmyEquipSetOptions): Effect<void, never | ArmyError | BridgeError>;
}
interface AuthApi {
    connectTo(server: string): Effect<AuthConnectOutcome, BridgeError>;
    getServers(): Effect<Server[], BridgeError>;
    getUsername(): Effect<string, BridgeError>;
    getPassword(): Effect<string, BridgeError>;
    isLoggedIn(): Effect<boolean, BridgeError>;
    isTemporarilyKicked(): Effect<boolean, BridgeError>;
    login(username: string, password: string): Effect<void, BridgeError>;
    logout(): Effect<void, BridgeError>;
}
interface BankApi {
    contains(item: ItemIdentifierToken, quantity?: number): Effect<boolean, BridgeError>;
    deposit(item: ItemIdentifierToken): Effect<boolean, BridgeError>;
    depositMany(...items: ItemIdentifierToken[]): Effect<void, BridgeError>;
    getItem(item: ItemIdentifierToken): Effect<Item | null, BridgeError>;
    getItems(): Effect<readonly Item[], BridgeError>;
    getSlots(): Effect<number, BridgeError>;
    getUsedSlots(): Effect<number, BridgeError>;
    getAvailableSlots(): Effect<number, BridgeError>;
    isOpen(): Effect<boolean, BridgeError>;
    open(force?: boolean): Effect<void, BridgeError>;
    swap(invKey: ItemIdentifierToken, bankKey: ItemIdentifierToken): Effect<boolean, BridgeError>;
    withdraw(key: ItemIdentifierToken): Effect<boolean, BridgeError>;
    withdrawMany(...items: ItemIdentifierToken[]): Effect<void, BridgeError>;
}
interface CombatApi {
    attackMonster(monster: MonsterIdentifierToken): Effect<void, BridgeError>;
    cancelAutoAttack(): Effect<void, BridgeError>;
    cancelTarget(): Effect<void, BridgeError>;
    canUseSkill(index: string | number): Effect<boolean, BridgeError>;
    exit(): Effect<boolean, BridgeError>;
    getConsumableSkillItem(): Effect<ConsumableSkillItem | null, BridgeError>;
    getTarget(): Effect<Monster | Avatar | null, BridgeError>;
    hasTarget(): Effect<boolean, BridgeError>;
    kill(target: MonsterIdentifierToken, options?: CombatKillOptions): Effect<void, BridgeError>;
    killForItem(target: MonsterIdentifierToken, item: ItemIdentifierToken, quantity?: number, options?: CombatKillOptions): Effect<void, BridgeError>;
    killForTempItem(target: MonsterIdentifierToken, item: ItemIdentifierToken, quantity?: number, options?: CombatKillOptions): Effect<void, BridgeError>;
    useSkill(index: string | number, force?: boolean, wait?: boolean): Effect<void, BridgeError>;
    hunt(target: MonsterIdentifierToken, findMost?: boolean): Effect<string, BridgeError>;
}
interface DropsApi {
    acceptDrop(item: ItemIdentifierToken): Effect<void, BridgeError>;
    containsDrop(item: ItemIdentifierToken): Effect<boolean, BridgeError>;
    isUsingCustomDrops(): Effect<boolean, BridgeError>;
    rejectDrop(itemId: number, visual?: boolean): Effect<boolean, BridgeError>;
    toggleUi(): Effect<void, BridgeError>;
}
interface HouseApi {
    getItem(item: ItemIdentifierToken): Effect<Item | null, BridgeError>;
    getItems(): Effect<readonly Item[], BridgeError>;
    getSlots(): Effect<number, BridgeError>;
    getUsedSlots(): Effect<number, BridgeError>;
    getAvailableSlots(): Effect<number, BridgeError>;
}
interface InventoryApi {
    contains(item: ItemIdentifierToken, quantity?: number): Effect<boolean, BridgeError>;
    equip(item: ItemIdentifierToken): Effect<boolean, BridgeError>;
    getItem(item: ItemIdentifierToken): Effect<Item | null, BridgeError>;
    getItems(): Effect<readonly Item[], BridgeError>;
    getSlots(): Effect<number, BridgeError>;
    getUsedSlots(): Effect<number, BridgeError>;
    getAvailableSlots(): Effect<number, BridgeError>;
}
interface PlayerApi {
    getCell(): Effect<string, BridgeError>;
  /** Uppercased class name. */
    getClassName(): Effect<string, BridgeError>;
    getFactions(): Effect<Collection<string, Faction>, BridgeError>;
    getGender(): Effect<string, BridgeError>;
    getGold(): Effect<number, BridgeError>;
    getHp(): Effect<number, BridgeError>;
    getLevel(): Effect<number, BridgeError>;
    getMaxHp(): Effect<number, BridgeError>;
    getMaxMp(): Effect<number, BridgeError>;
    getMp(): Effect<number, BridgeError>;
    getPad(): Effect<string, BridgeError>;
    getPosition(): Effect<[number, number], BridgeError>;
    getState(): Effect<number, BridgeError>;
    isAfk(): Effect<boolean, BridgeError>;
    isReady(): Effect<boolean, BridgeError>;
    isMember(): Effect<boolean, BridgeError>;
    jumpToCell(cell: string, pad?: string, correction?: boolean): Effect<void, BridgeError>;
    joinMap(map: string, cell?: string, pad?: string): Effect<void, BridgeError>;
    goToPlayer(name: string): Effect<void, BridgeError>;
    rest(full?: boolean): Effect<void, BridgeError>;
    useBoost(boost: ItemIdentifierToken): Effect<boolean, BridgeError>;
    hasActiveBoost(boostType: 'classPoints' | 'exp' | 'gold' | 'rep'): Effect<boolean, BridgeError>;
    isAlive(): Effect<boolean, BridgeError>;
    walkTo(x: number, y: number, walkSpeed?: number): Effect<boolean, BridgeError>;
}
interface QuestsApi {
    abandon(questId: number): Effect<void, BridgeError>;
    accept(questId: number, silent?: boolean): Effect<void, BridgeError>;
    canComplete(questId: number): Effect<boolean, BridgeError>;
    complete(questId: number, turnIns?: number, itemId?: number, special?: boolean): Effect<void, BridgeError>;
    getMaxTurnIns(questId: number): Effect<number, BridgeError>;
    load(questId: number, silent?: boolean): Effect<void, BridgeError>;
    loadMany(questIds: number[], silent?: boolean): Effect<void, BridgeError>;
    getTree(): Effect<Collection<number, Quest>, never>;
    has(questId: number): Effect<boolean, never>;
    getAccepted(): Effect<Quest[], BridgeError>;
    isAvailable(questId: number): Effect<boolean, BridgeError>;
    isInProgress(questId: number): Effect<boolean, BridgeError>;
}
interface RecipesApi {
    buff(skillList?: readonly number[] | null, wait?: boolean): Effect<void, unknown>;
    ensureLifeSteal(quantity: number): Effect<void, unknown>;
    ensureScrollOfEnrage(quantity: number): Effect<void, unknown>;
    useConsumables(items: string | readonly string[], equipAfter?: string): Effect<void, unknown>;
    goToHouse(player?: string): Effect<void, unknown>;
    beep(times?: number): Effect<void, unknown>;
    doWheelOfDoom(toBank?: boolean): Effect<void, unknown>;
    waitForPlayerCount(count: number, exact?: boolean): Effect<void, unknown>;
    equipItemByEnhancement(options: EquipEnhancementSelector): Effect<void, unknown>;
    enhanceItem(item: string, options: ScriptEnhanceItemOptions): Effect<void, unknown>;
}
interface ScriptContextAutoReloginApi {
    isEnabled(): Effect<boolean, never>;
    enable(): Effect<void, never>;
    disable(): Effect<void, never>;
    getDelay(): Effect<number, never>;
    setDelay(delayMs: number): Effect<void, never>;
    getServer(): Effect<string | undefined, never>;
    setServer(serverName: string): Effect<void, never>;
}
interface ScriptContextAutoZoneApi {
    isEnabled(): Effect<boolean, never>;
    getMap(): Effect<AutoZoneSupportedMap | undefined, never>;
    enable(): Effect<void, never>;
    disable(): Effect<void, never>;
    setMap(map: 'ledgermayne' | 'moreskulls' | 'ultradage' | 'darkcarnax' | 'astralshrine' | 'queeniona' | 'magnumopus' | undefined): Effect<void, never>;
}
interface ScriptPacketApi {
    sendClient(packet: string, type?: ClientPacketSendType): Effect<void, BridgeError>;
    sendServer(packet: string, type?: ServerPacketSendType): Effect<void, BridgeError>;
    packetFromClient(handler: ScriptPacketListener): Effect<ScriptPacketDisposer, ScriptNotReadyError>;
    packetFromServer(handler: ScriptPacketListener): Effect<ScriptPacketDisposer, ScriptNotReadyError>;
    onExtensionResponse(handler: ScriptPacketListener): Effect<ScriptPacketDisposer, ScriptNotReadyError>;
}
interface SettingsApi {
    setEnemyMagnet(enabled: boolean): Effect<void, BridgeError>;
    setInfiniteRange(enabled: boolean): Effect<void, BridgeError>;
    setProvokeCell(enabled: boolean): Effect<void, BridgeError>;
    setSkipCutscenes(enabled: boolean): Effect<void, BridgeError>;
    setCustomName(name: string): Effect<void, BridgeError>;
    setCustomGuild(name: string): Effect<void, BridgeError>;
    setWalkSpeed(speed: number): Effect<void, BridgeError>;
    setDeathAdsVisible(visible: boolean): Effect<void, BridgeError>;
    setCollisionsEnabled(enabled: boolean): Effect<void, BridgeError>;
    setEffectsEnabled(enabled: boolean): Effect<void, BridgeError>;
    setOtherPlayersVisible(visible: boolean): Effect<void, BridgeError>;
    setLagKillerEnabled(enabled: boolean): Effect<void, BridgeError>;
    setFrameRate(fps: number): Effect<void, BridgeError>;
}
interface ShopsApi {
    buyById(id: number, quantity?: number): Effect<boolean, BridgeError>;
    buyByName(name: string, quantity?: number): Effect<boolean, BridgeError>;
    canBuyItem(key: ItemIdentifierToken, quantity?: number): Effect<boolean, BridgeError>;
    close(shopId?: number): Effect<boolean, BridgeError>;
    getInfo(): Effect<ShopInfo | null, BridgeError>;
    getItem(key: ItemIdentifierToken): Effect<ShopItem | null, BridgeError>;
    getItems(): Effect<readonly ShopItem[], BridgeError>;
    getMaxBuyQuantity(key: ItemIdentifierToken): Effect<number, BridgeError>;
    isOpen(shopId?: number): Effect<boolean, BridgeError>;
    isMergeShop(): Effect<boolean, BridgeError>;
    load(shopId: number): Effect<void, BridgeError>;
    loadArmorCustomize(): Effect<void, BridgeError>;
    loadHairShop(shopId: number): Effect<void, BridgeError>;
    sellById(id: number, quantity?: number): Effect<boolean, BridgeError>;
    sellByName(name: string, quantity?: number): Effect<boolean, BridgeError>;
}
interface TempInventoryApi {
    contains(item: ItemIdentifierToken, quantity?: number): Effect<boolean, BridgeError>;
    getItem(item: ItemIdentifierToken): Effect<Item | null, BridgeError>;
    getItems(): Effect<readonly Item[], BridgeError>;
}
interface WorldApi {
    readonly map: WorldMapApi;
    readonly players: WorldPlayersApi;
    readonly monsters: WorldMonstersApi;
}
interface WorldMapApi {
    getCellMonsters(): Effect<Monster[], BridgeError>;
    getCells(): Effect<string[], BridgeError>;
    getCellPads(): Effect<string[], BridgeError>;
    isLoaded(): Effect<boolean, BridgeError>;
    isActionAvailable(gameAction: 'acceptQuest' | 'buyItem' | 'doIA' | 'equipItem' | 'getMapItem' | 'loadEnhShop' | 'loadHairShop' | 'loadShop' | 'rest' | 'sellItem' | 'tfer' | 'tryQuestComplete' | 'unequipItem' | 'who'): Effect<boolean, BridgeError>;
    getMapItem(itemId: number): Effect<void, BridgeError>;
    loadSwf(path: string): Effect<void, BridgeError>;
    reload(): Effect<void, BridgeError>;
    setSpawnPoint(cell?: string, pad?: string): Effect<void, BridgeError>;
    waitForGameAction(gameAction: 'acceptQuest' | 'buyItem' | 'doIA' | 'equipItem' | 'getMapItem' | 'loadEnhShop' | 'loadHairShop' | 'loadShop' | 'rest' | 'sellItem' | 'tfer' | 'tryQuestComplete' | 'unequipItem' | 'who', timeout?: DurationInput): Effect<boolean, BridgeError>;
    getName(): Effect<string, never>;
    getId(): Effect<number, never>;
    getRoomNumber(): Effect<number, never>;
}
interface WorldMonstersApi {
    getAll(): Effect<Collection<number, Monster>, never>;
    get(monMapId: number): Effect<Option<Monster>, never>;
    findByName(name: string, cell?: string): Effect<Option<Monster>, never>;
    getAura(monMapId: number, auraName: string): Effect<Option<Aura>, never>;
}
interface WorldPlayersApi {
    readonly me: WorldPlayersMeApi;
    getAll(): Effect<Collection<string, Avatar>, never>;
    get(username: string): Effect<Option<Avatar>, never>;
    getByName(name: string): Effect<Option<Avatar>, never>;
    getAuras(username: string): Effect<readonly Aura[], never>;
    getAura(username: string, auraName: string): Effect<Option<Aura>, never>;
}
interface WorldPlayersMeApi {
    get(): Effect<Option<Avatar>, never>;
    getAuras(): Effect<readonly Aura[], never>;
    getAura(auraName: string): Effect<Option<Aura>, never>;
}

interface ArmyEquipSetOptions {
  /**
   * When true, items will be resolved under the `items` key of the army config.
   */
  readonly resolveItems?: boolean;
}
interface ArmyRunStepOptions {
  readonly timeoutMs?: number;
}
type ArmySession = ArmySessionPayload;
type Aura = {
  duration?: number;
  isNew?: boolean;
  name: string;
  /**
   * Number of active instances tracked for this aura name.
   */
  stack?: number;
  /**
   * The aura's value, if applicable.
   * Can be an integer or float.
   */
  value?: number;
};
type AuthConnectOutcome =
  | {
      readonly status: "connected";
      readonly message: string;
      readonly retryable: false;
      readonly serverName?: string;
    }
  | {
      readonly status: AuthConnectFailureStatus;
      readonly message: string;
      readonly retryable: boolean;
      readonly serverName?: string;
    };
type AutoZoneSupportedMap = 'ledgermayne' | 'moreskulls' | 'ultradage' | 'darkcarnax' | 'astralshrine' | 'queeniona' | 'magnumopus';
interface Avatar extends BaseEntity {
  readonly data: AvatarData;
  readonly pad: string;
  readonly mp: number;
  readonly maxMp: number;
  readonly mpPercentage: number;
  readonly level: number;
  readonly username: string;
  isAFK(): boolean;
  readonly position: [number, number];
}
type ClientPacketSendType = "str" | "json" | "xml";
interface Collection<Key, Value> extends Map<Key, Value> {
  ensure(key: Key, defaultValueGenerator: (key: Key, collection: this) => Value): Value;
  hasAll(...keys: Key[]): boolean;
  hasAny(...keys: Key[]): boolean;
  first(): Value | undefined;
  first(amount: number): Value[];
  firstKey(): Key | undefined;
  firstKey(amount: number): Key[];
  last(): Value | undefined;
  last(amount: number): Value[];
  lastKey(): Key | undefined;
  lastKey(amount: number): Key[];
  at(index: number): Value | undefined;
  keyAt(index: number): Key | undefined;
  random(): Value | undefined;
  random(amount: number): Value[];
  randomKey(): Key | undefined;
  randomKey(amount: number): Key[];
  reverse(): this;
  find<NewValue extends Value>(fn: (value: Value, key: Key, collection: this) => value is NewValue): NewValue | undefined;
  find(fn: (value: Value, key: Key, collection: this) => unknown): Value | undefined;
  find<This, NewValue extends Value>(fn: (this: This, value: Value, key: Key, collection: this) => value is NewValue, thisArg: This): NewValue | undefined;
  find<This>(fn: (this: This, value: Value, key: Key, collection: this) => unknown, thisArg: This): Value | undefined;
  findKey<NewKey extends Key>(fn: (value: Value, key: Key, collection: this) => key is NewKey): NewKey | undefined;
  findKey(fn: (value: Value, key: Key, collection: this) => unknown): Key | undefined;
  findKey<This, NewKey extends Key>(fn: (this: This, value: Value, key: Key, collection: this) => key is NewKey, thisArg: This): NewKey | undefined;
  findKey<This>(fn: (this: This, value: Value, key: Key, collection: this) => unknown, thisArg: This): Key | undefined;
  findLast<NewValue extends Value>(fn: (value: Value, key: Key, collection: this) => value is NewValue): NewValue | undefined;
  findLast(fn: (value: Value, key: Key, collection: this) => unknown): Value | undefined;
  findLast<This, NewValue extends Value>(fn: (this: This, value: Value, key: Key, collection: this) => value is NewValue, thisArg: This): NewValue | undefined;
  findLast<This>(fn: (this: This, value: Value, key: Key, collection: this) => unknown, thisArg: This): Value | undefined;
  findLastKey<NewKey extends Key>(fn: (value: Value, key: Key, collection: this) => key is NewKey): NewKey | undefined;
  findLastKey(fn: (value: Value, key: Key, collection: this) => unknown): Key | undefined;
  findLastKey<This, NewKey extends Key>(fn: (this: This, value: Value, key: Key, collection: this) => key is NewKey, thisArg: This): NewKey | undefined;
  findLastKey<This>(fn: (this: This, value: Value, key: Key, collection: this) => unknown, thisArg: This): Key | undefined;
  sweep(fn: (value: Value, key: Key, collection: this) => unknown): number;
  sweep<This>(fn: (this: This, value: Value, key: Key, collection: this) => unknown, thisArg: This): number;
  filter<NewKey extends Key>(fn: (value: Value, key: Key, collection: this) => key is NewKey): Collection<NewKey, Value>;
  filter<NewValue extends Value>(fn: (value: Value, key: Key, collection: this) => value is NewValue): Collection<Key, NewValue>;
  filter(fn: (value: Value, key: Key, collection: this) => unknown): Collection<Key, Value>;
  filter<This, NewKey extends Key>(fn: (this: This, value: Value, key: Key, collection: this) => key is NewKey, thisArg: This): Collection<NewKey, Value>;
  filter<This, NewValue extends Value>(fn: (this: This, value: Value, key: Key, collection: this) => value is NewValue, thisArg: This): Collection<Key, NewValue>;
  filter<This>(fn: (this: This, value: Value, key: Key, collection: this) => unknown, thisArg: This): Collection<Key, Value>;
  partition<NewKey extends Key>(fn: (value: Value, key: Key, collection: this) => key is NewKey): [Collection<NewKey, Value>, Collection<Exclude<Key, NewKey>, Value>];
  partition<NewValue extends Value>(fn: (value: Value, key: Key, collection: this) => value is NewValue): [Collection<Key, NewValue>, Collection<Key, Exclude<Value, NewValue>>];
  partition(fn: (value: Value, key: Key, collection: this) => unknown): [Collection<Key, Value>, Collection<Key, Value>];
  partition<This, NewKey extends Key>(fn: (this: This, value: Value, key: Key, collection: this) => key is NewKey, thisArg: This): [Collection<NewKey, Value>, Collection<Exclude<Key, NewKey>, Value>];
  partition<This, NewValue extends Value>(fn: (this: This, value: Value, key: Key, collection: this) => value is NewValue, thisArg: This): [Collection<Key, NewValue>, Collection<Key, Exclude<Value, NewValue>>];
  partition<This>(fn: (this: This, value: Value, key: Key, collection: this) => unknown, thisArg: This): [Collection<Key, Value>, Collection<Key, Value>];
  flatMap<NewValue>(fn: (value: Value, key: Key, collection: this) => Collection<Key, NewValue>): Collection<Key, NewValue>;
  flatMap<NewValue, This>(fn: (this: This, value: Value, key: Key, collection: this) => Collection<Key, NewValue>, thisArg: This): Collection<Key, NewValue>;
  map<NewValue>(fn: (value: Value, key: Key, collection: this) => NewValue): NewValue[];
  map<This, NewValue>(fn: (this: This, value: Value, key: Key, collection: this) => NewValue, thisArg: This): NewValue[];
  mapValues<NewValue>(fn: (value: Value, key: Key, collection: this) => NewValue): Collection<Key, NewValue>;
  mapValues<This, NewValue>(fn: (this: This, value: Value, key: Key, collection: this) => NewValue, thisArg: This): Collection<Key, NewValue>;
  some(fn: (value: Value, key: Key, collection: this) => unknown): boolean;
  some<This>(fn: (this: This, value: Value, key: Key, collection: this) => unknown, thisArg: This): boolean;
  every<NewKey extends Key>(fn: (value: Value, key: Key, collection: this) => key is NewKey): boolean;
  every<NewValue extends Value>(fn: (value: Value, key: Key, collection: this) => value is NewValue): boolean;
  every(fn: (value: Value, key: Key, collection: this) => unknown): boolean;
  every<This, NewKey extends Key>(fn: (this: This, value: Value, key: Key, collection: this) => key is NewKey, thisArg: This): boolean;
  every<This, NewValue extends Value>(fn: (this: This, value: Value, key: Key, collection: this) => value is NewValue, thisArg: This): boolean;
  every<This>(fn: (this: This, value: Value, key: Key, collection: this) => unknown, thisArg: This): boolean;
  reduce(fn: (accumulator: Value, value: Value, key: Key, collection: this) => Value, initialValue?: Value): Value;
  reduce<InitialValue>(fn: (accumulator: InitialValue, value: Value, key: Key, collection: this) => InitialValue, initialValue: InitialValue): InitialValue;
  reduceRight(fn: (accumulator: Value, value: Value, key: Key, collection: this) => Value, initialValue?: Value): Value;
  reduceRight<InitialValue>(fn: (accumulator: InitialValue, value: Value, key: Key, collection: this) => InitialValue, initialValue: InitialValue): InitialValue;
  each(fn: (value: Value, key: Key, collection: this) => void): this;
  each<This>(fn: (this: This, value: Value, key: Key, collection: this) => void, thisArg: This): this;
  tap(fn: (collection: this) => void): this;
  tap<This>(fn: (this: This, collection: this) => void, thisArg: This): this;
  clone(): Collection<Key, Value>;
  concat(...collections: ReadonlyCollection<Key, Value>[]): Collection<Key, Value>;
  equals(collection: ReadonlyCollection<Key, Value>): boolean;
  sort(compareFunction?: Comparator<Key, Value>): this;
  intersection(other: ReadonlyCollection<Key, any>): Collection<Key, Value>;
  union<OtherValue>(other: ReadonlyCollection<Key, OtherValue>): Collection<Key, Value | OtherValue>;
  difference(other: ReadonlyCollection<Key, any>): Collection<Key, Value>;
  symmetricDifference<OtherValue>(other: ReadonlyCollection<Key, OtherValue>): Collection<Key, Value | OtherValue>;
  merge<OtherValue, ResultValue>(other: ReadonlyCollection<Key, OtherValue>, whenInSelf: (value: Value, key: Key) => Keep<ResultValue>, whenInOther: (valueOther: OtherValue, key: Key) => Keep<ResultValue>, whenInBoth: (value: Value, valueOther: OtherValue, key: Key) => Keep<ResultValue>): Collection<Key, ResultValue>;
  toReversed(): Collection<Key, Value>;
  toSorted(compareFunction?: Comparator<Key, Value>): Collection<Key, Value>;
  toJSON(): [Key, Value][];
}
interface CombatKillOptions {
  readonly killPriority?: readonly MonsterIdentifierToken[] | string;
  readonly skillSet?: readonly Skill[] | string;
  readonly skillDelay?: number;
  readonly skillWait?: boolean;
}
type ConsumableSkillItem = {
  itemId?: number;
  name?: string;
};
type EquipEnhancementSelector = {
  readonly enhancement: string;
  readonly slot?: EquipEnhancementSelectorSlot;
  readonly special?: string;
};
interface Faction {
  data: FactionData;
  readonly id: number;
  readonly name: string;
  readonly rank: number;
  readonly totalRep: number;
  readonly rep: number;
  readonly requiredRep: number;
  readonly remainingRep: number;
}
interface Item {
  data: ItemData;
  readonly id: number;
  readonly name: string;
  readonly description: string;
  readonly quantity: number;
  readonly maxStack: number;
  isUpgrade(): boolean;
  isAC(): boolean;
  readonly category: string;
  isTemp(): boolean;
  readonly itemGroup: string;
  isArmor(): boolean;
  isClass(): boolean;
  isCape(): boolean;
  isHelm(): boolean;
  isPet(): boolean;
  isWeapon(): boolean;
  readonly fileName: string;
  readonly fileLink: string;
  readonly meta: Record<string, number> | null;
  readonly classRank: number | null;
  isMaxed(): boolean;
  isMember(): boolean;
  readonly charItemId: number;
  isEquipped(): boolean;
  isWearing(): boolean;
  readonly level: number;
  readonly enhancementLevel: number;
  readonly enhancementPatternId: number;
  isBoost(): boolean;
}
interface Monster extends BaseEntity {
  readonly data: MonsterData;
  readonly monMapId: number;
  readonly id: number;
  readonly level: number;
  readonly race: string;
  readonly name: string;
  readonly cell: string;
}
interface Quest {
  data: QuestInfo;
  readonly name: string;
  readonly id: number;
  readonly once: boolean;
  readonly rewards: QuestReward[];
  readonly requirements: QuestRequirement[];
  isDaily(): boolean;
  isWeekly(): boolean;
  isMonthly(): boolean;
}
interface ScriptEnhanceItemOptions {
  readonly enhancement: string;
  readonly special?: string;
}
type ScriptPacketDisposer = () => void;
type ScriptPacketListener = (
  packet: string,
) =>
  | void
  | Effect<unknown, unknown>
  | Generator<EffectYieldable<any, any, never, never>, unknown, never>;
interface Server {
  data: ServerData;
  readonly maxPlayers: number;
  readonly port: number;
  readonly langCode: string;
  readonly name: string;
  readonly ip: string;
  readonly playerCount: number;
  isUpgrade(): boolean;
  isCanned(): boolean;
  isOnline(): boolean;
  isFull(): boolean;
}
type ServerPacketSendType = "String" | "Json";
type ShopInfo = {
  Location: string;
  ShopID: string;
  bHouse: string;
  bStaff: string;
  bUpgrd: string;
  iIndex: string;
  items: ShopItemData[];
  sField: string;
  sName: string;
};
interface ShopItem extends Item {
  data: ShopItemData;
}
interface When { readonly [key: string]: unknown; }
interface ArmySessionPayload extends ArmyConfigPayload {
  readonly sessionId: string;
  readonly playerName: string;
  readonly playerNumber: number;
  readonly role: "leader" | "member";
}
interface Number { readonly [key: string]: unknown; }
interface The { readonly [key: string]: unknown; }
interface Can { readonly [key: string]: unknown; }
type AuthConnectFailureStatus =
  | Exclude<ConnectToSelectionStatus, "selected">
  | "connection-failed"
  | "connection-error"
  | "timeout";
interface BaseEntity {
  readonly data: BaseEntityData;
  readonly hp: number;
  readonly maxHp: number;
  readonly hpPercentage: number;
  readonly state: EntityState;
  readonly alive: boolean;
  isHpLessThan(value: number): boolean;
  isHpGreaterThan(value: number): boolean;
  isHpPercentageLessThan(value: number): boolean;
  isHpPercentageGreaterThan(value: number): boolean;
  isInCombat(): boolean;
  isDead(): boolean;
  isIdle(): boolean;
  isPlayer(): boolean;
  isMonster(): boolean;
  readonly cell: string;
  isInCell(cell: string): boolean;
}
type AvatarData = BaseEntityData & {
  afk: boolean;
  entID: number;
  entType: string;
  intLevel: number;
  intMP: number;
  intMPMax: number;
  strPad: string;
  strUsername: string;
  tx: number;
  ty: number;
  uoName: string;
};
type ReadonlyCollection<Key, Value> = Omit<Collection<Key, Value>, keyof Map<Key, Value> | "ensure" | "reverse" | "sort" | "sweep"> & ReadonlyMap<Key, Value>;
type Comparator<Key, Value> = (firstValue: Value, secondValue: Value, firstKey: Key, secondKey: Key) => number;
type Keep<Value> = {
    keep: false;
} | {
    keep: true;
    value: Value;
};
type EquipEnhancementSelectorSlot = EquipItemTypeFilter | "armor";
type FactionData = {
  CharFactionID: string;
  /**
   * The ID of the faction.
   */
  FactionID: string;
  /**
   * The rank that the player has achieved in this faction.
   */
  iRank: number;
  /**
   * The total amount of rep the player has for this faction.
   */
  iRep: number;
  /**
   * The total required rep for the player to rank up.
   */
  iRepToRank: number;
  /**
   * The amount of rep the player has for their current rank.
   */
  iSpillRep: number;
  /**
   * The name of the faction.
   */
  sName: string;
};
type ItemData = {
  CharID: number;
  CharItemID: number;
  EnhDPS: number;
  EnhID: number;
  EnhLvl: number;
  EnhPatternID: number;
  PatternID?: number | string;
  EnhRng: number;
  EnhRty: number;
  ItemID: number;
  ProcID?: number;
  bBank: number;
  bHouse: number;
  bCoins: number;
  bEquip: number;
  bStaff: number;
  bTemp: number;
  bUpg: number;
  bWear: number;
  dPurchase: string;
  iCost: number;
  iDPS: number;
  iHrs: number;
  iLvl: number;
  iQty: number;
  iRng: number;
  iRty: number;
  iStk: number;
  iType: number;
  sDesc: string;
  sES: string;
  sElmt: string;
  sFile: string;
  sIcon: string;
  sLink: string;
  sMeta: string;
  sName: string;
  sType: string;
};
type MonsterData = BaseEntityData & {
  iLvl: number;
  intMP: number;
  intMPMax: number;
  monId: number;
  monMapId: number;
  sRace: string;
  strFrame: string;
  strMonName: string;
};
type QuestInfo = {
  FactionID: string;
  /**
   * The ID of this quest.
   */
  QuestID: string;
  RequiredItems: QuestRequirementData[];
  Rewards: QuestBonusRewardData[];
  bGuild: string;
  /**
   * Whether this quest can only be completed once.
   */
  bOnce: string;
  bStaff: string;
  bUpg: string;
  bitSuccess: string;
  iClass: number;
  /**
   * The amount of experience rewarded for completing this quest.
   */
  iExp: number;
  /**
   * The amount of gold rewarded for completing this quest.
   */
  iGold: number;
  iIndex?: number;
  /**
   * The required level to accept this quest.
   */
  iLvl: number;
  /**
   * The amount of reputation rewarded for completing this quest. 0 if not applicable.
   */
  iRep: number;
  /**
   * The class points required to accept this quest. 0 if not applicable.
   */
  iReqCP: number;
  /**
   * The required faction reputation to accept this quest.
   */
  iReqRep: number;
  iSlot: number;
  iValue: number;
  iWar: number;
  metaValues: Record<string, string>;
  oItems: Record<string, ItemData>;
  oRewards: Record<string, QuestBonusRewardData>;
  reward: QuestRewardData[];
  /**
   * The description of this quest.
   */
  sDesc: string;
  /**
   * The text displayed when this quest can be completed.
   */
  sEndText: string;
  /**
   * The name of the faction that this quest is for.
   */
  sFaction: string;
  sField?: string;
  /**
   * The name of this quest.
   */
  sName: string;
  /**
   * The status of the quest.
   */
  status: string;
  turnin: QuestTurnInData[];
};
type QuestReward = {
  /**
   * The drop chance of the item with a percent sign.
   */
  dropChance: string;
  /**
   * The item ID.
   */
  itemId: string;
  /**
   * The name of the item.
   */
  itemName: string;
  /**
   * The quantity of the item.
   */
  quantity: number;
};
type QuestRequirement = {
  /**
   * The item ID.
   */
  itemId: string;
  /**
   * The name of the item.
   */
  itemName: string;
  /**
   * The quantity of the item.
   */
  quantity: number;
};
type ServerData = {
  bOnline: number;
  bUpg: number;
  iChat: number;
  iCount: number;
  iLevel: number;
  iMax: number;
  iPort: number;
  sIP: string;
  sLang: string;
  sName: string;
};
interface Json { readonly [key: string]: unknown; }
interface Location { readonly [key: string]: unknown; }
interface ShopID { readonly [key: string]: unknown; }
type ShopItemData = ItemData & {
  /**
   * Faction ID associated with the item.
   */
  FactionID: string;
  /**
   * Proc ID for Forge/Awe weapon enhancements
   */
  ItemProcID?: string;
  /**
   * Shop item id.
   */
  ShopItemID: string;
  /**
   * Enhancement-specific properties
   */
  bEnhShop?: boolean;
  /**
   * Whether the item can be placed in a house.
   */
  bHouse: string;
  iClass: string;
  iQSindex: string;
  iQSvalue: string;
  iQtyRemain: string;
  iReqCP: string;
  iReqRep: string;
  /**
   * Faction associated with the item.
   */
  sFaction: string;
  sQuest?: string;
  /**
   * Items required to merge this item.
   */
  turnin?: {
    ItemID: string;
    iQty: string;
    sName: string;
  }[];
};
interface ArmyConfigPayload extends ArmyConfigCore {
  readonly configName: string;
  readonly raw: ArmyConfigRaw;
}
type ConnectToSelectionStatus =
  | "selected"
  | "not-ready"
  | "offline"
  | "full"
  | "member-only"
  | "chat-restricted"
  | "underage-chat"
  | "email-unconfirmed"
  | "test-client-required"
  | "not-found";
type BaseEntityData = {
  intHP: number;
  intHPMax: number;
  intState: number;
  strFrame: string;
};
enum EntityState {
  /**
   * The entity is dead.
   */
  Dead = 0,
  /**
   * The entity is idle.
   */
  Idle = 1,
  /**
   * The entity is in combat.
   */
  InCombat = 2
}
type EquipItemTypeFilter = "weapon" | "cape" | "helm" | "class";
interface CharFactionID { readonly [key: string]: unknown; }
interface ID { readonly [key: string]: unknown; }
interface FactionID { readonly [key: string]: unknown; }
interface CharID { readonly [key: string]: unknown; }
interface CharItemID { readonly [key: string]: unknown; }
interface EnhDPS { readonly [key: string]: unknown; }
interface EnhID { readonly [key: string]: unknown; }
interface EnhLvl { readonly [key: string]: unknown; }
interface EnhPatternID { readonly [key: string]: unknown; }
interface PatternID { readonly [key: string]: unknown; }
interface EnhRng { readonly [key: string]: unknown; }
interface EnhRty { readonly [key: string]: unknown; }
interface ItemID { readonly [key: string]: unknown; }
interface ProcID { readonly [key: string]: unknown; }
interface QuestID { readonly [key: string]: unknown; }
interface RequiredItems { readonly [key: string]: unknown; }
type QuestRequirementData = {
  /**
   * The item ID.
   */
  ItemID: string;
  /**
   * The quantity of the item.
   */
  iQty: number;
  /**
   * The name of the item.
   */
  sName: string;
};
interface Rewards { readonly [key: string]: unknown; }
type QuestBonusRewardData = {
  /**
   * The drop chance of the item with a percent sign.
   */
  DropChance: string;
  /**
   * The item ID.
   */
  ItemID: string;
  /**
   * The quantity of the item.
   */
  iQty: number;
  /**
   * The name of the item.
   */
  sName: string;
};
interface Whether { readonly [key: string]: unknown; }
type QuestRewardData = {
  /**
   * The item ID.
   */
  ItemID: string;
  /**
   * The quantity of the item.
   */
  iQty: number;
  /**
   * The rate of the reward without a percent sign.
   */
  iRate: string;
  /**
   * The type of the reward.
   */
  iType: string;
};
type QuestTurnInData = {
  /**
   * The item ID.
   */
  ItemID: string;
  /**
   * The quantity of the item.
   */
  iQty: number;
};
interface Proc { readonly [key: string]: unknown; }
interface Forge { readonly [key: string]: unknown; }
interface Awe { readonly [key: string]: unknown; }
interface ItemProcID { readonly [key: string]: unknown; }
interface Shop { readonly [key: string]: unknown; }
interface ShopItemID { readonly [key: string]: unknown; }
interface Enhancement { readonly [key: string]: unknown; }
interface Items { readonly [key: string]: unknown; }
interface ArmyConfigCore {
  readonly leader: string;
  readonly players: readonly string[];
  readonly roomNumber: string;
}
type ArmyConfigRaw = Record<string, unknown>;
interface Dead { readonly [key: string]: unknown; }
interface Idle { readonly [key: string]: unknown; }
interface InCombat { readonly [key: string]: unknown; }
interface DropChance { readonly [key: string]: unknown; }
