packages:
  - packages/*
  - app
  - docs

ignoredBuiltDependencies:
  - core-js
  - esbuild
  - svelte-preprocess
  - unrs-resolver

onlyBuiltDependencies:
  - electron # https://github.com/electron/electron/issues/44008
