import { execFile } from "node:child_process";
import fs from "node:fs/promises";
import {
  basename,
  dirname,
  isAbsolute,
  join,
  relative,
  resolve,
} from "node:path";
import { promisify } from "node:util";
import { fileURLToPath, pathToFileURL } from "node:url";

import * as NodeRuntime from "@effect/platform-node/NodeRuntime";
import { Console, Effect } from "effect";
import ts from "typescript";

const execFileAsync = promisify(execFile);

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const DEFAULT_REPO_ROOT = join(SCRIPT_DIR, "..");
const DEFAULT_SOURCE_DIR = "app/src/renderer/game/scripting/Commands";
const DEFAULT_OUTPUT_DIR = "docs/src/content/docs/script-commands";
const COMMAND_FACTORY_PATTERN = /^create.*ScriptDsl$/;
const GENERATED_HEADER =
  "<!-- Generated by pnpm run docgen. Do not edit directly. -->";

const SUPPORT_FILES = new Set([
  "commandDsl.ts",
  "customCommand.ts",
  "customCondition.ts",
  "index.ts",
  "itemOperations.ts",
]);

const TYPE_REFERENCE_WRAPPERS = new Set([
  "Array",
  "Partial",
  "Readonly",
  "ReadonlyArray",
  "Record",
  "Promise",
  "Required",
]);

type CliOptions = {
  readonly repoRoot: string;
  readonly sourceDir: string;
  readonly outputDir: string;
  readonly includeSourceLinks: boolean;
};

type GitSourceInfo = {
  readonly repoUrl: string;
  readonly branch: string;
};

type CommandParameterDoc = {
  readonly name: string;
  readonly type: string;
  readonly required: boolean;
  readonly rest: boolean;
  readonly defaultValue: string | null;
  readonly description: string;
};

type CommandJsDocTag = {
  readonly tag: string;
  readonly name: string | null;
  readonly text: string;
};

type CommandDoc = {
  readonly domain: string;
  readonly name: string;
  readonly aliases: readonly string[];
  readonly summary: string;
  readonly call: string;
  readonly signature: string;
  readonly parameters: readonly CommandParameterDoc[];
  readonly returnType: string;
  readonly tags: readonly CommandJsDocTag[];
  readonly examples: readonly string[];
  readonly remarks: readonly string[];
  readonly deprecated: boolean;
  readonly deprecationMessages: readonly string[];
  readonly returns: readonly string[];
  readonly sourcePath: string;
  readonly sourceLine: number;
  readonly sourceUrl: string | null;
};

type TypePropertyDoc = {
  readonly name: string;
  readonly type: string;
  readonly required: boolean;
  readonly readonly: boolean;
  readonly description: string;
};

type TypeShapeDoc = {
  readonly name: string;
  readonly kind: "interface" | "type";
  readonly summary: string;
  readonly definition: string;
  readonly properties: readonly TypePropertyDoc[];
  readonly sourcePath: string;
  readonly sourceLine: number;
  readonly sourceUrl: string | null;
};

type DomainDocs = {
  readonly domain: string;
  readonly commands: readonly CommandDoc[];
  readonly types: readonly TypeShapeDoc[];
};

type RenderedFile = {
  readonly path: string;
  readonly content: string;
};

type TypeLinkRegistry = ReadonlyMap<string, string>;

class DocgenError extends Error {
  override readonly name = "DocgenError";
}

const fail = (message: string): never => {
  throw new DocgenError(message);
};

const parseCliOptions = (
  args: ReadonlyArray<string>,
  repoRoot: string,
): CliOptions => {
  let source = DEFAULT_SOURCE_DIR;
  let out = DEFAULT_OUTPUT_DIR;
  let includeSourceLinks = false;

  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index];
    if (arg === "--") {
      continue;
    }
    if (arg === "--include-source-links") {
      includeSourceLinks = true;
      continue;
    }
    if (arg === "--source") {
      source = args[index + 1] ?? fail("--source requires a path");
      index += 1;
      continue;
    }
    if (arg.startsWith("--source=")) {
      source = arg.slice("--source=".length);
      continue;
    }
    if (arg === "--out") {
      out = args[index + 1] ?? fail("--out requires a path");
      index += 1;
      continue;
    }
    if (arg.startsWith("--out=")) {
      out = arg.slice("--out=".length);
      continue;
    }
    fail(`Unknown argument: ${arg}`);
  }

  return {
    repoRoot,
    sourceDir: isAbsolute(source) ? source : resolve(repoRoot, source),
    outputDir: isAbsolute(out) ? out : resolve(repoRoot, out),
    includeSourceLinks,
  };
};

const normalizeGitRemoteUrl = (rawUrl: string): string | null => {
  const url = rawUrl.trim().replace(/\.git$/, "");
  if (url.startsWith("https://")) {
    return url;
  }
  if (url.startsWith("http://")) {
    return `https://${url.slice("http://".length)}`;
  }

  const sshMatch = url.match(/^git@([^:]+):(.+)$/);
  if (sshMatch) {
    return `https://${sshMatch[1]}/${sshMatch[2]}`;
  }

  return null;
};

const getGitSourceInfo = (
  repoRoot: string,
): Effect.Effect<GitSourceInfo | null> =>
  Effect.gen(function* () {
    const remoteUrl = yield* Effect.tryPromise(async () => {
      const result = await execFileAsync(
        "git",
        ["remote", "get-url", "origin"],
        {
          cwd: repoRoot,
        },
      );
      return result.stdout;
    }).pipe(Effect.catch(() => Effect.succeed(null)));

    if (remoteUrl === null) {
      return null;
    }

    const repoUrl = normalizeGitRemoteUrl(remoteUrl);
    if (repoUrl === null) {
      return null;
    }

    const branchOutput = yield* Effect.tryPromise(async () => {
      const result = await execFileAsync(
        "git",
        ["symbolic-ref", "--short", "refs/remotes/origin/HEAD"],
        { cwd: repoRoot },
      );
      return result.stdout.trim();
    }).pipe(Effect.catch(() => Effect.succeed("origin/main")));

    const branch = branchOutput.replace(/^origin\//, "") || "main";
    return { repoUrl, branch };
  });

const listDomainFiles = (
  sourceDir: string,
): Effect.Effect<ReadonlyArray<string>, unknown> =>
  Effect.gen(function* () {
    const entries = yield* Effect.tryPromise(() =>
      fs.readdir(sourceDir, { withFileTypes: true }),
    );

    return entries
      .filter(
        (entry) =>
          entry.isFile() &&
          entry.name.endsWith(".ts") &&
          !entry.name.endsWith(".test.ts") &&
          !entry.name.endsWith(".spec.ts") &&
          !SUPPORT_FILES.has(entry.name),
      )
      .map((entry) => join(sourceDir, entry.name))
      .sort((a, b) => a.localeCompare(b));
  });

const unwrapExpression = (expression: ts.Expression): ts.Expression => {
  let current = expression;
  while (
    ts.isAsExpression(current) ||
    ts.isSatisfiesExpression(current) ||
    ts.isParenthesizedExpression(current)
  ) {
    current = current.expression;
  }
  return current;
};

const getPropertyNameText = (name: ts.PropertyName): string | null => {
  if (
    ts.isIdentifier(name) ||
    ts.isStringLiteral(name) ||
    ts.isNumericLiteral(name)
  ) {
    return name.text;
  }
  return null;
};

const getText = (
  value:
    | string
    | ts.NodeArray<ts.JSDocComment>
    | readonly ts.JSDocComment[]
    | undefined,
): string => {
  if (value === undefined) {
    return "";
  }
  if (typeof value === "string") {
    return value.trim();
  }

  return value
    .map((part) => {
      const text = (part as { text?: unknown }).text;
      return text === undefined ? (part as ts.Node).getText() : String(text);
    })
    .join("")
    .trim();
};

const normalizeJsDocTagText = (value: string): string =>
  value.replace(/^\s*-\s+/, "").trim();

const getNodeJsDoc = (node: ts.Node): ts.JSDoc | null => {
  const docs = (node as ts.Node & { jsDoc?: ts.JSDoc[] }).jsDoc;
  return docs?.[docs.length - 1] ?? null;
};

const getMethodJsDoc = (method: ts.MethodDeclaration): ts.JSDoc | null =>
  getNodeJsDoc(method);

const collectAliasMap = (sourceFile: ts.SourceFile): Map<string, string[]> => {
  const aliasesByTarget = new Map<string, string[]>();

  const visit = (node: ts.Node) => {
    if (ts.isVariableDeclaration(node) && ts.isIdentifier(node.name)) {
      const name = node.name.text;
      const initializer =
        node.initializer === undefined
          ? null
          : unwrapExpression(node.initializer);

      if (
        name.includes("Aliases") &&
        initializer &&
        ts.isObjectLiteralExpression(initializer)
      ) {
        for (const property of initializer.properties) {
          if (!ts.isPropertyAssignment(property)) {
            continue;
          }

          const alias = getPropertyNameText(property.name);
          const targetInitializer = unwrapExpression(property.initializer);
          if (alias === null || !ts.isStringLiteralLike(targetInitializer)) {
            continue;
          }

          const aliases = aliasesByTarget.get(targetInitializer.text) ?? [];
          aliases.push(alias);
          aliasesByTarget.set(targetInitializer.text, aliases);
        }
      }
    }

    ts.forEachChild(node, visit);
  };

  visit(sourceFile);
  return aliasesByTarget;
};

const collectFactoryObjectLiterals = (
  factoryBody: ts.Block,
): ReadonlyArray<ts.ObjectLiteralExpression> => {
  const localObjects = new Map<string, ts.ObjectLiteralExpression>();
  const returnedObjects: ts.ObjectLiteralExpression[] = [];

  for (const statement of factoryBody.statements) {
    if (ts.isVariableStatement(statement)) {
      for (const declaration of statement.declarationList.declarations) {
        if (
          !ts.isIdentifier(declaration.name) ||
          declaration.initializer === undefined
        ) {
          continue;
        }

        const initializer = unwrapExpression(declaration.initializer);
        if (ts.isObjectLiteralExpression(initializer)) {
          localObjects.set(declaration.name.text, initializer);
        }
      }
      continue;
    }

    if (
      !ts.isReturnStatement(statement) ||
      statement.expression === undefined
    ) {
      continue;
    }

    const expression = unwrapExpression(statement.expression);
    if (ts.isObjectLiteralExpression(expression)) {
      returnedObjects.push(expression);
      continue;
    }

    if (ts.isCallExpression(expression)) {
      const firstArg = expression.arguments[0];
      if (firstArg && ts.isIdentifier(firstArg)) {
        const localObject = localObjects.get(firstArg.text);
        if (localObject) {
          returnedObjects.push(localObject);
        }
      }
    }
  }

  return returnedObjects;
};

const collectFactoryMethods = (
  sourceFile: ts.SourceFile,
): ReadonlyArray<ts.MethodDeclaration> => {
  const methods: ts.MethodDeclaration[] = [];

  for (const statement of sourceFile.statements) {
    if (!ts.isVariableStatement(statement)) {
      continue;
    }

    const isExported = statement.modifiers?.some(
      (modifier) => modifier.kind === ts.SyntaxKind.ExportKeyword,
    );
    if (!isExported) {
      continue;
    }

    for (const declaration of statement.declarationList.declarations) {
      if (
        !ts.isIdentifier(declaration.name) ||
        !COMMAND_FACTORY_PATTERN.test(declaration.name.text) ||
        declaration.initializer === undefined
      ) {
        continue;
      }

      const initializer = unwrapExpression(declaration.initializer);
      if (
        !ts.isArrowFunction(initializer) &&
        !ts.isFunctionExpression(initializer)
      ) {
        continue;
      }
      if (!ts.isBlock(initializer.body)) {
        continue;
      }

      for (const objectLiteral of collectFactoryObjectLiterals(
        initializer.body,
      )) {
        for (const property of objectLiteral.properties) {
          if (ts.isMethodDeclaration(property)) {
            methods.push(property);
          }
        }
      }
    }
  }

  return methods;
};

const getParameterName = (parameter: ts.ParameterDeclaration): string => {
  if (ts.isIdentifier(parameter.name)) {
    return parameter.name.text;
  }
  return parameter.name.getText();
};

const getParameterType = (
  checker: ts.TypeChecker,
  parameter: ts.ParameterDeclaration,
  sourceFile: ts.SourceFile,
): string => {
  if (parameter.type) {
    return parameter.type.getText(sourceFile);
  }

  return checker.typeToString(checker.getTypeAtLocation(parameter));
};

const getReturnType = (
  checker: ts.TypeChecker,
  method: ts.MethodDeclaration,
): string => {
  const signature = checker.getSignatureFromDeclaration(method);
  if (!signature) {
    return "unknown";
  }

  return checker.typeToString(signature.getReturnType());
};

const collectJsDocTags = (doc: ts.JSDoc | null): CommandJsDocTag[] => {
  if (!doc?.tags) {
    return [];
  }

  return Array.from(doc.tags).map((tag) => {
    const name = (tag as ts.JSDocTag & { name?: ts.Node }).name;
    return {
      tag: tag.tagName.getText(),
      name:
        name === undefined ? null : name.getText().replace(/^["']|["']$/g, ""),
      text: normalizeJsDocTagText(getText(tag.comment)),
    };
  });
};

const getParamDescriptions = (
  method: ts.MethodDeclaration,
): Map<string, string> => {
  const descriptions = new Map<string, string>();
  const doc = getMethodJsDoc(method);
  if (!doc?.tags) {
    return descriptions;
  }

  for (const tag of doc.tags) {
    if (!ts.isJSDocParameterTag(tag)) {
      continue;
    }
    descriptions.set(
      tag.name.getText(),
      normalizeJsDocTagText(getText(tag.comment)),
    );
  }

  return descriptions;
};

const collectParameters = (
  checker: ts.TypeChecker,
  method: ts.MethodDeclaration,
  sourceFile: ts.SourceFile,
): CommandParameterDoc[] => {
  const descriptions = getParamDescriptions(method);
  const params = method.parameters.map((parameter) => {
    const name = getParameterName(parameter);
    const description = descriptions.get(name);
    if (description === undefined) {
      fail(
        `${sourceFile.fileName}: cmd.${method.name.getText()} missing @param ${name}`,
      );
    }

    const defaultValue = parameter.initializer?.getText(sourceFile) ?? null;
    const optional =
      parameter.questionToken !== undefined || defaultValue !== null;

    return {
      name,
      type: getParameterType(checker, parameter, sourceFile),
      required: !optional,
      rest: parameter.dotDotDotToken !== undefined,
      defaultValue,
      description,
    };
  });

  for (const paramName of descriptions.keys()) {
    if (!params.some((param) => param.name === paramName)) {
      fail(
        `${sourceFile.fileName}: @param ${paramName} does not match a parameter`,
      );
    }
  }

  return params;
};

const getEntityNameIdentifier = (entityName: ts.EntityName): ts.Identifier => {
  if (ts.isIdentifier(entityName)) {
    return entityName;
  }
  return entityName.right;
};

const collectTypeReferenceIdentifiers = (
  node: ts.TypeNode | undefined,
): ts.Identifier[] => {
  if (node === undefined) {
    return [];
  }

  const identifiers: ts.Identifier[] = [];
  const visit = (current: ts.Node) => {
    if (ts.isTypeReferenceNode(current)) {
      const identifier = getEntityNameIdentifier(current.typeName);
      if (!TYPE_REFERENCE_WRAPPERS.has(identifier.text)) {
        identifiers.push(identifier);
      }
    }

    ts.forEachChild(current, visit);
  };

  visit(node);
  return identifiers;
};

const resolveTypeDeclaration = (
  checker: ts.TypeChecker,
  identifier: ts.Identifier,
): {
  readonly name: string;
  readonly declaration: ts.InterfaceDeclaration | ts.TypeAliasDeclaration;
} | null => {
  const symbol = checker.getSymbolAtLocation(identifier);
  if (!symbol) {
    return null;
  }

  const resolvedSymbol =
    (symbol.flags & ts.SymbolFlags.Alias) !== 0
      ? checker.getAliasedSymbol(symbol)
      : symbol;
  const declaration = resolvedSymbol.declarations?.find(
    (
      candidate,
    ): candidate is ts.InterfaceDeclaration | ts.TypeAliasDeclaration =>
      ts.isInterfaceDeclaration(candidate) ||
      ts.isTypeAliasDeclaration(candidate),
  );

  if (!declaration) {
    return null;
  }

  return {
    name: resolvedSymbol.getName(),
    declaration,
  };
};

const isInsideRepo = (repoRoot: string, path: string): boolean => {
  const repoRelativePath = relative(repoRoot, path);
  return !repoRelativePath.startsWith("..") && !isAbsolute(repoRelativePath);
};

const getTypeMembers = (
  declaration: ts.InterfaceDeclaration | ts.TypeAliasDeclaration,
): readonly ts.TypeElement[] => {
  if (ts.isInterfaceDeclaration(declaration)) {
    return declaration.members;
  }

  return ts.isTypeLiteralNode(declaration.type) ? declaration.type.members : [];
};

const getReadonlyModifier = (member: ts.PropertySignature): boolean =>
  member.modifiers?.some(
    (modifier) => modifier.kind === ts.SyntaxKind.ReadonlyKeyword,
  ) ?? false;

const getTypePropertyDocs = (
  checker: ts.TypeChecker,
  declaration: ts.InterfaceDeclaration | ts.TypeAliasDeclaration,
): TypePropertyDoc[] => {
  const sourceFile = declaration.getSourceFile();
  return getTypeMembers(declaration).flatMap((member) => {
    if (!ts.isPropertySignature(member)) {
      return [];
    }

    const name = getPropertyNameText(member.name);
    if (name === null) {
      return [];
    }

    return [
      {
        name,
        type:
          member.type?.getText(sourceFile) ??
          checker.typeToString(checker.getTypeAtLocation(member)),
        required: member.questionToken === undefined,
        readonly: getReadonlyModifier(member),
        description: getText(getNodeJsDoc(member)?.comment),
      },
    ];
  });
};

const getTrailingLineComment = (
  sourceFile: ts.SourceFile,
  node: ts.Node,
): string => {
  const [comment] = ts.getTrailingCommentRanges(sourceFile.text, node.end) ?? [];
  if (
    comment === undefined ||
    comment.kind !== ts.SyntaxKind.SingleLineCommentTrivia
  ) {
    return "";
  }

  const text = sourceFile.text.slice(comment.pos, comment.end).trim();
  return text === "" ? "" : ` ${text}`;
};

const getUnionMemberDefinition = (
  sourceFile: ts.SourceFile,
  member: ts.TypeNode,
  terminated: boolean,
): string => {
  const typeText = member.getText(sourceFile);
  const comment = getTrailingLineComment(sourceFile, member);
  const semicolon = terminated ? ";" : "";
  return `  | ${typeText}${semicolon}${comment}`;
};

const getUnionTypeDefinition = (
  declaration: ts.TypeAliasDeclaration,
  sourceFile: ts.SourceFile,
  union: ts.UnionTypeNode,
): string => {
  const lines = [`type ${declaration.name.text} =`];
  for (const [index, member] of union.types.entries()) {
    lines.push(
      getUnionMemberDefinition(
        sourceFile,
        member,
        index === union.types.length - 1,
      ),
    );
  }
  return lines.join("\n");
};

const getTypeDefinition = (
  declaration: ts.InterfaceDeclaration | ts.TypeAliasDeclaration,
  sourceFile: ts.SourceFile,
): string => {
  if (ts.isInterfaceDeclaration(declaration)) {
    return `interface ${declaration.name.text}`;
  }

  if (ts.isUnionTypeNode(declaration.type)) {
    return getUnionTypeDefinition(declaration, sourceFile, declaration.type);
  }

  return `type ${declaration.name.text} = ${declaration.type.getText(sourceFile)}`;
};

const collectTypeShapeDocs = (
  checker: ts.TypeChecker,
  rootReferences: ReadonlyArray<ts.Identifier>,
  options: CliOptions,
  git: GitSourceInfo | null,
): TypeShapeDoc[] => {
  const pending = [...rootReferences];
  const seen = new Set<string>();
  const docs: TypeShapeDoc[] = [];

  while (pending.length > 0) {
    const reference = pending.shift();
    if (!reference) {
      continue;
    }

    const resolved = resolveTypeDeclaration(checker, reference);
    if (resolved === null || seen.has(resolved.name)) {
      continue;
    }

    const sourceFile = resolved.declaration.getSourceFile();
    if (!isInsideRepo(options.repoRoot, sourceFile.fileName)) {
      continue;
    }

    seen.add(resolved.name);
    const sourceLine =
      sourceFile.getLineAndCharacterOfPosition(
        resolved.declaration.getStart(sourceFile),
      ).line + 1;
    const sourcePath = relative(
      options.repoRoot,
      sourceFile.fileName,
    ).replaceAll("\\", "/");

    docs.push({
      name: resolved.name,
      kind: ts.isInterfaceDeclaration(resolved.declaration)
        ? "interface"
        : "type",
      summary: getText(getNodeJsDoc(resolved.declaration)?.comment),
      definition: getTypeDefinition(resolved.declaration, sourceFile),
      properties: getTypePropertyDocs(checker, resolved.declaration),
      sourcePath,
      sourceLine,
      sourceUrl: buildSourceUrl(
        git,
        options.repoRoot,
        sourceFile.fileName,
        sourceLine,
      ),
    });

    if (ts.isTypeAliasDeclaration(resolved.declaration)) {
      pending.push(
        ...collectTypeReferenceIdentifiers(resolved.declaration.type),
      );
    }

    for (const member of getTypeMembers(resolved.declaration)) {
      if (ts.isPropertySignature(member)) {
        pending.push(...collectTypeReferenceIdentifiers(member.type));
      }
    }
  }

  return docs.sort((a, b) => a.name.localeCompare(b.name));
};

const uniqSorted = (values: ReadonlyArray<string>): string[] =>
  Array.from(new Set(values.filter(Boolean))).sort((a, b) =>
    a.localeCompare(b),
  );

const sameSet = (
  left: ReadonlyArray<string>,
  right: ReadonlyArray<string>,
): boolean => {
  if (left.length !== right.length) {
    return false;
  }

  const leftSet = new Set(left);
  return right.every((value) => leftSet.has(value));
};

const buildSourceUrl = (
  git: GitSourceInfo | null,
  repoRoot: string,
  sourcePath: string,
  sourceLine: number,
): string | null => {
  if (git === null) {
    return null;
  }

  const repoRelativePath = relative(repoRoot, sourcePath).replaceAll("\\", "/");
  return `${git.repoUrl}/blob/${git.branch}/${repoRelativePath}#L${sourceLine}`;
};

const collectCommandDocs = (
  options: CliOptions,
  files: ReadonlyArray<string>,
  git: GitSourceInfo | null,
): DomainDocs[] => {
  const configPath = join(
    options.repoRoot,
    "app/src/renderer/game/tsconfig.json",
  );
  const configFile = ts.readConfigFile(configPath, ts.sys.readFile);
  if (configFile.error) {
    fail(ts.flattenDiagnosticMessageText(configFile.error.messageText, "\n"));
  }

  const parsedConfig = ts.parseJsonConfigFileContent(
    configFile.config,
    ts.sys,
    dirname(configPath),
    {},
    configPath,
  );

  const program = ts.createProgram([...files], parsedConfig.options);
  const checker = program.getTypeChecker();
  const usedCommandNames = new Map<string, string>();

  return files.map((file) => {
    const sourceFile = program.getSourceFile(file);
    if (!sourceFile) {
      fail(`Unable to read source file: ${file}`);
    }

    const domain = basename(file, ".ts");
    const aliasesByTarget = collectAliasMap(sourceFile);
    const methods = collectFactoryMethods(sourceFile);
    const commandDocs: CommandDoc[] = [];
    const typeReferences: ts.Identifier[] = [];
    const methodNames = new Set(
      methods.map((method) => method.name.getText(sourceFile)),
    );

    for (const [target, aliases] of aliasesByTarget.entries()) {
      if (!methodNames.has(target)) {
        fail(
          `${file}: alias map points to missing command ${target} (${aliases.join(", ")})`,
        );
      }
    }

    for (const method of methods) {
      const name = method.name.getText(sourceFile);
      const previousDomain = usedCommandNames.get(name);
      if (previousDomain !== undefined && previousDomain !== domain) {
        fail(`cmd.${name} is exposed by both ${previousDomain} and ${domain}`);
      }
      usedCommandNames.set(name, domain);

      const doc = getMethodJsDoc(method);
      const summary = getText(doc?.comment);
      if (!summary) {
        fail(`${file}: cmd.${name} is missing a JSDoc summary`);
      }

      const tags = collectJsDocTags(doc);
      const jsdocAliases = uniqSorted(
        tags
          .filter((tag) => tag.tag === "alias")
          .flatMap((tag) =>
            tag.text.split(/[,\s]+/).map((value) => value.trim()),
          ),
      );
      const mapAliases = uniqSorted(aliasesByTarget.get(name) ?? []);
      if (
        mapAliases.length > 0 &&
        jsdocAliases.length > 0 &&
        !sameSet(mapAliases, jsdocAliases)
      ) {
        fail(
          `${file}: cmd.${name} @alias tags (${jsdocAliases.join(", ")}) disagree with alias map (${mapAliases.join(", ")})`,
        );
      }

      const aliases = uniqSorted([...mapAliases, ...jsdocAliases]);
      const parameters = collectParameters(checker, method, sourceFile);
      for (const parameter of method.parameters) {
        typeReferences.push(...collectTypeReferenceIdentifiers(parameter.type));
      }
      typeReferences.push(...collectTypeReferenceIdentifiers(method.type));
      const returnType = getReturnType(checker, method);
      const deprecatedTags = tags.filter((tag) => tag.tag === "deprecated");
      const sourceLine =
        sourceFile.getLineAndCharacterOfPosition(method.getStart(sourceFile))
          .line + 1;
      const sourcePath = relative(options.repoRoot, file).replaceAll("\\", "/");
      const signatureParameters = parameters
        .map((param) => {
          const prefix = param.rest ? "..." : "";
          const optional =
            !param.required && param.defaultValue === null ? "?" : "";
          const defaultValue =
            param.defaultValue === null ? "" : ` = ${param.defaultValue}`;
          return `${prefix}${param.name}${optional}: ${param.type}${defaultValue}`;
        })
        .join(", ");
      const callParameters = parameters
        .map((param) => `${param.rest ? "..." : ""}${param.name}`)
        .join(", ");

      commandDocs.push({
        domain,
        name,
        aliases,
        summary,
        call: `cmd.${name}(${callParameters})`,
        signature: `cmd.${name}(${signatureParameters}): ${returnType}`,
        parameters,
        returnType,
        tags,
        examples: tags
          .filter((tag) => tag.tag === "example")
          .map((tag) => tag.text),
        remarks: tags
          .filter((tag) => tag.tag === "remark" || tag.tag === "remarks")
          .map((tag) => tag.text),
        deprecated: deprecatedTags.length > 0,
        deprecationMessages: deprecatedTags.map((tag) => tag.text),
        returns: tags
          .filter((tag) => tag.tag === "returns")
          .map((tag) => tag.text),
        sourcePath,
        sourceLine,
        sourceUrl: buildSourceUrl(git, options.repoRoot, file, sourceLine),
      });
    }

    return {
      domain,
      commands: commandDocs.sort((a, b) => a.name.localeCompare(b.name)),
      types: collectTypeShapeDocs(checker, typeReferences, options, git),
    };
  });
};

const titleCase = (value: string): string =>
  value
    .split(/[_-]+/)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");

const escapeTableCell = (value: string): string =>
  value
    .replaceAll("\\", "\\\\")
    .replaceAll("|", "\\|")
    .replace(/\r?\n/g, "<br>");

const renderCode = (value: string): string => `\`${escapeTableCell(value)}\``;

const anchorSlug = (value: string): string =>
  value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9_-]+/g, "-")
    .replace(/^-+|-+$/g, "");

const typeAnchor = (typeName: string): string => `type-${anchorSlug(typeName)}`;

const commandAnchor = (commandName: string): string =>
  `command-${anchorSlug(commandName)}`;

const buildTypeLinkRegistry = (
  docs: ReadonlyArray<DomainDocs>,
): TypeLinkRegistry => {
  const registry = new Map<string, string>();

  for (const domainDocs of docs) {
    for (const type of domainDocs.types) {
      if (!registry.has(type.name)) {
        registry.set(
          type.name,
          `../${domainDocs.domain}/#${typeAnchor(type.name)}`,
        );
      }
    }
  }

  return registry;
};

const isIdentifierStart = (char: string): boolean => /[A-Za-z_$]/.test(char);

const isIdentifierPart = (char: string): boolean => /[A-Za-z0-9_$]/.test(char);

const renderTypeExpression = (
  type: string,
  typeLinks: TypeLinkRegistry,
): string => {
  const rendered: string[] = [];

  for (let index = 0; index < type.length; ) {
    const char = type[index];

    if (isIdentifierStart(char)) {
      let end = index + 1;
      while (end < type.length && isIdentifierPart(type[end])) {
        end += 1;
      }

      const token = type.slice(index, end);
      const link = typeLinks.get(token);
      rendered.push(
        link === undefined
          ? renderCode(token)
          : `[${renderCode(token)}](${link})`,
      );
      index = end;
      continue;
    }

    if (char === "|") {
      rendered.push("\\|");
    } else if (char === "<") {
      rendered.push("&lt;");
    } else if (char === ">") {
      rendered.push("&gt;");
    } else if (char === "\\") {
      rendered.push("\\\\");
    } else if (char === "\n" || char === "\r") {
      rendered.push("<br>");
    } else {
      rendered.push(char);
    }

    index += 1;
  }

  return rendered.join("");
};

const renderTagSection = (
  lines: string[],
  title: string,
  values: ReadonlyArray<string>,
  codeFence: string | null = null,
) => {
  const filtered = values.filter((value) => value.trim().length > 0);
  if (filtered.length === 0) {
    return;
  }

  lines.push(`**${title}**`, "");
  for (const [index, value] of filtered.entries()) {
    if (codeFence) {
      lines.push(`\`\`\`${codeFence}`, value, "```", "");
      continue;
    }

    lines.push(value);
    if (index < filtered.length - 1) {
      lines.push("");
    }
  }
  lines.push("");
};

const renderTipSection = (lines: string[], values: ReadonlyArray<string>) => {
  const filtered = values.filter((value) => value.trim().length > 0);
  if (filtered.length === 0) {
    return;
  }

  lines.push(":::tip");
  for (const [index, value] of filtered.entries()) {
    if (index > 0) {
      lines.push("");
    }
    for (const line of value.split(/\r?\n/)) {
      lines.push(line);
    }
  }
  lines.push(":::", "");
};

const renderDeprecatedSection = (
  lines: string[],
  command: CommandDoc,
): void => {
  if (!command.deprecated) {
    return;
  }

  const messages = command.deprecationMessages.filter(
    (value) => value.trim().length > 0,
  );

  lines.push(":::caution[Deprecated]");
  if (messages.length === 0) {
    lines.push("This command is deprecated.");
  } else {
    for (const [index, message] of messages.entries()) {
      if (index > 0) {
        lines.push("");
      }
      for (const line of message.split(/\r?\n/)) {
        lines.push(line);
      }
    }
  }
  lines.push(":::", "");
};

const renderAdditionalTags = (
  lines: string[],
  tags: ReadonlyArray<CommandJsDocTag>,
) => {
  if (tags.length === 0) {
    return;
  }

  lines.push(":::note[Metadata]");
  for (const tag of tags) {
    const tagName =
      tag.name === null ? `@${tag.tag}` : `@${tag.tag} ${tag.name}`;
    lines.push(`- ${renderCode(tagName)}: ${tag.text}`);
  }
  lines.push(":::", "");
};

const renderReferenceIndex = (lines: string[], domainDocs: DomainDocs) => {
  const hasAliases = domainDocs.commands.some(
    (command) => command.aliases.length > 0,
  );
  const hasDeprecated = domainDocs.commands.some(
    (command) => command.deprecated,
  );
  const headers = ["Command", "Summary"];
  const alignments = ["---", "---"];
  if (hasDeprecated) {
    headers.push("Status");
    alignments.push("---");
  }
  if (hasAliases) {
    headers.push("Aliases");
    alignments.push("---");
  }

  lines.push("## Reference Index", "", "### Commands", "");
  lines.push(`| ${headers.join(" | ")} |`, `| ${alignments.join(" | ")} |`);

  for (const command of domainDocs.commands) {
    const commandLink = `[${renderCode(`cmd.${command.name}`)}](#${commandAnchor(command.name)})`;
    const summary = escapeTableCell(command.summary);
    const cells = [commandLink, summary];
    if (hasDeprecated) {
      cells.push(command.deprecated ? "Deprecated" : "");
    }
    if (hasAliases) {
      const aliases = command.aliases
        .map((alias) => renderCode(`cmd.${alias}`))
        .join(", ");
      cells.push(aliases);
    }

    lines.push(`| ${cells.join(" | ")} |`);
  }

  lines.push("");

  if (domainDocs.types.length === 0) {
    return;
  }

  lines.push("### Referenced Types", "");
  lines.push("| Type | Kind | Summary |", "| --- | --- | --- |");

  for (const type of domainDocs.types) {
    const typeLink = `[${renderCode(type.name)}](#${typeAnchor(type.name)})`;
    lines.push(
      `| ${typeLink} | ${type.kind} | ${escapeTableCell(type.summary)} |`,
    );
  }

  lines.push("");
};

const renderDomainMarkdown = (
  domainDocs: DomainDocs,
  typeLinks: TypeLinkRegistry,
): string => {
  const title = titleCase(domainDocs.domain);
  const pageTitle = `${title} Commands`;
  const lines: string[] = [
    "---",
    `title: ${pageTitle}`,
    `description: Generated vexed ${domainDocs.domain} command reference.`,
    "sidebar:",
    `  label: ${title}`,
    "tableOfContents:",
    "  minHeadingLevel: 2",
    "  maxHeadingLevel: 2",
    "---",
    "",
    GENERATED_HEADER,
    "",
  ];

  renderReferenceIndex(lines, domainDocs);

  lines.push("## Commands", "");

  for (const command of domainDocs.commands) {
    lines.push(`<a id="${commandAnchor(command.name)}"></a>`, "");
    lines.push(`### \`${command.call}\``, "", command.summary, "");
    renderDeprecatedSection(lines, command);
    renderTipSection(lines, command.remarks);

    const sourceText = `**Source:** \`${command.sourcePath}:${command.sourceLine}\``;
    lines.push(
      command.sourceUrl
        ? `${sourceText} · [View implementation/source](${command.sourceUrl})`
        : sourceText,
      "",
    );

    lines.push("```ts", command.signature, "```", "");

    if (command.parameters.length > 0) {
      lines.push(
        "| Name | Type | Required | Default | Description |",
        "| --- | --- | --- | --- | --- |",
      );
      for (const param of command.parameters) {
        lines.push(
          `| ${renderCode(param.name)} | ${renderTypeExpression(param.type, typeLinks)} | ${
            param.required ? "yes" : "no"
          } | ${param.defaultValue === null ? "" : renderCode(param.defaultValue)} | ${escapeTableCell(param.description)} |`,
        );
      }
      lines.push("");
    }

    if (command.aliases.length > 0) {
      lines.push(
        "**Aliases**",
        "",
        command.aliases.map((alias) => `\`cmd.${alias}\``).join(", "),
        "",
      );
    }

    renderTagSection(lines, "Examples", command.examples, "js");
    renderTagSection(lines, "Returns", command.returns);

    const additionalTags = command.tags.filter(
      (tag) =>
        ![
          "alias",
          "param",
          "example",
          "remark",
          "remarks",
          "deprecated",
          "returns",
        ].includes(tag.tag),
    );
    renderAdditionalTags(lines, additionalTags);
  }

  if (domainDocs.types.length > 0) {
    lines.push("## Referenced Types", "");

    for (const type of domainDocs.types) {
      lines.push(`<a id="${typeAnchor(type.name)}"></a>`, "");
      lines.push(`### \`${type.name}\``, "");

      if (type.summary) {
        lines.push(type.summary, "");
      }

      const sourceText = `**Source:** \`${type.sourcePath}:${type.sourceLine}\``;
      lines.push(
        type.sourceUrl
          ? `${sourceText} · [View implementation/source](${type.sourceUrl})`
          : sourceText,
        "",
      );

      lines.push("```ts", type.definition, "```", "");

      if (type.properties.length > 0) {
        lines.push(
          "| Name | Type | Required | Readonly | Description |",
          "| --- | --- | --- | --- | --- |",
        );

        for (const property of type.properties) {
          lines.push(
            `| ${renderCode(property.name)} | ${renderTypeExpression(property.type, typeLinks)} | ${
              property.required ? "yes" : "no"
            } | ${property.readonly ? "yes" : "no"} | ${escapeTableCell(property.description)} |`,
          );
        }

        lines.push("");
      }
    }
  }

  return `${lines
    .join("\n")
    .replace(/\n{3,}/g, "\n\n")
    .trimEnd()}\n`;
};

const renderFiles = (
  options: CliOptions,
  docs: ReadonlyArray<DomainDocs>,
): ReadonlyArray<RenderedFile> => {
  const typeLinks = buildTypeLinkRegistry(docs);
  return docs.map((domainDocs) => ({
    path: join(options.outputDir, `${domainDocs.domain}.md`),
    content: renderDomainMarkdown(domainDocs, typeLinks),
  }));
};

const writeGeneratedDocs = (
  outputDir: string,
  files: ReadonlyArray<RenderedFile>,
): Effect.Effect<void, unknown> =>
  Effect.gen(function* () {
    yield* Effect.tryPromise(() => fs.mkdir(outputDir, { recursive: true }));

    const expected = new Set(files.map((file) => basename(file.path)));
    const existing = yield* Effect.tryPromise(() =>
      fs.readdir(outputDir, { withFileTypes: true }),
    ).pipe(Effect.catch(() => Effect.succeed([])));

    for (const entry of existing) {
      if (
        entry.isFile() &&
        entry.name.endsWith(".md") &&
        !expected.has(entry.name)
      ) {
        yield* Effect.tryPromise(() => fs.unlink(join(outputDir, entry.name)));
      }
    }

    for (const file of files) {
      const current = yield* Effect.tryPromise(() =>
        fs.readFile(file.path, "utf8"),
      ).pipe(Effect.catch(() => Effect.succeed(null)));
      if (current === file.content) {
        continue;
      }

      yield* Effect.tryPromise(() =>
        fs.writeFile(file.path, file.content, "utf8"),
      );
    }
  });

const main = (options: CliOptions): Effect.Effect<void, unknown> =>
  Effect.gen(function* () {
    const files = yield* listDomainFiles(options.sourceDir);
    const git = options.includeSourceLinks
      ? yield* getGitSourceInfo(options.repoRoot)
      : null;
    const docs = collectCommandDocs(options, files, git);
    const renderedFiles = renderFiles(options, docs);

    yield* writeGeneratedDocs(options.outputDir, renderedFiles);
    yield* Console.log(
      `Generated ${renderedFiles.length} command doc files in ${relative(
        options.repoRoot,
        options.outputDir,
      )}`,
    );
  });

if (
  process.argv[1] &&
  import.meta.url === pathToFileURL(process.argv[1]).href
) {
  const options = parseCliOptions(process.argv.slice(2), DEFAULT_REPO_ROOT);

  main(options).pipe(
    Effect.catch((error) =>
      Effect.gen(function* () {
        yield* Console.error(
          error instanceof Error ? error.message : String(error),
        );
        yield* Effect.sync(() => {
          process.exitCode = 1;
        });
      }),
    ),
    NodeRuntime.runMain,
  );
}
