import { execFile } from "node:child_process";
import fs from "node:fs/promises";
import { dirname, isAbsolute, join, relative, resolve } from "node:path";
import { promisify } from "node:util";
import { fileURLToPath, pathToFileURL } from "node:url";

import * as NodeRuntime from "@effect/platform-node/NodeRuntime";
import { Console, Effect } from "effect";
import ts from "typescript";
import {
  Application,
  type DeclarationReflection,
  type ProjectReflection,
  type Reflection,
  ReflectionKind,
  type SignatureReflection,
  type SomeType,
} from "typedoc";

const execFileAsync = promisify(execFile);

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const DEFAULT_REPO_ROOT = join(SCRIPT_DIR, "..");
const DEFAULT_SOURCE_FILE =
  "app/src/renderer/windows/game/scripting/ScriptApi.ts";
const DEFAULT_OUTPUT_DIR = "docs/src/content/docs/scripting";
const LEGACY_OUTPUT_DIR = "docs/src/content/docs/script-commands";
const SOURCE_LINKS_OUTPUT = "docs/src/generated/script-source-links.ts";
const TYPE_PREVIEWS_OUTPUT = "docs/public/script-type-previews.json";
const APP_TSCONFIG = "app/tsconfig.json";
const GAME_API_ENTRYPOINT = "packages/game/src/index.ts";
const COLLECTION_API_ENTRYPOINT = "packages/collection/src/index.ts";
const SOURCE_REF_ENV = "DOCGEN_SOURCE_REF";
const DEFAULT_SOURCE_REF = "dev";
const GENERATED_HEADER =
  "<!-- Generated by pnpm run docgen. Do not edit directly. -->";

const TYPE_REFERENCE_WRAPPERS = new Set([
  "Array",
  "Effect",
  "Generator",
  "Omit",
  "Partial",
  "Pick",
  "Readonly",
  "ReadonlyArray",
  "Record",
  "Required",
]);

const BUILTIN_TYPE_NAMES = new Set([
  "AbortSignal",
  "Boolean",
  "Date",
  "Duration",
  "Error",
  "Function",
  "Number",
  "Object",
  "Option",
  "Promise",
  "String",
  "any",
  "boolean",
  "false",
  "never",
  "null",
  "number",
  "readonly",
  "string",
  "true",
  "undefined",
  "unknown",
  "void",
]);

type CliOptions = {
  readonly repoRoot: string;
  readonly sourceFile: string;
  readonly outputDir: string;
  readonly includeSourceLinks: boolean;
};

type GitSourceInfo = {
  readonly repoUrl: string;
  readonly ref: string;
};

type SourceInfo = {
  readonly sourcePath: string;
  readonly sourceLine: number;
  readonly sourceUrl: string | null;
};

type ParameterDoc = {
  readonly name: string;
  readonly type: string;
  readonly required: boolean;
  readonly rest: boolean;
  readonly description: string;
};

type ReturnDoc = {
  readonly raw: string;
  readonly result: string | null;
  readonly error: string | null;
};

type MemberDoc = SourceInfo & {
  readonly path: string;
  readonly name: string;
  readonly kind: "method" | "effect" | "value";
  readonly summary: string;
  readonly signature: string;
  readonly parameters: readonly ParameterDoc[];
  readonly returnDoc: ReturnDoc;
};

type TypeMemberDoc = SourceInfo & {
  readonly name: string;
  readonly type: string;
  readonly summary: string;
  readonly readonly: boolean;
  readonly optional: boolean;
  readonly inheritedFrom: string | null;
};

type TypeMethodDoc = SourceInfo & {
  readonly name: string;
  readonly signature: string;
  readonly summary: string;
  readonly inheritedFrom: string | null;
};

type ReferencedTypeDoc = SourceInfo & {
  readonly name: string;
  readonly slug: string;
  readonly kind: string;
  readonly summary: string;
  readonly definition: string;
  readonly properties: readonly TypeMemberDoc[];
  readonly methods: readonly TypeMethodDoc[];
};

type ApiGroup = {
  readonly id: string;
  readonly title: string;
  readonly label: string;
  readonly description: string;
  readonly summary: string;
  readonly members: readonly MemberDoc[];
  readonly typeReferences: readonly string[];
};

type ApiNamespace = {
  readonly name: string;
  readonly slug: string;
  readonly href: string;
  readonly sourceType: string;
};

type TypeLink = {
  readonly href: string;
  readonly slug: string;
};

type RenderedFile = {
  readonly path: string;
  readonly content: string;
};

class DocgenError extends Error {
  override readonly name = "DocgenError";
}

const fail = (message: string): never => {
  throw new DocgenError(message);
};

const parseCliOptions = (
  args: ReadonlyArray<string>,
  repoRoot: string,
): CliOptions => {
  let source = DEFAULT_SOURCE_FILE;
  let out = DEFAULT_OUTPUT_DIR;
  let includeSourceLinks = true;

  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index] ?? fail(`Unable to read argument at ${index}`);
    if (arg === "--") {
      continue;
    }
    if (arg === "--include-source-links") {
      includeSourceLinks = true;
      continue;
    }
    if (arg === "--no-source-links") {
      includeSourceLinks = false;
      continue;
    }
    if (arg === "--source") {
      source = args[index + 1] ?? fail("--source requires a path");
      index += 1;
      continue;
    }
    if (arg.startsWith("--source=")) {
      source = arg.slice("--source=".length);
      continue;
    }
    if (arg === "--out") {
      out = args[index + 1] ?? fail("--out requires a path");
      index += 1;
      continue;
    }
    if (arg.startsWith("--out=")) {
      out = arg.slice("--out=".length);
      continue;
    }
    fail(`Unknown argument: ${arg}`);
  }

  return {
    repoRoot,
    sourceFile: isAbsolute(source) ? source : resolve(repoRoot, source),
    outputDir: isAbsolute(out) ? out : resolve(repoRoot, out),
    includeSourceLinks,
  };
};

const normalizeGitRemoteUrl = (rawUrl: string): string | null => {
  const url = rawUrl.trim().replace(/\.git$/, "");
  if (url.startsWith("https://")) {
    return url;
  }
  if (url.startsWith("http://")) {
    return `https://${url.slice("http://".length)}`;
  }

  const sshMatch = url.match(/^git@([^:]+):(.+)$/);
  if (sshMatch) {
    return `https://${sshMatch[1]}/${sshMatch[2]}`;
  }

  return null;
};

const getGitSourceInfo = (
  repoRoot: string,
): Effect.Effect<GitSourceInfo | null> =>
  Effect.gen(function* () {
    const remoteUrl = yield* Effect.tryPromise(async () => {
      const result = await execFileAsync(
        "git",
        ["remote", "get-url", "origin"],
        { cwd: repoRoot },
      );
      return result.stdout;
    }).pipe(Effect.catch(() => Effect.succeed(null)));

    if (remoteUrl === null) {
      return null;
    }

    const repoUrl = normalizeGitRemoteUrl(remoteUrl);
    if (repoUrl === null) {
      return null;
    }

    const sourceRef = process.env[SOURCE_REF_ENV]?.trim();
    if (sourceRef) {
      return { repoUrl, ref: sourceRef };
    }

    return { repoUrl, ref: DEFAULT_SOURCE_REF };
  });

const buildSourceUrl = (
  git: GitSourceInfo | null,
  repoRoot: string,
  sourcePath: string,
  sourceLine: number,
): string | null => {
  if (git === null) {
    return null;
  }

  const repoRelativePath = relative(repoRoot, sourcePath).replaceAll("\\", "/");
  return `${git.repoUrl}/blob/${git.ref}/${repoRelativePath}#L${sourceLine}`;
};

const getSourceInfo = (
  options: CliOptions,
  git: GitSourceInfo | null,
  node: ts.Node,
): SourceInfo => {
  const sourceFile = node.getSourceFile();
  const sourceLine =
    sourceFile.getLineAndCharacterOfPosition(node.getStart(sourceFile)).line +
    1;

  return {
    sourcePath: relative(options.repoRoot, sourceFile.fileName).replaceAll(
      "\\",
      "/",
    ),
    sourceLine,
    sourceUrl: buildSourceUrl(
      git,
      options.repoRoot,
      sourceFile.fileName,
      sourceLine,
    ),
  };
};

const titleCase = (value: string): string =>
  value
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .split(/[\s_-]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");

const kebabCase = (value: string): string =>
  value
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/[^A-Za-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .toLowerCase();

const anchorSlug = (value: string): string =>
  value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9_-]+/g, "-")
    .replace(/^-+|-+$/g, "");

const memberAnchor = (path: string): string => `member-${anchorSlug(path)}`;

const escapeTableCell = (value: string): string =>
  value
    .replaceAll("\\", "\\\\")
    .replaceAll("|", "\\|")
    .replace(/\r?\n/g, "<br>");

const escapeHtml = (value: string): string =>
  value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");

const renderCode = (value: string): string => `\`${escapeTableCell(value)}\``;
const renderHtmlCode = (value: string): string =>
  `<code>${escapeHtml(value)}</code>`;
const lucideCheckIcon =
  '<span class="required-mark" role="img" aria-label="Required"></span>';

const renderBooleanMark = (value: boolean): string =>
  value ? lucideCheckIcon : "";

const getText = (
  value:
    | string
    | ts.NodeArray<ts.JSDocComment>
    | readonly ts.JSDocComment[]
    | undefined,
): string => {
  if (value === undefined) {
    return "";
  }
  if (typeof value === "string") {
    return value.trim();
  }

  return value
    .map((part) => {
      const text = (part as { text?: unknown }).text;
      return text === undefined ? (part as ts.Node).getText() : String(text);
    })
    .join("")
    .trim();
};

const getNodeJsDoc = (node: ts.Node): ts.JSDoc | null => {
  const docs = (node as ts.Node & { jsDoc?: ts.JSDoc[] }).jsDoc;
  return docs?.[docs.length - 1] ?? null;
};

const getSummary = (node: ts.Node): string =>
  getText(getNodeJsDoc(node)?.comment);

const getParamDescriptions = (
  node: ts.SignatureDeclaration,
): ReadonlyMap<string, string> => {
  const descriptions = new Map<string, string>();
  const doc = getNodeJsDoc(node);
  if (!doc?.tags) {
    return descriptions;
  }

  for (const tag of doc.tags) {
    if (!ts.isJSDocParameterTag(tag)) {
      continue;
    }
    descriptions.set(
      tag.name.getText(),
      getText(tag.comment).replace(/^\s*-\s+/, ""),
    );
  }

  return descriptions;
};

const createProgram = (repoRoot: string): ts.Program => {
  const configPath = resolve(repoRoot, APP_TSCONFIG);
  const readResult = ts.readConfigFile(configPath, ts.sys.readFile);
  if (readResult.error) {
    fail(ts.flattenDiagnosticMessageText(readResult.error.messageText, "\n"));
  }

  const parsed = ts.parseJsonConfigFileContent(
    readResult.config,
    ts.sys,
    dirname(configPath),
  );

  if (parsed.errors.length > 0) {
    fail(
      parsed.errors
        .map((error) =>
          ts.flattenDiagnosticMessageText(error.messageText, "\n"),
        )
        .join("\n"),
    );
  }

  return ts.createProgram({
    rootNames: parsed.fileNames,
    options: parsed.options,
  });
};

const isInsideRepo = (repoRoot: string, fileName: string): boolean => {
  const rel = relative(repoRoot, fileName);
  return rel === "" || (!rel.startsWith("..") && !isAbsolute(rel));
};

const buildDeclarationMap = (
  program: ts.Program,
): ReadonlyMap<string, ts.InterfaceDeclaration | ts.TypeAliasDeclaration> => {
  const declarations = new Map<
    string,
    ts.InterfaceDeclaration | ts.TypeAliasDeclaration
  >();

  const visit = (node: ts.Node): void => {
    if (ts.isInterfaceDeclaration(node) || ts.isTypeAliasDeclaration(node)) {
      declarations.set(node.name.text, node);
    }
    ts.forEachChild(node, visit);
  };

  for (const sourceFile of program.getSourceFiles()) {
    if (sourceFile.fileName.includes("/node_modules/")) {
      continue;
    }
    visit(sourceFile);
  }

  return declarations;
};

const getInterface = (
  declarations: ReadonlyMap<
    string,
    ts.InterfaceDeclaration | ts.TypeAliasDeclaration
  >,
  name: string,
  seen = new Set<string>(),
): ts.InterfaceDeclaration => {
  if (seen.has(name)) {
    fail(`Unable to resolve circular interface alias ${name}`);
  }

  const declaration =
    declarations.get(name) ?? fail(`Unable to find interface ${name}`);

  if (ts.isInterfaceDeclaration(declaration)) {
    return declaration;
  }

  const reference = parseTypeReference(declaration.type);
  if (reference) {
    const nextSeen = new Set(seen);
    nextSeen.add(name);
    if (reference.name === "Omit" && reference.args.length >= 2) {
      const target = parseTypeReference(reference.args[0]);
      if (target) {
        return omitInterfaceMembers(
          getInterface(declarations, target.name, nextSeen),
          literalTypeNames(reference.args[1]),
        );
      }
    }
    return getInterface(declarations, reference.name, nextSeen);
  }

  return fail(`Unable to find interface ${name}`);
};

const literalTypeNames = (node: ts.TypeNode | undefined): Set<string> => {
  const names = new Set<string>();
  if (node === undefined) {
    return names;
  }

  const visit = (current: ts.TypeNode): void => {
    if (
      ts.isLiteralTypeNode(current) &&
      ts.isStringLiteralLike(current.literal)
    ) {
      names.add(current.literal.text);
      return;
    }

    if (ts.isUnionTypeNode(current)) {
      for (const child of current.types) {
        visit(child);
      }
    }
  };

  visit(node);
  return names;
};

const omitInterfaceMembers = (
  declaration: ts.InterfaceDeclaration,
  omitted: ReadonlySet<string>,
): ts.InterfaceDeclaration => ({
  ...declaration,
  members: ts.factory.createNodeArray(
    declaration.members.filter((member) => {
      if (!ts.isMethodSignature(member) && !ts.isPropertySignature(member)) {
        return true;
      }

      const name = getPropertyName(member.name);
      return name === null || !omitted.has(name);
    }),
  ),
});

const getPropertyName = (name: ts.PropertyName): string | null => {
  if (
    ts.isIdentifier(name) ||
    ts.isStringLiteral(name) ||
    ts.isNumericLiteral(name)
  ) {
    return name.text;
  }
  return null;
};

const getTypeNameText = (name: ts.EntityName): string => {
  if (ts.isIdentifier(name)) {
    return name.text;
  }
  return getTypeNameText(name.right);
};

const typeText = (
  node: ts.TypeNode | undefined,
  sourceFile: ts.SourceFile,
): string => (node === undefined ? "unknown" : node.getText(sourceFile));

const splitTopLevel = (value: string, delimiter = ","): string[] => {
  const parts: string[] = [];
  let depth = 0;
  let start = 0;

  for (let index = 0; index < value.length; index += 1) {
    const char = value[index];
    if (char === "<" || char === "(" || char === "[" || char === "{") {
      depth += 1;
    } else if (char === ">" || char === ")" || char === "]" || char === "}") {
      depth = Math.max(0, depth - 1);
    } else if (char === delimiter && depth === 0) {
      parts.push(value.slice(start, index).trim());
      start = index + 1;
    }
  }

  parts.push(value.slice(start).trim());
  return parts;
};

const parseTypeReference = (
  node: ts.TypeNode | undefined,
): { readonly name: string; readonly args: readonly ts.TypeNode[] } | null => {
  if (!node || !ts.isTypeReferenceNode(node)) {
    return null;
  }

  return {
    name: getTypeNameText(node.typeName),
    args: Array.from(node.typeArguments ?? []),
  };
};

const isEffectTypeNode = (node: ts.TypeNode | undefined): boolean => {
  const reference = parseTypeReference(node);
  if (!reference) {
    return false;
  }
  return reference.name === "Effect" && reference.args.length >= 1;
};

const parseEffectValueShape = (
  node: ts.TypeNode | undefined,
): string | null => {
  const reference = parseTypeReference(node);
  if (
    !reference ||
    reference.name !== "EffectValue" ||
    reference.args.length !== 1
  ) {
    return null;
  }

  const target = parseTypeReference(reference.args[0]);
  return target?.name ?? null;
};

const formatType = (
  checker: ts.TypeChecker,
  node: ts.TypeNode | undefined,
): string => {
  if (node === undefined) {
    return "unknown";
  }

  const type = checker.getTypeAtLocation(node);
  return checker.typeToString(
    type,
    node,
    ts.TypeFormatFlags.NoTruncation |
      ts.TypeFormatFlags.UseSingleQuotesForStringLiteralType,
  );
};

const parseEffectReturn = (
  raw: string,
  node: ts.TypeNode | undefined,
  sourceFile: ts.SourceFile,
): ReturnDoc => {
  const reference = parseTypeReference(node);
  if (reference?.name === "Effect" && reference.args.length >= 1) {
    return {
      raw,
      result: typeText(reference.args[0], sourceFile),
      error:
        reference.args.length >= 2
          ? typeText(reference.args[1], sourceFile)
          : "never",
    };
  }

  if (reference?.name === "BridgeEffect" && reference.args.length >= 1) {
    return {
      raw,
      result: typeText(reference.args[0], sourceFile),
      error: "BridgeError",
    };
  }

  if (reference?.name === "ArmyEffect" && reference.args.length >= 1) {
    const extraError =
      reference.args.length >= 2
        ? `${typeText(reference.args[1], sourceFile)} | `
        : "";
    return {
      raw,
      result: typeText(reference.args[0], sourceFile),
      error: `${extraError}ArmyError | BridgeError`,
    };
  }

  const effectMatch = /^(?:Effect\.)?Effect<(.+)>$/.exec(raw);
  if (effectMatch?.[1]) {
    const args = splitTopLevel(effectMatch[1]);
    return {
      raw,
      result: args[0] ?? "unknown",
      error: args[1] ?? "never",
    };
  }

  return { raw, result: null, error: null };
};

const getReturnDoc = (
  checker: ts.TypeChecker,
  node: ts.SignatureDeclaration,
): ReturnDoc => {
  const sourceFile = node.getSourceFile();
  const raw =
    node.type === undefined
      ? checker.typeToString(
          checker.getSignatureFromDeclaration(node)?.getReturnType() ??
            checker.getAnyType(),
          node,
          ts.TypeFormatFlags.NoTruncation,
        )
      : formatType(checker, node.type);

  return parseEffectReturn(raw, node.type, sourceFile);
};

const getParameterDocs = (
  checker: ts.TypeChecker,
  node: ts.SignatureDeclaration,
): ParameterDoc[] => {
  const descriptions = getParamDescriptions(node);
  const sourceFile = node.getSourceFile();

  return node.parameters.map((parameter) => {
    const name = parameter.name.getText(sourceFile);
    return {
      name,
      type: formatType(checker, parameter.type),
      required:
        parameter.questionToken === undefined &&
        parameter.initializer === undefined &&
        parameter.dotDotDotToken === undefined,
      rest: parameter.dotDotDotToken !== undefined,
      description: descriptions.get(name) ?? "",
    };
  });
};

const methodSignature = (
  path: string,
  parameters: readonly ParameterDoc[],
  returnDoc: ReturnDoc,
): string =>
  `${path}(${parameters
    .map(
      (parameter) =>
        `${parameter.rest ? "..." : ""}${parameter.name}${
          parameter.required ? "" : "?"
        }: ${parameter.type}`,
    )
    .join(", ")}): ${returnDoc.raw}`;

const collectTypeReferences = (
  node: ts.Node | undefined,
  output: Set<string>,
): void => {
  if (node === undefined) {
    return;
  }

  if (ts.isTypeReferenceNode(node)) {
    const name = getTypeNameText(node.typeName);
    if (!TYPE_REFERENCE_WRAPPERS.has(name) && !BUILTIN_TYPE_NAMES.has(name)) {
      output.add(name);
    }
  }

  ts.forEachChild(node, (child) => collectTypeReferences(child, output));
};

const resolveNestedInterface = (
  declarations: ReadonlyMap<
    string,
    ts.InterfaceDeclaration | ts.TypeAliasDeclaration
  >,
  node: ts.TypeNode | undefined,
): ts.InterfaceDeclaration | null => {
  const reference = parseTypeReference(node);
  if (!reference) {
    return null;
  }

  const declaration = declarations.get(reference.name);
  return declaration && ts.isInterfaceDeclaration(declaration)
    ? declaration
    : null;
};

const collectMembersFromInterface = (
  checker: ts.TypeChecker,
  declarations: ReadonlyMap<
    string,
    ts.InterfaceDeclaration | ts.TypeAliasDeclaration
  >,
  options: CliOptions,
  git: GitSourceInfo | null,
  declaration: ts.InterfaceDeclaration,
  basePath: string,
  typeReferences: Set<string>,
  seenInterfaces = new Set<string>(),
): MemberDoc[] => {
  if (seenInterfaces.has(declaration.name.text)) {
    return [];
  }

  const nextSeen = new Set(seenInterfaces);
  nextSeen.add(declaration.name.text);
  const docs: MemberDoc[] = [];

  for (const member of declaration.members) {
    if (ts.isMethodSignature(member)) {
      const name = getPropertyName(member.name);
      if (name === null) {
        continue;
      }

      const parameters = getParameterDocs(checker, member);
      const returnDoc = getReturnDoc(checker, member);
      for (const parameter of member.parameters) {
        collectTypeReferences(parameter.type, typeReferences);
      }
      collectTypeReferences(member.type, typeReferences);

      const path = `${basePath}.${name}`;
      docs.push({
        path,
        name,
        kind: "method",
        summary: getSummary(member),
        signature: methodSignature(path, parameters, returnDoc),
        parameters,
        returnDoc,
        ...getSourceInfo(options, git, member),
      });
      continue;
    }

    if (!ts.isPropertySignature(member)) {
      continue;
    }

    const name = getPropertyName(member.name);
    if (name === null) {
      continue;
    }

    const nestedInterface = resolveNestedInterface(declarations, member.type);
    if (nestedInterface !== null && !isEffectTypeNode(member.type)) {
      docs.push(
        ...collectMembersFromInterface(
          checker,
          declarations,
          options,
          git,
          nestedInterface,
          `${basePath}.${name}`,
          typeReferences,
          nextSeen,
        ),
      );
      continue;
    }

    if (member.type && ts.isFunctionTypeNode(member.type)) {
      const parameters = getParameterDocs(checker, member.type);
      const returnDoc = getReturnDoc(checker, member.type);
      for (const parameter of member.type.parameters) {
        collectTypeReferences(parameter.type, typeReferences);
      }
      collectTypeReferences(member.type.type, typeReferences);

      const path = `${basePath}.${name}`;
      docs.push({
        path,
        name,
        kind: "method",
        summary: getSummary(member),
        signature: methodSignature(path, parameters, returnDoc),
        parameters,
        returnDoc,
        ...getSourceInfo(options, git, member),
      });
      continue;
    }

    collectTypeReferences(member.type, typeReferences);

    const returnDoc = parseEffectReturn(
      formatType(checker, member.type),
      member.type,
      member.getSourceFile(),
    );
    docs.push({
      path: `${basePath}.${name}`,
      name,
      kind: returnDoc.result === null ? "value" : "effect",
      summary: getSummary(member),
      signature: `${basePath}.${name}: ${returnDoc.raw}`,
      parameters: [],
      returnDoc,
      ...getSourceInfo(options, git, member),
    });
  }

  return docs.sort((a, b) => a.path.localeCompare(b.path));
};

const collectScriptPacketMembers = (
  checker: ts.TypeChecker,
  declarations: ReadonlyMap<
    string,
    ts.InterfaceDeclaration | ts.TypeAliasDeclaration
  >,
  options: CliOptions,
  git: GitSourceInfo | null,
  typeReferences: Set<string>,
): MemberDoc[] => {
  const packetShape = getInterface(declarations, "PacketShape");
  const packetApi = getInterface(declarations, "ScriptPacketApi");
  const exposedSendMethods = new Set(["sendClient", "sendServer"]);

  return [
    ...collectMembersFromInterface(
      checker,
      declarations,
      options,
      git,
      {
        ...packetShape,
        members: ts.factory.createNodeArray(
          packetShape.members.filter(
            (member) =>
              ts.isMethodSignature(member) &&
              exposedSendMethods.has(getPropertyName(member.name) ?? ""),
          ),
        ),
      } as ts.InterfaceDeclaration,
      "api.packet",
      typeReferences,
    ),
    ...collectMembersFromInterface(
      checker,
      declarations,
      options,
      git,
      packetApi,
      "api.packet",
      typeReferences,
    ),
  ].sort((a, b) => a.path.localeCompare(b.path));
};

const getProperty = (
  declaration: ts.InterfaceDeclaration,
  name: string,
): ts.PropertySignature | null => {
  for (const member of declaration.members) {
    if (
      ts.isPropertySignature(member) &&
      getPropertyName(member.name) === name
    ) {
      return member;
    }
  }
  return null;
};

const getMethod = (
  declaration: ts.InterfaceDeclaration,
  name: string,
): ts.MethodSignature | null => {
  for (const member of declaration.members) {
    if (ts.isMethodSignature(member) && getPropertyName(member.name) === name) {
      return member;
    }
  }
  return null;
};

const collectApiGroups = (
  checker: ts.TypeChecker,
  declarations: ReadonlyMap<
    string,
    ts.InterfaceDeclaration | ts.TypeAliasDeclaration
  >,
  options: CliOptions,
  git: GitSourceInfo | null,
): {
  readonly runtimeHelpers: readonly MemberDoc[];
  readonly namespaces: readonly ApiNamespace[];
  readonly groups: readonly ApiGroup[];
  readonly typeReferences: readonly string[];
} => {
  const scriptApi = getInterface(declarations, "ScriptApi");
  const scriptContext = getInterface(declarations, "ScriptContext");
  const scriptRuntimeApi = getInterface(declarations, "ScriptRuntimeApi");
  const helperTypeReferences = new Set<string>();
  const groups: ApiGroup[] = [];

  const runtimeHelpers = [
    ...["log", "stop", "sleep"].flatMap((name) => {
      const method = getMethod(scriptRuntimeApi, name);
      if (!method) {
        return [];
      }
      const parameters = getParameterDocs(checker, method);
      const returnDoc = getReturnDoc(checker, method);
      for (const parameter of method.parameters) {
        collectTypeReferences(parameter.type, helperTypeReferences);
      }
      collectTypeReferences(method.type, helperTypeReferences);
      const path = `script.${name}`;
      return [
        {
          path,
          name,
          kind: "method" as const,
          summary: getSummary(method),
          signature: methodSignature(path, parameters, returnDoc),
          parameters,
          returnDoc,
          ...getSourceInfo(options, git, method),
        },
      ];
    }),
    ...["signal"].flatMap((name) => {
      const property = getProperty(scriptRuntimeApi, name);
      if (!property) {
        return [];
      }
      collectTypeReferences(property.type, helperTypeReferences);
      const returnDoc = parseEffectReturn(
        formatType(checker, property.type),
        property.type,
        property.getSourceFile(),
      );
      return [
        {
          path: `script.${name}`,
          name,
          kind: "value" as const,
          summary: getSummary(property),
          signature: `script.${name}: ${returnDoc.raw}`,
          parameters: [],
          returnDoc,
          ...getSourceInfo(options, git, property),
        },
      ];
    }),
  ].sort((a, b) => a.path.localeCompare(b.path));

  const namespaces: ApiNamespace[] = [];
  for (const member of scriptApi.members) {
    if (!ts.isPropertySignature(member)) {
      continue;
    }

    const name = getPropertyName(member.name);
    if (name === null) {
      continue;
    }

    const shapeName =
      name === "packet"
        ? "ScriptPacketApi"
        : parseEffectValueShape(member.type);
    if (shapeName === null) {
      continue;
    }

    const typeReferences = new Set<string>();
    const members =
      name === "packet"
        ? collectScriptPacketMembers(
            checker,
            declarations,
            options,
            git,
            typeReferences,
          )
        : collectMembersFromInterface(
            checker,
            declarations,
            options,
            git,
            getInterface(declarations, shapeName),
            `api.${name}`,
            typeReferences,
          );

    const id = `api/${kebabCase(name)}`;
    namespaces.push({
      name,
      slug: kebabCase(name),
      href: `/scripting/api/${kebabCase(name)}/`,
      sourceType: shapeName,
    });
    const summary = getSummary(member);
    groups.push({
      id,
      title: `api.${name}`,
      label: titleCase(name),
      description: summary || "",
      summary,
      members,
      typeReferences: Array.from(typeReferences),
    });
  }

  for (const member of scriptContext.members) {
    if (!ts.isPropertySignature(member)) {
      continue;
    }

    const name = getPropertyName(member.name);
    if (name === null || name === "api" || name === "script") {
      continue;
    }

    const shapeName = parseEffectValueShape(member.type);
    if (shapeName === null) {
      continue;
    }

    const typeReferences = new Set<string>();
    const members = collectMembersFromInterface(
      checker,
      declarations,
      options,
      git,
      getInterface(declarations, shapeName),
      name,
      typeReferences,
    );

    const summary = getSummary(member) || "";
    groups.push({
      id: kebabCase(name),
      title: name,
      label: titleCase(name),
      description: summary,
      summary,
      members,
      typeReferences: Array.from(typeReferences),
    });
  }

  return {
    runtimeHelpers,
    namespaces: namespaces.sort((a, b) => a.name.localeCompare(b.name)),
    groups: groups.sort((a, b) => a.id.localeCompare(b.id)),
    typeReferences: Array.from(
      new Set([
        ...helperTypeReferences,
        ...groups.flatMap((group) => group.typeReferences),
      ]),
    ),
  };
};

const walkReflection = (
  reflection: Reflection,
  visit: (reflection: Reflection) => void,
): void => {
  visit(reflection);
  if (!reflection.isContainer()) {
    return;
  }
  for (const child of reflection.children ?? []) {
    walkReflection(child, visit);
  }
};

const reflectionSource = (
  options: CliOptions,
  git: GitSourceInfo | null,
  reflection: DeclarationReflection | SignatureReflection,
): SourceInfo => {
  const source = reflection.sources?.[0];
  if (source === undefined) {
    return {
      sourcePath: "unknown",
      sourceLine: 1,
      sourceUrl: null,
    };
  }

  const fullPath =
    source.fullFileName || resolve(options.repoRoot, source.fileName);
  const sourcePath = relative(options.repoRoot, fullPath).replaceAll("\\", "/");
  return {
    sourcePath,
    sourceLine: source.line,
    sourceUrl: buildSourceUrl(git, options.repoRoot, fullPath, source.line),
  };
};

const commentText = (reflection: Reflection | undefined): string => {
  const parts = reflection?.comment?.summary ?? [];
  return parts
    .map((part) => ("text" in part ? part.text : ""))
    .join("")
    .trim();
};

const typeToString = (type: SomeType | undefined): string =>
  type?.toString() ?? "unknown";

const typeParametersText = (
  typeParameters: DeclarationReflection["typeParameters"],
): string =>
  typeParameters === undefined || typeParameters.length === 0
    ? ""
    : `<${typeParameters.map((parameter) => parameter.name).join(", ")}>`;

const typedocKindName = (kind: ReflectionKind): string =>
  ReflectionKind.singularString(kind).toString().toLowerCase();

const isDocumentableTypeReflection = (
  reflection: Reflection,
): reflection is DeclarationReflection =>
  reflection.isDeclaration() &&
  (reflection.kind === ReflectionKind.Class ||
    reflection.kind === ReflectionKind.Interface ||
    reflection.kind === ReflectionKind.TypeAlias ||
    reflection.kind === ReflectionKind.Enum);

const reflectionRank = (reflection: DeclarationReflection): number => {
  const sourcePenalty = reflection.sources?.some((source) =>
    source.fullFileName.includes("/dist/"),
  )
    ? 10
    : 0;

  switch (reflection.kind) {
    case ReflectionKind.Class:
      return sourcePenalty;
    case ReflectionKind.Interface:
      return sourcePenalty + 1;
    case ReflectionKind.TypeAlias:
      return sourcePenalty + 2;
    case ReflectionKind.Enum:
      return sourcePenalty + 3;
    default:
      return sourcePenalty + 4;
  }
};

const isDocSourceReflection = (
  options: CliOptions,
  reflection: DeclarationReflection,
): boolean => {
  const source = reflection.sources?.[0];
  if (source === undefined) {
    return false;
  }

  const fullPath =
    source.fullFileName || resolve(options.repoRoot, source.fileName);
  if (!isInsideRepo(options.repoRoot, fullPath)) {
    return false;
  }

  const relativePath = relative(options.repoRoot, fullPath).replaceAll(
    "\\",
    "/",
  );
  return (
    relativePath.startsWith("app/src/shared/") ||
    relativePath.startsWith("app/src/renderer/windows/game/") ||
    relativePath.startsWith("packages/game/src/") ||
    relativePath.startsWith("packages/collection/src/")
  );
};

const buildTypeReflectionMap = (
  options: CliOptions,
  project: ProjectReflection,
): ReadonlyMap<string, DeclarationReflection> => {
  const reflections = new Map<string, DeclarationReflection>();
  walkReflection(project, (reflection) => {
    if (
      !isDocumentableTypeReflection(reflection) ||
      !isDocSourceReflection(options, reflection)
    ) {
      return;
    }

    const current = reflections.get(reflection.name);
    if (
      current === undefined ||
      reflectionRank(reflection) < reflectionRank(current)
    ) {
      reflections.set(reflection.name, reflection);
    }
  });
  return reflections;
};

const collectTypeNameTokens = (text: string, output: Set<string>): void => {
  for (const match of text.matchAll(/\b[A-Za-z_$][A-Za-z0-9_$]*\b/g)) {
    const token = match[0];
    if (!BUILTIN_TYPE_NAMES.has(token) && !TYPE_REFERENCE_WRAPPERS.has(token)) {
      output.add(token);
    }
  }
};

const getInheritedFrom = (reflection: DeclarationReflection): string | null => {
  const inherited = reflection.inheritedFrom;
  if (inherited === undefined) {
    return null;
  }

  const parent = inherited.reflection?.parent;
  if (parent !== undefined && parent.name !== reflection.parent?.name) {
    return parent.name;
  }

  const qualified = inherited.qualifiedName;
  const parts = qualified.split(".");
  return parts.length > 1 ? (parts[parts.length - 2] ?? null) : inherited.name;
};

const methodSignatureText = (
  method: DeclarationReflection,
  signature: SignatureReflection,
): string => {
  const typeParameters =
    signature.typeParameters === undefined ||
    signature.typeParameters.length === 0
      ? ""
      : `<${signature.typeParameters.map((parameter) => parameter.name).join(", ")}>`;
  const parameters = (signature.parameters ?? [])
    .map((parameter) => {
      const rest = parameter.flags.isRest ? "..." : "";
      const optional = parameter.flags.isOptional ? "?" : "";
      return `${rest}${parameter.name}${optional}: ${typeToString(parameter.type)}`;
    })
    .join(", ");
  return `${method.name}${typeParameters}(${parameters}): ${typeToString(
    signature.type,
  )}`;
};

const declarationDefinition = (reflection: DeclarationReflection): string => {
  const typeParameters = typeParametersText(reflection.typeParameters);
  switch (reflection.kind) {
    case ReflectionKind.Class: {
      const extended = reflection.extendedTypes?.[0];
      return `class ${reflection.name}${typeParameters}${
        extended === undefined ? "" : ` extends ${extended.toString()}`
      }`;
    }
    case ReflectionKind.Interface:
      return `interface ${reflection.name}${typeParameters}`;
    case ReflectionKind.TypeAlias:
      return `type ${reflection.name}${typeParameters} = ${typeToString(
        reflection.type,
      )}`;
    case ReflectionKind.Enum:
      return `enum ${reflection.name}`;
    default:
      return `${typedocKindName(reflection.kind)} ${reflection.name}`;
  }
};

const isVisibleInstanceMember = (reflection: DeclarationReflection): boolean =>
  !reflection.flags.isPrivate &&
  !reflection.flags.isProtected &&
  !reflection.flags.isStatic;

const buildReferencedTypeDoc = (
  options: CliOptions,
  git: GitSourceInfo | null,
  reflection: DeclarationReflection,
): ReferencedTypeDoc => {
  const properties: TypeMemberDoc[] = [];
  const methods: TypeMethodDoc[] = [];

  for (const child of reflection.children ?? []) {
    if (!isVisibleInstanceMember(child)) {
      continue;
    }

    if (
      child.kind === ReflectionKind.Property ||
      child.kind === ReflectionKind.Accessor ||
      child.kind === ReflectionKind.EnumMember
    ) {
      const getSignature = child.getSignature;
      properties.push({
        name: child.name,
        type: typeToString(getSignature?.type ?? child.type),
        summary: commentText(getSignature ?? child),
        readonly:
          child.flags.isReadonly || child.kind === ReflectionKind.Accessor,
        optional: child.flags.isOptional,
        inheritedFrom: getInheritedFrom(child),
        ...reflectionSource(options, git, getSignature ?? child),
      });
      continue;
    }

    if (child.kind === ReflectionKind.Method) {
      for (const signature of child.signatures ?? []) {
        methods.push({
          name: child.name,
          signature: methodSignatureText(child, signature),
          summary: commentText(signature) || commentText(child),
          inheritedFrom: getInheritedFrom(child),
          ...reflectionSource(options, git, signature),
        });
      }
    }
  }

  return {
    name: reflection.name,
    slug: kebabCase(reflection.name),
    kind: typedocKindName(reflection.kind),
    summary: commentText(reflection),
    definition: declarationDefinition(reflection),
    properties: properties.sort((a, b) => a.name.localeCompare(b.name)),
    methods: methods.sort((a, b) => a.name.localeCompare(b.name)),
    ...reflectionSource(options, git, reflection),
  };
};

const collectReferencedTypeDocs = (
  options: CliOptions,
  git: GitSourceInfo | null,
  project: ProjectReflection,
  rootReferences: ReadonlySet<string>,
): ReferencedTypeDoc[] => {
  const reflections = buildTypeReflectionMap(options, project);
  const pending = Array.from(rootReferences);
  const seen = new Set<string>();
  const docs: ReferencedTypeDoc[] = [];

  for (let index = 0; index < pending.length; index += 1) {
    const name = pending[index];
    if (
      name === undefined ||
      seen.has(name) ||
      BUILTIN_TYPE_NAMES.has(name) ||
      TYPE_REFERENCE_WRAPPERS.has(name)
    ) {
      continue;
    }
    seen.add(name);

    const reflection = reflections.get(name);
    if (reflection === undefined) {
      continue;
    }

    const doc = buildReferencedTypeDoc(options, git, reflection);
    docs.push(doc);

    const nestedReferences = new Set<string>();
    collectTypeNameTokens(doc.definition, nestedReferences);
    for (const property of doc.properties) {
      collectTypeNameTokens(property.type, nestedReferences);
    }
    for (const method of doc.methods) {
      collectTypeNameTokens(method.signature, nestedReferences);
    }
    for (const nested of nestedReferences) {
      if (!seen.has(nested) && !pending.includes(nested)) {
        pending.push(nested);
      }
    }
  }

  return docs.sort((a, b) => a.name.localeCompare(b.name));
};

const typedocEntryPoints = (
  program: ts.Program,
  options: CliOptions,
  declarations: ReadonlyMap<
    string,
    ts.InterfaceDeclaration | ts.TypeAliasDeclaration
  >,
  typeReferences: ReadonlySet<string>,
): readonly string[] => {
  const entryPoints = new Set<string>();
  const addSourceFile = (fileName: string): void => {
    if (
      fileName.includes("/node_modules/") ||
      fileName.endsWith(".test.ts") ||
      !isInsideRepo(options.repoRoot, fileName)
    ) {
      return;
    }
    entryPoints.add(relative(options.repoRoot, fileName).replaceAll("\\", "/"));
  };

  addSourceFile(options.sourceFile);
  for (const sourceFile of program.getSourceFiles()) {
    if (
      sourceFile.fileName.endsWith("app/src/renderer/windows/game/global.d.ts")
    ) {
      addSourceFile(sourceFile.fileName);
    }
  }
  for (const reference of typeReferences) {
    const declaration = declarations.get(reference);
    if (declaration !== undefined) {
      addSourceFile(declaration.getSourceFile().fileName);
    }
  }
  entryPoints.add(GAME_API_ENTRYPOINT);
  entryPoints.add(COLLECTION_API_ENTRYPOINT);
  return Array.from(entryPoints).sort();
};

const createTypeDocProject = (
  program: ts.Program,
  options: CliOptions,
  declarations: ReadonlyMap<
    string,
    ts.InterfaceDeclaration | ts.TypeAliasDeclaration
  >,
  typeReferences: ReadonlySet<string>,
): Effect.Effect<ProjectReflection, unknown> =>
  Effect.tryPromise(async () => {
    const app = await Application.bootstrap(
      {
        entryPoints: [
          ...typedocEntryPoints(program, options, declarations, typeReferences),
        ],
        excludeExternals: false,
        excludePrivate: true,
        excludeProtected: true,
        skipErrorChecking: true,
        logLevel: "Error",
        compilerOptions: {
          target: "esnext",
          module: "esnext",
          moduleResolution: "bundler",
          lib: ["esnext", "dom", "dom.iterable"],
          strict: true,
          skipLibCheck: true,
          jsx: "react-jsx",
          jsxImportSource: "solid-js",
          resolveJsonModule: true,
          esModuleInterop: true,
          allowSyntheticDefaultImports: true,
          noEmit: true,
          baseUrl: "app",
          paths: {
            "*": ["./*"],
          },
        },
      },
      [],
    );
    const project = await app.convert();
    if (project === undefined) {
      return fail("TypeDoc was unable to convert scripting API entry points");
    }
    return project;
  });

const renderTypeExpression = (
  type: string,
  typeLinks: ReadonlyMap<string, TypeLink>,
): string => {
  let rendered = "";
  for (let index = 0; index < type.length; ) {
    const rest = type.slice(index);
    const match = /^[A-Za-z_$][A-Za-z0-9_$]*/.exec(rest);
    if (match?.[0]) {
      const token = match[0];
      const link = typeLinks.get(token);
      rendered +=
        link === undefined ? renderCode(token) : renderTypeLink(token, link);
      index += token.length;
      continue;
    }

    const char = type[index] ?? "";
    if (char === "|") {
      rendered += "\\|";
    } else if (char === "<") {
      rendered += "&lt;";
    } else if (char === ">") {
      rendered += "&gt;";
    } else {
      rendered += escapeTableCell(char);
    }
    index += 1;
  }
  return rendered;
};

const buildTypeLinks = (
  types: readonly ReferencedTypeDoc[],
  prefix: string,
): ReadonlyMap<string, TypeLink> =>
  new Map(
    types.map((type) => [
      type.name,
      {
        href: `${prefix}${type.slug}/`,
        slug: type.slug,
      },
    ]),
  );

const renderTypeLink = (name: string, link: TypeLink): string =>
  `<a href="${escapeHtml(link.href)}" data-script-type="${escapeHtml(link.slug)}">${renderHtmlCode(name)}</a>`;

const renderSourceLink = (
  source: SourceInfo,
  className = "source-reference__link",
): string => {
  const sourceReference = `${source.sourcePath}:${source.sourceLine}`;
  const isHeadingLink = className === "source-reference__heading-link";
  const headingStyle = isHeadingLink
    ? ` style="float: right; display: inline-flex; align-items: center; justify-content: center; margin-block: -0.125rem; margin-inline-start: 0.5rem; border-radius: var(--radius-sm); text-decoration: none;"`
    : "";
  const headingAttributes = isHeadingLink
    ? ` tabindex="-1" aria-hidden="true"`
    : ` aria-label="Open source: ${escapeHtml(sourceReference)}"`;
  const icon = `<svg class="source-reference__icon" width="16" height="16" aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m18 16 4-4-4-4"></path><path d="m6 8-4 4 4 4"></path><path d="m14.5 4-5 16"></path></svg>`;
  return source.sourceUrl
    ? `<a class="${className}"${headingStyle} href="${escapeHtml(source.sourceUrl)}"${headingAttributes} title="Open source: ${escapeHtml(sourceReference)}" target="_blank" rel="noreferrer">${icon}</a>`
    : "";
};

const renderHeadingSourceLink = (source: SourceInfo): string => {
  const sourceLink = renderSourceLink(source, "source-reference__heading-link");
  return sourceLink === "" ? "" : ` ${sourceLink}`;
};

const renderSource = (source: SourceInfo): string => {
  const sourceReference = `${source.sourcePath}:${source.sourceLine}`;
  const sourcePath = `<code class="source-reference__path">${escapeHtml(sourceReference)}</code>`;

  return `<p class="source-reference"><span class="source-reference__label">Source</span>${sourcePath}${renderSourceLink(source)}</p>`;
};

const renderMember = (
  lines: string[],
  member: MemberDoc,
  typeLinks: ReadonlyMap<string, TypeLink>,
) => {
  lines.push(`<a id="${memberAnchor(member.path)}"></a>`, "");
  lines.push(
    `### \`${member.path}${member.kind === "method" ? "()" : ""}\`${renderHeadingSourceLink(member)}`,
    "",
  );

  if (member.summary !== "") {
    lines.push(member.summary, "");
  }

  if (member.sourceUrl === null) {
    lines.push(renderSource(member), "");
  }

  lines.push("```ts", member.signature, "```", "");

  if (member.parameters.length > 0) {
    lines.push(
      "| Name | Type | Required | Description |",
      "| --- | --- | --- | --- |",
    );
    for (const parameter of member.parameters) {
      lines.push(
        `| ${renderCode(`${parameter.rest ? "..." : ""}${parameter.name}`)} | ${renderTypeExpression(parameter.type, typeLinks)} | ${renderBooleanMark(parameter.required)} | ${escapeTableCell(parameter.description)} |`,
      );
    }
    lines.push("");
  }

  if (member.returnDoc.result !== null) {
    lines.push(
      `**Yields:** ${renderTypeExpression(member.returnDoc.result, typeLinks)}`,
      "",
      `**Errors:** ${renderTypeExpression(member.returnDoc.error ?? "never", typeLinks)}`,
      "",
    );
  } else {
    lines.push(
      `**Returns:** ${renderTypeExpression(member.returnDoc.raw, typeLinks)}`,
      "",
    );
  }
};

const typeMemberAnchor = (kind: "property" | "method", name: string): string =>
  `${kind}-${anchorSlug(name)}`;

const renderTypeProperty = (lines: string[], property: TypeMemberDoc) => {
  lines.push(
    `<a id="${typeMemberAnchor("property", property.name)}"></a>`,
    "",
    `### \`${property.name}\`${renderHeadingSourceLink(property)}`,
    "",
  );

  if (property.summary !== "") {
    lines.push(property.summary, "");
  }

  if (property.sourceUrl === null) {
    lines.push(renderSource(property), "");
  }

  lines.push("```ts");
  lines.push(
    `${property.readonly ? "readonly " : ""}${property.name}${
      property.optional ? "?" : ""
    }: ${property.type}`,
  );
  lines.push("```", "");
};

const renderTypeMethod = (lines: string[], method: TypeMethodDoc) => {
  lines.push(
    `<a id="${typeMemberAnchor("method", method.name)}"></a>`,
    "",
    `### \`${method.name}()\`${renderHeadingSourceLink(method)}`,
    "",
  );

  if (method.summary !== "") {
    lines.push(method.summary, "");
  }

  if (method.sourceUrl === null) {
    lines.push(renderSource(method), "");
  }

  lines.push("```ts", method.signature, "```", "");
};

const frontmatter = (
  title: string,
  description: string,
  label?: string,
  extraFields = "",
): string => {
  const yamlString = (value: string): string => JSON.stringify(value);
  const sidebar =
    label === undefined ? "" : `sidebar:\n  label: ${yamlString(label)}\n`;
  return `---\ntitle: ${yamlString(title)}\ndescription: ${yamlString(description)}\n${sidebar}${extraFields}tableOfContents:\n  minHeadingLevel: 2\n  maxHeadingLevel: 3\n---`;
};

const finalizeMarkdown = (lines: readonly string[]): string =>
  `${lines
    .join("\n")
    .replace(/\n{3,}/g, "\n\n")
    .trimEnd()}\n`;

const renderIndex = (_namespaces: readonly ApiNamespace[]): string => {
  const lines = [
    frontmatter("Scripting API", "", "Overview"),
    "",
    GENERATED_HEADER,
    "",
    "Scripts export a CommonJS generator function and receive one context object.",
    "",
    "```js",
    "module.exports = function* run(ctx) {",
    "  const { api, script } = ctx",
    '  script.log("started")',
    '  yield* api.player.joinMap("battleon")',
    "}",
    "```",
    "",
    "## Context",
    "",
    "The context is the object passed to your script. It separates gameplay APIs, current-script lifecycle helpers, and scriptable feature controls.",
    "",
    "| Member | Description |",
    "| --- | --- |",
    "| [`api`](/scripting/api/) | Gameplay and game-state APIs. |",
    "| [`script`](/scripting/script/) | Current script lifecycle and diagnostics APIs. |",
    "| [`autoZone`](/scripting/auto-zone/) | Auto Zone feature controls. |",
    "| [`autoRelogin`](/scripting/auto-relogin/) | Auto Relogin feature controls. |",
    "",
    "## Reference",
    "",
    "| Page | Description |",
    "| --- | --- |",
    "| [`types`](/scripting/types/) | Referenced scripting data types and public class surfaces. |",
    "",
    "## Editor Integration",
    "",
    "Download the generated declaration file [`script-api.d.ts`](/script-api.d.ts) and place it beside your scripts. These typings are not perfect, but they should be good enough for editor autocomplete and catching common mistakes.",
    "",
    "```js",
    '/// <reference path="./script-api.d.ts" />',
    "",
    "/** @param {ScriptContext} context */",
    "module.exports = function* run({ api }) {",
    '  yield* api.player.joinMap("battleon")',
    "}",
    "```",
    "",
    "For a folder full of scripts, put `script-api.d.ts` beside them and add `jsconfig.json` to the folder. Keep `checkJs` off to get autocomplete without diagnostics noise, and add `// @ts-check` only to files where you want type errors reported.",
    "",
    "```json",
    "{",
    '  "compilerOptions": {',
    '    "target": "ES2020",',
    '    "lib": ["ES2020", "DOM"],',
    '    "checkJs": false,',
    '    "skipLibCheck": true',
    "  },",
    '  "include": ["**/*.js", "script-api.d.ts"]',
    "}",
    "```",
  ];
  return finalizeMarkdown(lines);
};

const renderApiOverview = (namespaces: readonly ApiNamespace[]): string => {
  const lines = [
    frontmatter(
      "Game API",
      "Gameplay and game-state APIs exposed to scripts.",
      "API",
    ),
    "",
    GENERATED_HEADER,
    "",
    "`api` gives scripts access to gameplay and game-state namespaces.",
    "",
    "## Namespaces",
    "",
    "| Namespace | Description |",
    "| --- | --- |",
    ...namespaces.map(
      (namespace) =>
        `| [\`api.${namespace.name}\`](${namespace.href}) | ${titleCase(
          namespace.name,
        )} APIs. |`,
    ),
  ];

  return finalizeMarkdown(lines);
};

const renderScriptOverview = (
  helpers: readonly MemberDoc[],
  typeLinks: ReadonlyMap<string, TypeLink>,
): string => {
  const lines = [
    frontmatter(
      "Script",
      "Current script lifecycle and diagnostics APIs.",
      "Script",
    ),
    "",
    GENERATED_HEADER,
    "",
    "`script` gives scripts access to the current script's lifecycle and diagnostics helpers.",
    "",
    "## Members",
    "",
  ];

  for (const helper of helpers) {
    renderMember(lines, helper, typeLinks);
  }

  return finalizeMarkdown(lines);
};

const renderGroup = (
  group: ApiGroup,
  typeLinks: ReadonlyMap<string, TypeLink>,
): string => {
  const lines = [
    frontmatter(group.title, group.description, group.label),
    "",
    GENERATED_HEADER,
    "",
    group.summary,
    "",
  ];

  if (group.members.length > 0) {
    lines.push("## Members", "");
    for (const member of group.members) {
      renderMember(lines, member, typeLinks);
    }
  }

  return finalizeMarkdown(lines);
};

const renderTypesIndex = (types: readonly ReferencedTypeDoc[]): string => {
  const lines = [
    frontmatter("Referenced Types", "", "Types"),
    "",
    GENERATED_HEADER,
    "",
    "Referenced types are generated from the types directly linked by the documented API surface. This page is not a complete or authoritative representation of every type available.",
    "",
    "",
    "| Type | Kind | Summary |",
    "| --- | --- | --- |",
    ...types.map(
      (type) =>
        `| ${renderTypeLink(type.name, {
          href: `/scripting/types/${type.slug}/`,
          slug: type.slug,
        })} | ${escapeTableCell(type.kind)} | ${escapeTableCell(type.summary)} |`,
    ),
  ];
  return finalizeMarkdown(lines);
};

const renderTypePage = (type: ReferencedTypeDoc): string => {
  const lines = [
    frontmatter(type.name, type.summary || "", type.name),
    "",
    GENERATED_HEADER,
    "",
  ];

  if (type.summary !== "") {
    lines.push(type.summary, "");
  }

  if (type.sourceUrl === null) {
    lines.push(renderSource(type), "");
  }

  lines.push("```ts", type.definition, "```", "");

  if (type.properties.length > 0) {
    lines.push("## Properties", "");
    for (const property of type.properties) {
      renderTypeProperty(lines, property);
    }
  }

  if (type.methods.length > 0) {
    lines.push("## Methods", "");
    for (const method of type.methods) {
      renderTypeMethod(lines, method);
    }
  }

  return finalizeMarkdown(lines);
};

const renderSourceLinksModule = (
  types: readonly ReferencedTypeDoc[],
): string => {
  const entries = types
    .filter((type) => type.sourceUrl !== null)
    .map((type) => {
      const sourceReference = `${type.sourcePath}:${type.sourceLine}`;
      return `  ${JSON.stringify(`scripting/types/${type.slug}`)}: { path: ${JSON.stringify(sourceReference)}, url: ${JSON.stringify(type.sourceUrl)} },`;
    })
    .sort();

  return `${GENERATED_HEADER.replace("<!--", "//").replace("-->", "")}

export const scriptSourceLinks: Record<string, { path: string; url: string }> = {
${entries.join("\n")}
};
`;
};

const renderTypePreviewsJson = (types: readonly ReferencedTypeDoc[]): string =>
  `${JSON.stringify(
    {
      types: Object.fromEntries(
        types
          .map((type): [string, object] => [
            type.slug,
            {
              name: type.name,
              slug: type.slug,
              kind: type.kind,
              summary: type.summary,
              definition: type.definition,
              keys: [
                ...type.properties.map((property) => ({
                  kind: "property",
                  name: property.name,
                  signature: `${property.readonly ? "readonly " : ""}${property.name}${
                    property.optional ? "?" : ""
                  }: ${property.type}`,
                  description: property.summary,
                })),
                ...type.methods.map((method) => ({
                  kind: "method",
                  name: `${method.name}()`,
                  signature: method.signature,
                  description: method.summary,
                })),
              ],
              source:
                type.sourceUrl === null
                  ? null
                  : {
                      path: `${type.sourcePath}:${type.sourceLine}`,
                      url: type.sourceUrl,
                    },
            },
          ])
          .sort(([left], [right]) => left.localeCompare(right)),
      ),
    },
    null,
    2,
  )}\n`;

const renderFiles = (
  options: CliOptions,
  helpers: readonly MemberDoc[],
  namespaces: readonly ApiNamespace[],
  groups: readonly ApiGroup[],
  types: readonly ReferencedTypeDoc[],
): ReadonlyArray<RenderedFile> => {
  const typeLinks = buildTypeLinks(types, "/scripting/types/");
  return [
    {
      path: join(options.outputDir, "index.md"),
      content: renderIndex(namespaces),
    },
    {
      path: join(options.outputDir, "api.md"),
      content: renderApiOverview(namespaces),
    },
    {
      path: join(options.outputDir, "script.md"),
      content: renderScriptOverview(helpers, typeLinks),
    },
    {
      path: join(options.outputDir, "types/index.md"),
      content: renderTypesIndex(types),
    },
    ...groups.map((group) => ({
      path: join(options.outputDir, `${group.id}.md`),
      content: renderGroup(group, typeLinks),
    })),
    ...types.map((type) => ({
      path: join(options.outputDir, `types/${type.slug}.md`),
      content: renderTypePage(type),
    })),
    {
      path: resolve(options.repoRoot, SOURCE_LINKS_OUTPUT),
      content: renderSourceLinksModule(types),
    },
    {
      path: resolve(options.repoRoot, TYPE_PREVIEWS_OUTPUT),
      content: renderTypePreviewsJson(types),
    },
  ];
};

const ensureParentDir = async (path: string): Promise<void> => {
  await fs.mkdir(dirname(path), { recursive: true });
};

const listMarkdownFiles = async (dir: string): Promise<readonly string[]> => {
  const entries = await fs
    .readdir(dir, { withFileTypes: true })
    .catch(() => []);
  const files: string[] = [];
  for (const entry of entries) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await listMarkdownFiles(path)));
    } else if (entry.isFile() && entry.name.endsWith(".md")) {
      files.push(path);
    }
  }
  return files;
};

const writeGeneratedDocs = (
  repoRoot: string,
  outputDir: string,
  files: ReadonlyArray<RenderedFile>,
): Effect.Effect<void, unknown> =>
  Effect.gen(function* () {
    const legacyDir = resolve(repoRoot, LEGACY_OUTPUT_DIR);
    if (legacyDir !== outputDir) {
      yield* Effect.tryPromise(() =>
        fs.rm(legacyDir, { recursive: true, force: true }),
      );
    }

    yield* Effect.tryPromise(() => fs.mkdir(outputDir, { recursive: true }));

    const expected = new Set(files.map((file) => resolve(file.path)));
    const existing = yield* Effect.tryPromise(() =>
      listMarkdownFiles(outputDir),
    );
    for (const file of existing) {
      if (!expected.has(resolve(file))) {
        yield* Effect.tryPromise(() => fs.unlink(file));
      }
    }

    for (const file of files) {
      yield* Effect.tryPromise(() => ensureParentDir(file.path));
      const current = yield* Effect.tryPromise(() =>
        fs.readFile(file.path, "utf8"),
      ).pipe(Effect.catch(() => Effect.succeed(null)));
      if (current === file.content) {
        continue;
      }

      yield* Effect.tryPromise(() =>
        fs.writeFile(file.path, file.content, "utf8"),
      );
    }
  });

const main = (options: CliOptions): Effect.Effect<void, unknown> =>
  Effect.gen(function* () {
    const program = createProgram(options.repoRoot);
    const sourceFile = program.getSourceFile(options.sourceFile);
    if (!sourceFile) {
      fail(`Unable to load ${relative(options.repoRoot, options.sourceFile)}`);
    }

    const checker = program.getTypeChecker();
    const declarations = buildDeclarationMap(program);
    const git = yield* getGitSourceInfo(options.repoRoot);
    const { runtimeHelpers, namespaces, groups, typeReferences } =
      collectApiGroups(
        checker,
        declarations,
        options,
        options.includeSourceLinks ? git : null,
      );
    const typedocProject = yield* createTypeDocProject(
      program,
      options,
      declarations,
      new Set(typeReferences),
    );
    const referencedTypes = collectReferencedTypeDocs(
      options,
      options.includeSourceLinks ? git : null,
      typedocProject,
      new Set(typeReferences),
    );
    const renderedFiles = renderFiles(
      options,
      runtimeHelpers,
      namespaces,
      groups,
      referencedTypes,
    );

    yield* writeGeneratedDocs(
      options.repoRoot,
      options.outputDir,
      renderedFiles,
    );
    yield* Console.log(
      `Generated ${renderedFiles.length} scripting API doc files in ${relative(
        options.repoRoot,
        options.outputDir,
      )}`,
    );
  });

if (
  process.argv[1] &&
  import.meta.url === pathToFileURL(process.argv[1]).href
) {
  const options = parseCliOptions(process.argv.slice(2), DEFAULT_REPO_ROOT);

  main(options).pipe(
    Effect.catch((error) =>
      Effect.gen(function* () {
        yield* Console.error(
          error instanceof Error ? error.message : String(error),
        );
        yield* Effect.sync(() => {
          process.exitCode = 1;
        });
      }),
    ),
    NodeRuntime.runMain,
  );
}
