import fs from "node:fs/promises";
import { dirname, isAbsolute, join, relative, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import ts from "typescript";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const DEFAULT_REPO_ROOT = join(SCRIPT_DIR, "..");
const DEFAULT_SOURCE_FILE =
  "app/src/renderer/windows/game/scripting/ScriptApi.ts";
const DEFAULT_OUTPUT_FILE = "docs/public/script-api.d.ts";
const APP_TSCONFIG = "app/tsconfig.json";
const GENERATED_HEADER =
  "// Generated by pnpm run types:scripting. Do not edit directly.";

const BUILTIN_TYPE_NAMES = new Set([
  "A",
  "AbortSignal",
  "Array",
  "Boolean",
  "Date",
  "E",
  "Error",
  "Exclude",
  "Function",
  "Generator",
  "InitialValue",
  "Key",
  "Map",
  "Math",
  "NewKey",
  "NewValue",
  "Object",
  "Omit",
  "OtherValue",
  "Partial",
  "Pick",
  "Promise",
  "Readonly",
  "ReadonlyArray",
  "ReadonlyMap",
  "Record",
  "Required",
  "Requirements",
  "ResultValue",
  "Set",
  "String",
  "Symbol",
  "TemplateStringsArray",
  "This",
  "Value",
  "any",
  "bigint",
  "boolean",
  "false",
  "never",
  "null",
  "number",
  "object",
  "string",
  "symbol",
  "true",
  "undefined",
  "unknown",
  "void",
]);

const SUPPORT_TYPE_NAMES = new Set([
  "ArmyError",
  "BridgeError",
  "DurationInput",
  "DurationLike",
  "Effect",
  "EffectYieldable",
  "ItemIdentifierToken",
  "MonsterIdentifierToken",
  "MonsterMapID",
  "MonsterName",
  "Option",
  "ScriptExecutionError",
  "ScriptNotReadyError",
  "Skill",
]);

const SUPPORT_DECLARATIONS = `
type DurationInput = number | string | bigint | DurationLike;

interface DurationLike {
  readonly _tag?: string;
}

type Option<Value> =
  | { readonly _tag: "Some"; readonly value: Value }
  | { readonly _tag: "None" };

type EffectYieldable<
  Value = unknown,
  Error = unknown,
  Requirements = never,
  Next = never,
> = unknown;

interface Effect<
  Value = unknown,
  Error = unknown,
  Requirements = never,
> {
  [Symbol.iterator](): Generator<EffectYieldable<Value, Error>, Value, any>;
}

interface ScriptExecutionError extends Error {
  readonly _tag: "ScriptExecutionError";
  readonly sourceName: string;
}

interface ScriptNotReadyError extends Error {
  readonly _tag: "ScriptNotReadyError";
  readonly sourceName: string;
}

interface BridgeError extends Error {}

interface ArmyError extends Error {}

type ItemIdentifierToken = number | string;
type MonsterName =
  | string
  | \`id'\${number}\`
  | \`id.\${number}\`
  | \`id:\${number}\`
  | \`id-\${number}\`;
type MonsterMapID = number;
type MonsterIdentifierToken = MonsterName | MonsterMapID;
type Skill = number | string;
`;

type CliOptions = {
  readonly repoRoot: string;
  readonly sourceFile: string;
  readonly outputFile: string;
};

type Declaration =
  | ts.InterfaceDeclaration
  | ts.TypeAliasDeclaration
  | ts.ClassDeclaration
  | ts.EnumDeclaration;

type RenderedInterface = {
  readonly name: string;
  readonly content: string;
};

class TypesgenError extends Error {
  override readonly name = "TypesgenError";
}

const fail = (message: string): never => {
  throw new TypesgenError(message);
};

const parseCliOptions = (
  args: ReadonlyArray<string>,
  repoRoot: string,
): CliOptions => {
  let source = DEFAULT_SOURCE_FILE;
  let out = DEFAULT_OUTPUT_FILE;

  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index] ?? fail(`Unable to read argument at ${index}`);
    if (arg === "--") {
      continue;
    }
    if (arg === "--source") {
      source = args[index + 1] ?? fail("--source requires a path");
      index += 1;
      continue;
    }
    if (arg.startsWith("--source=")) {
      source = arg.slice("--source=".length);
      continue;
    }
    if (arg === "--out") {
      out = args[index + 1] ?? fail("--out requires a path");
      index += 1;
      continue;
    }
    if (arg.startsWith("--out=")) {
      out = arg.slice("--out=".length);
      continue;
    }
    fail(`Unknown argument: ${arg}`);
  }

  return {
    repoRoot,
    sourceFile: isAbsolute(source) ? source : resolve(repoRoot, source),
    outputFile: isAbsolute(out) ? out : resolve(repoRoot, out),
  };
};

const createProgram = (repoRoot: string): ts.Program => {
  const configPath = resolve(repoRoot, APP_TSCONFIG);
  const readResult = ts.readConfigFile(configPath, ts.sys.readFile);
  if (readResult.error) {
    fail(ts.flattenDiagnosticMessageText(readResult.error.messageText, "\n"));
  }

  const parsed = ts.parseJsonConfigFileContent(
    readResult.config,
    ts.sys,
    dirname(configPath),
  );

  if (parsed.errors.length > 0) {
    fail(
      parsed.errors
        .map((error) =>
          ts.flattenDiagnosticMessageText(error.messageText, "\n"),
        )
        .join("\n"),
    );
  }

  return ts.createProgram({
    rootNames: parsed.fileNames,
    options: parsed.options,
  });
};

const getPropertyName = (name: ts.PropertyName): string | null => {
  if (
    ts.isIdentifier(name) ||
    ts.isStringLiteral(name) ||
    ts.isNumericLiteral(name)
  ) {
    return name.text;
  }
  return null;
};

const getEntityNameText = (name: ts.EntityName): string =>
  ts.isIdentifier(name) ? name.text : `${getEntityNameText(name.left)}.${name.right.text}`;

const getUnqualifiedEntityName = (name: ts.EntityName): string =>
  ts.isIdentifier(name) ? name.text : name.right.text;

const parseTypeReference = (
  node: ts.TypeNode | undefined,
): { readonly name: string; readonly unqualifiedName: string; readonly args: readonly ts.TypeNode[] } | null => {
  if (!node || !ts.isTypeReferenceNode(node)) {
    return null;
  }

  return {
    name: getEntityNameText(node.typeName),
    unqualifiedName: getUnqualifiedEntityName(node.typeName),
    args: Array.from(node.typeArguments ?? []),
  };
};

const typeParameterText = (
  sourceFile: ts.SourceFile,
  typeParameters: ts.NodeArray<ts.TypeParameterDeclaration> | undefined,
): string =>
  typeParameters === undefined || typeParameters.length === 0
    ? ""
    : `<${typeParameters.map((parameter) => parameter.getText(sourceFile)).join(", ")}>`;

const formatType = (
  checker: ts.TypeChecker,
  node: ts.TypeNode | undefined,
): string => {
  if (node === undefined) {
    return "unknown";
  }

  const text = checker.typeToString(
    checker.getTypeAtLocation(node),
    node,
    ts.TypeFormatFlags.NoTruncation |
      ts.TypeFormatFlags.UseSingleQuotesForStringLiteralType,
  );
  return normalizeTypeText(text);
};

const typeNodeText = (node: ts.TypeNode, sourceFile: ts.SourceFile): string =>
  normalizeTypeText(node.getText(sourceFile));

const transformTypeText = (type: string): string => {
  let output = type;

  output = output.replace(/\bEffect\.Effect\s*</g, "Effect<");
  output = output.replace(/\bEffect\.Yieldable\s*</g, "EffectYieldable<");
  output = output.replace(/\bOption\.Option\s*</g, "Option<");
  output = output.replace(/\bDuration\.Input\b/g, "DurationInput");
  output = output.replace(/\bReadonlyArray\s*</g, "readonly ");
  output = output.replace(/\bSchema\.Schema\.Type<[^>]+>/g, "unknown");
  output = output.replace(/\bData\.TaggedError\([^)]*\)<([^>]*)>/g, "Error & $1");

  return output;
};

const normalizeTypeText = (type: string): string =>
  transformTypeText(type)
    .replace(/import\([^)]*\)\./g, "")
    .replace(/\s+/g, " ")
    .trim();

const unwrapEffectReturn = (
  checker: ts.TypeChecker,
  node: ts.TypeNode | undefined,
): string | null => {
  const sourceFile = node?.getSourceFile();
  const reference = parseTypeReference(node);
  if (reference && sourceFile) {
    const args = reference.args.map((arg) => typeNodeText(arg, sourceFile));
    switch (reference.unqualifiedName) {
      case "Effect":
        return `Effect<${args[0] ?? "unknown"}, ${args[1] ?? "never"}>`;
      case "BridgeEffect":
        return `Effect<${args[0] ?? "unknown"}, BridgeError>`;
      case "ArmyEffect":
        return `Effect<${args[0] ?? "unknown"}, ${args[1] ?? "never"} | ArmyError | BridgeError>`;
      case "ScriptRecipeEffect":
        return `Effect<${args[0] ?? "unknown"}, unknown>`;
    }
  }

  const formatted = formatType(checker, node);
  if (formatted.startsWith("Effect<")) {
    return formatted;
  }
  return null;
};

const returnTypeText = (
  checker: ts.TypeChecker,
  node: ts.TypeNode | undefined,
): string => unwrapEffectReturn(checker, node) ?? formatType(checker, node);

const parameterText = (
  checker: ts.TypeChecker,
  parameter: ts.ParameterDeclaration,
): string => {
  const sourceFile = parameter.getSourceFile();
  const name = parameter.name.getText(sourceFile);
  const rest = parameter.dotDotDotToken === undefined ? "" : "...";
  const optional =
    parameter.dotDotDotToken !== undefined ||
    (parameter.questionToken === undefined && parameter.initializer === undefined)
      ? ""
      : "?";
  return `${rest}${name}${optional}: ${formatType(checker, parameter.type)}`;
};

const getJsDocComment = (node: ts.Node): string => {
  const docs = (node as ts.Node & { jsDoc?: ts.JSDoc[] }).jsDoc;
  const doc = docs?.[docs.length - 1];
  const raw = doc?.comment;
  if (typeof raw !== "string") {
    return "";
  }
  const text = raw.trim();
  if (text === "") {
    return "";
  }
  return `  /** ${text.replaceAll("*/", "*\\/")} */\n`;
};

const buildDeclarationMap = (program: ts.Program): ReadonlyMap<string, Declaration> => {
  const declarations = new Map<string, Declaration>();

  const visit = (node: ts.Node): void => {
    if (
      (ts.isInterfaceDeclaration(node) ||
        ts.isTypeAliasDeclaration(node) ||
        ts.isClassDeclaration(node) ||
        ts.isEnumDeclaration(node)) &&
      node.name
    ) {
      declarations.set(node.name.text, node);
    }
    ts.forEachChild(node, visit);
  };

  for (const sourceFile of program.getSourceFiles()) {
    if (sourceFile.fileName.includes("/node_modules/")) {
      continue;
    }
    visit(sourceFile);
  }

  return declarations;
};

const getInterface = (
  declarations: ReadonlyMap<string, Declaration>,
  name: string,
): ts.InterfaceDeclaration => {
  const declaration = declarations.get(name);
  if (!declaration || !ts.isInterfaceDeclaration(declaration)) {
    fail(`Unable to find interface ${name}`);
  }
  return declaration as ts.InterfaceDeclaration;
};

const getDeclaration = (
  declarations: ReadonlyMap<string, Declaration>,
  name: string,
): Declaration | null => declarations.get(name) ?? null;

const parseEffectValueShape = (
  node: ts.TypeNode | undefined,
): string | null => {
  const reference = parseTypeReference(node);
  if (
    !reference ||
    reference.unqualifiedName !== "EffectValue" ||
    reference.args.length !== 1
  ) {
    return null;
  }

  const target = parseTypeReference(reference.args[0]);
  return target?.unqualifiedName ?? null;
};

const interfaceNameForProperty = (propertyName: string): string => {
  const normalized = propertyName
    .replace(/(^|[-_\s]+)([a-zA-Z0-9])/g, (_match, _separator, char: string) =>
      char.toUpperCase(),
    )
    .replace(/[^A-Za-z0-9_$]/g, "");
  return `${normalized}Api`;
};

const nestedInterfaceName = (parentName: string, propertyName: string): string =>
  `${parentName.replace(/Api$/, "")}${interfaceNameForProperty(propertyName)}`;

const collectTypeNames = (text: string, output: Set<string>): void => {
  for (const match of text.matchAll(/\b[A-Za-z_$][A-Za-z0-9_$]*\b/g)) {
    const token = match[0];
    if (
      !BUILTIN_TYPE_NAMES.has(token) &&
      /^[A-Z_$]/.test(token)
    ) {
      output.add(token);
    }
  }
};

const renderMethodSignature = (
  checker: ts.TypeChecker,
  node: ts.MethodSignature | ts.FunctionTypeNode,
  name: string,
): string => {
  const sourceFile = node.getSourceFile();
  const typeParameters = typeParameterText(sourceFile, node.typeParameters);
  const parameters = node.parameters
    .map((parameter) => parameterText(checker, parameter))
    .join(", ");
  return `${name}${typeParameters}(${parameters}): ${returnTypeText(checker, node.type)};`;
};

type RenderState = {
  readonly checker: ts.TypeChecker;
  readonly declarations: ReadonlyMap<string, Declaration>;
  readonly rendered: Map<string, RenderedInterface>;
  readonly referencedTypes: Set<string>;
};

const renderInterfaceFromDeclaration = (
  state: RenderState,
  declaration: ts.InterfaceDeclaration,
  outputName: string,
): string => {
  const lines: string[] = [`interface ${outputName} {`];

  for (const member of declaration.members) {
    if (ts.isMethodSignature(member)) {
      const name = getPropertyName(member.name);
      if (name === null) {
        continue;
      }
      const signature = renderMethodSignature(state.checker, member, name);
      collectTypeNames(signature, state.referencedTypes);
      lines.push(`${getJsDocComment(member)}    ${signature}`);
      continue;
    }

    if (!ts.isPropertySignature(member)) {
      continue;
    }

    const name = getPropertyName(member.name);
    if (name === null) {
      continue;
    }

    if (member.type && ts.isFunctionTypeNode(member.type)) {
      const signature = renderMethodSignature(state.checker, member.type, name);
      collectTypeNames(signature, state.referencedTypes);
      lines.push(`${getJsDocComment(member)}    ${signature}`);
      continue;
    }

    const shapeName = parseEffectValueShape(member.type);
    if (shapeName !== null) {
      const childOutputName =
        outputName === "ScriptApi" ? interfaceNameForProperty(name) : nestedInterfaceName(outputName, name);
      renderApiInterface(state, shapeName, childOutputName);
      lines.push(`    readonly ${name}: ${childOutputName};`);
      continue;
    }

    const reference = parseTypeReference(member.type);
    const childDeclaration =
      reference === null
        ? null
        : getDeclaration(state.declarations, reference.unqualifiedName);
    if (childDeclaration && ts.isInterfaceDeclaration(childDeclaration)) {
      const childOutputName =
        outputName === "ScriptContext" && name === "api"
          ? "ScriptApi"
          : nestedInterfaceName(outputName, name);
      renderApiInterface(state, childDeclaration.name.text, childOutputName);
      lines.push(`    readonly ${name}: ${childOutputName};`);
      continue;
    }

    const readonly = member.modifiers?.some(
      (modifier) => modifier.kind === ts.SyntaxKind.ReadonlyKeyword,
    )
      ? "readonly "
      : "";
    const optional = member.questionToken === undefined ? "" : "?";
    const type = formatType(state.checker, member.type);
    collectTypeNames(type, state.referencedTypes);
    lines.push(`${getJsDocComment(member)}    ${readonly}${name}${optional}: ${type};`);
  }

  lines.push("}");
  return lines.join("\n");
};

const renderPacketApiInterface = (state: RenderState, outputName: string): void => {
  if (state.rendered.has(outputName)) {
    return;
  }

  const packetShape = getInterface(state.declarations, "PacketShape");
  const packetApi = getInterface(state.declarations, "ScriptPacketApi");
  const exposedSendMethods = new Set(["sendClient", "sendServer"]);
  const lines: string[] = [`interface ${outputName} {`];

  for (const declaration of [packetShape, packetApi]) {
    for (const member of declaration.members) {
      if (!ts.isMethodSignature(member)) {
        continue;
      }
      const name = getPropertyName(member.name);
      if (name === null) {
        continue;
      }
      if (declaration === packetShape && !exposedSendMethods.has(name)) {
        continue;
      }
      if (declaration === packetApi && exposedSendMethods.has(name)) {
        continue;
      }
      const signature = renderMethodSignature(state.checker, member, name);
      collectTypeNames(signature, state.referencedTypes);
      lines.push(`${getJsDocComment(member)}    ${signature}`);
    }
  }

  lines.push("}");
  state.rendered.set(outputName, { name: outputName, content: lines.join("\n") });
};

const renderApiInterface = (
  state: RenderState,
  sourceName: string,
  outputName: string,
): void => {
  if (state.rendered.has(outputName)) {
    return;
  }

  if (sourceName === "ScriptPacketApi") {
    renderPacketApiInterface(state, outputName);
    return;
  }

  const declaration = getInterface(state.declarations, sourceName);
  state.rendered.set(outputName, {
    name: outputName,
    content: renderInterfaceFromDeclaration(state, declaration, outputName),
  });
};

const stripDeclarationText = (text: string): string =>
  transformTypeText(text)
    .replace(/^export\s+/gm, "")
    .replace(/^declare\s+/gm, "")
    .replace(/\bprivate\s+/g, "")
    .replace(/\bprotected\s+/g, "")
    .replace(/#private;\n?/g, "")
    .replace(/import\([^)]*\)\./g, "")
    .replace(/Schema\.Literals<[^;]+;/g, "unknown;");

const renderClassAsInterface = (
  checker: ts.TypeChecker,
  declaration: ts.ClassDeclaration,
): string => {
  const name = declaration.name?.text ?? fail("Cannot render anonymous class");
  const sourceFile = declaration.getSourceFile();
  const typeParameters = typeParameterText(sourceFile, declaration.typeParameters);
  const extendsClause = declaration.heritageClauses
    ?.flatMap((clause) =>
      clause.token === ts.SyntaxKind.ExtendsKeyword
        ? clause.types.map((type) => type.getText(type.getSourceFile()))
        : [],
    )
    .at(0);
  const lines = [
    `interface ${name}${typeParameters}${extendsClause ? ` extends ${extendsClause}` : ""} {`,
  ];

  for (const member of declaration.members) {
    const modifiers = ts.canHaveModifiers(member) ? ts.getModifiers(member) : undefined;
    if (
      modifiers?.some(
        (modifier) =>
          modifier.kind === ts.SyntaxKind.PrivateKeyword ||
          modifier.kind === ts.SyntaxKind.ProtectedKeyword ||
          modifier.kind === ts.SyntaxKind.StaticKeyword,
      )
    ) {
      continue;
    }

    if (ts.isGetAccessorDeclaration(member)) {
      const propertyName = getPropertyName(member.name);
      if (propertyName === null) continue;
      lines.push(`  readonly ${propertyName}: ${returnTypeText(checker, member.type)};`);
      continue;
    }

    if (ts.isPropertyDeclaration(member)) {
      const propertyName = getPropertyName(member.name);
      if (propertyName === null) continue;
      const optional = member.questionToken === undefined ? "" : "?";
      lines.push(`  ${propertyName}${optional}: ${formatType(checker, member.type)};`);
      continue;
    }

    if (ts.isMethodDeclaration(member)) {
      const methodName = getPropertyName(member.name);
      if (methodName === null) continue;
      const sourceFile = member.getSourceFile();
      const typeParameters = typeParameterText(sourceFile, member.typeParameters);
      const parameters = member.parameters
        .map((parameter) => parameterText(checker, parameter))
        .join(", ");
      lines.push(
        `  ${methodName}${typeParameters}(${parameters}): ${returnTypeText(checker, member.type)};`,
      );
    }
  }

  lines.push("}");
  return lines.join("\n");
};

const isSchemaTypeAlias = (declaration: ts.TypeAliasDeclaration): boolean => {
  const reference = parseTypeReference(declaration.type);
  return reference?.name === "Schema.Schema.Type";
};

const renderTypeAlias = (
  checker: ts.TypeChecker,
  declaration: ts.TypeAliasDeclaration,
): string => {
  if (!isSchemaTypeAlias(declaration)) {
    return stripDeclarationText(declaration.getText(declaration.getSourceFile()));
  }

  const typeParameters = typeParameterText(
    declaration.getSourceFile(),
    declaration.typeParameters,
  );
  return `type ${declaration.name.text}${typeParameters} = ${formatType(
    checker,
    declaration.type,
  )};`;
};

const declarationText = (
  checker: ts.TypeChecker,
  declaration: Declaration,
): string | null => {
  const sourceFile = declaration.getSourceFile();
  const name = declaration.name?.text;
  if (
    name === "ScriptExecutionError" ||
    name === "ScriptNotReadyError" ||
    name === "BridgeError" ||
    name === "ArmyError"
  ) {
    return null;
  }

  if (ts.isClassDeclaration(declaration)) {
    return renderClassAsInterface(checker, declaration);
  }

  if (ts.isTypeAliasDeclaration(declaration)) {
    return renderTypeAlias(checker, declaration);
  }

  return stripDeclarationText(declaration.getText(sourceFile));
};

const renderReferencedDeclarations = (
  state: RenderState,
  apiInterfaceNames: ReadonlySet<string>,
): readonly string[] => {
  const output: string[] = [];
  const seen = new Set([...apiInterfaceNames, ...SUPPORT_TYPE_NAMES]);
  const pending = Array.from(state.referencedTypes).sort();

  for (let index = 0; index < pending.length; index += 1) {
    const name = pending[index];
    if (!name || seen.has(name) || BUILTIN_TYPE_NAMES.has(name)) {
      continue;
    }
    seen.add(name);

    const declaration = state.declarations.get(name);
    if (!declaration) {
      output.push(`interface ${name} { readonly [key: string]: unknown; }`);
      continue;
    }

    const rendered = declarationText(state.checker, declaration);
    if (rendered === null) {
      continue;
    }
    const text = rendered;
    output.push(text);
    collectTypeNames(text, state.referencedTypes);
    for (const referenced of Array.from(state.referencedTypes)) {
      if (!seen.has(referenced) && !pending.includes(referenced)) {
        pending.push(referenced);
      }
    }
  }

  return output;
};

const renderScriptTypes = (
  program: ts.Program,
  declarations: ReadonlyMap<string, Declaration>,
): string => {
  const checker = program.getTypeChecker();
  const state: RenderState = {
    checker,
    declarations,
    rendered: new Map(),
    referencedTypes: new Set(),
  };

  renderApiInterface(state, "ScriptContext", "ScriptContext");

  const interfaceNames = new Set(state.rendered.keys());
  const referencedDeclarations = renderReferencedDeclarations(state, interfaceNames);
  const interfaces = Array.from(state.rendered.values())
    .sort((left, right) => {
      if (left.name === "ScriptContext") return -1;
      if (right.name === "ScriptContext") return 1;
      if (left.name === "ScriptApi") return -1;
      if (right.name === "ScriptApi") return 1;
      return left.name.localeCompare(right.name);
    })
    .map((entry) => entry.content);

  const lines = [
    GENERATED_HEADER,
    "",
    "/* eslint-disable */",
    "",
    SUPPORT_DECLARATIONS.trimEnd(),
    "",
    "type ScriptMain = (",
    "  context: ScriptContext,",
    ") => Generator<EffectYieldable<unknown, unknown>, unknown, any>;",
    "",
    ...interfaces,
    "",
    ...referencedDeclarations,
    "",
  ];

  return `${lines.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd()}\n`;
};

const main = async (options: CliOptions): Promise<void> => {
  const program = createProgram(options.repoRoot);
  if (!program.getSourceFile(options.sourceFile)) {
    fail(`Unable to load ${relative(options.repoRoot, options.sourceFile)}`);
  }

  const declarations = buildDeclarationMap(program);
  const content = renderScriptTypes(program, declarations);

  await fs.mkdir(dirname(options.outputFile), { recursive: true });
  const current = await fs.readFile(options.outputFile, "utf8").catch(() => null);
  if (current !== content) {
    await fs.writeFile(options.outputFile, content, "utf8");
  }

  console.info(
    `Generated scripting types at ${relative(options.repoRoot, options.outputFile)}`,
  );
};

if (
  process.argv[1] &&
  import.meta.url === pathToFileURL(process.argv[1]).href
) {
  main(parseCliOptions(process.argv.slice(2), DEFAULT_REPO_ROOT)).catch((error) => {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  });
}
